export interface AreaTransferPage {
    slug: string;
    areaName: string;
    airportName: string;
    city: string;
    country: string;
    distance: string;
    travelTime: string;
    description: string;
    longDescription: string;
    pickupProcess: string[];
    travelTips: string[];
    faq: { question: string; answer: string }[];
    relatedRoutes: { name: string; slug: string; type: 'city' | 'airport' | 'route' }[];
}

export const areaTransferPages: AreaTransferPage[] = [
    {
        slug: 'dubai-marina-to-dubai-airport',
        areaName: 'Dubai Marina',
        airportName: 'Dubai International Airport (DXB)',
        city: 'Dubai',
        country: 'United Arab Emirates',
        distance: '32 km',
        travelTime: '30–40 minutes',
        description: 'Taxi from Dubai Marina to Dubai Airport. Reliable departure transfers from the Marina district.',
        longDescription: 'Arrange a professional taxi transfer from any residence or hotel in Dubai Marina to Dubai International Airport (DXB). Our service ensures a punctual departure from the Marina, with experienced drivers who navigate the highway efficiently to reach your terminal in time for check-in.',
        pickupProcess: [
            'Driver arrives at your specified residence, apartment, or hotel entrance in Dubai Marina.',
            'Full assistance with luggage from your location to the vehicle.',
            'Direct transportation via Sheikh Zayed Road to DXB.',
            'Drop-off at the departures level for Terminal 1, 2, or 3.',
        ],
        travelTips: [
            'Leave early as traffic on Sheikh Zayed Road can be heavy during peak hours.',
            'Confirm your airline terminal (T1, T2, or T3) with the driver.',
            'We recommend departing the Marina 3 hours before international flights.',
            'Ensure all members of your group are ready at the pickup time.',
        ],
        faq: [
            { question: 'How do I arrange a taxi to the airport from Dubai Marina?', answer: 'You can book online or via WhatsApp. Provide your Marina address and flight time.' },
            { question: 'How early should I leave for my flight from the Marina?', answer: 'We suggest leaving at least 3 hours before your scheduled departure time.' },
            { question: 'Can taxis pick up from Marina residential towers?', answer: 'Yes, our drivers coordinate with tower security for pickup at the main entrance.' },
            { question: 'Is the service available for early morning flights?', answer: 'Yes, we provide 24/7 departure transfers across Dubai.' },
            { question: 'Can I book a large van for airport transit?', answer: 'Yes, we have high-capacity vans for families and shoppers.' },
        ],
        relatedRoutes: [
            { name: 'Dubai Airport Taxi', slug: '/airport/dubai-airport-taxi', type: 'airport' },
            { name: 'Dubai Taxi Service', slug: '/city/dubai-taxi', type: 'city' },
            { name: 'Taxi to Dubai Marina', slug: '/taxi-to-area/dubai-airport-to-dubai-marina', type: 'route' },
        ],
    },
    {
        slug: 'palm-jumeirah-to-dubai-airport',
        areaName: 'Palm Jumeirah',
        airportName: 'Dubai International Airport (DXB)',
        city: 'Dubai',
        country: 'United Arab Emirates',
        distance: '35 km',
        travelTime: '35–45 minutes',
        description: 'Taxi from Palm Jumeirah to Dubai Airport. Direct departure transfers from the Palm.',
        longDescription: 'Our transfer service provides reliable transportation from any villa or hotel on the Palm Jumeirah to Dubai International Airport (DXB). We handle the logistics of your return journey, ensuring a comfortable transit from the Palm to your departure terminal.',
        pickupProcess: [
            'Driver meets you at your Palm Jumeirah residence or hotel entrance.',
            'Professional help with luggage and loading into the vehicle.',
            'Direct transfer from the Palm through the city to the airport.',
            'Drop-off at the departures hall for your specific terminal.',
        ],
        travelTips: [
            'The Palm route can take longer due to the crescent geography; allow extra time.',
            'Check which terminal your airline uses at DXB.',
            'Morning traffic can be significant on the trunk of the Palm.',
            'Confirm your booking for early morning flights at least 24 hours in advance.',
        ],
        faq: [
            { question: 'How long to reach the airport from the Palm Jumeirah?', answer: 'The journey typically takes 35 to 45 minutes depending on traffic.' },
            { question: 'Can the taxi pick up from private villas?', answer: 'Yes, we provide pickups from all villas and residences on the Palm.' },
            { question: 'Are SUVs available for travelers with several bags?', answer: 'Yes, Cadillac Escalade and GMC models are available.' },
            { question: 'Is the service available at night?', answer: 'Yes, we provide 24/7 transfers from the Palm Jumeirah.' },
            { question: 'How early should I book?', answer: 'We recommend booking 12 to 24 hours before your flight.' },
        ],
        relatedRoutes: [
            { name: 'Dubai Airport Taxi', slug: '/airport/dubai-airport-taxi', type: 'airport' },
            { name: 'Dubai Taxi Service', slug: '/city/dubai-taxi', type: 'city' },
            { name: 'Taxi to Palm Jumeirah', slug: '/taxi-to-area/dubai-airport-to-palm-jumeirah', type: 'route' },
        ],
    },
    {
        slug: 'olaya-riyadh-to-riyadh-airport',
        areaName: 'Olaya District',
        airportName: 'King Khalid International Airport (RUH)',
        city: 'Riyadh',
        country: 'Saudi Arabia',
        distance: '35 km',
        travelTime: '30–40 minutes',
        description: 'Taxi from Olaya to Riyadh Airport. Professional departure transfers from central Riyadh.',
        longDescription: 'Reliable transportation from the Olaya district in central Riyadh to King Khalid International Airport (RUH). Our service provides a punctual connection for business and leisure travelers heading to the airport terminals, ensuring a stress-free departure from the capital.',
        pickupProcess: [
            'Driver arrives at your Olaya residence, office, or hotel.',
            'Full assistance with luggage and baggage loading.',
            'Direct transit via the airport highway to the departure gates.',
            'Drop-off at Terminal 1, 2, 3, 4, or 5 as per your airline.',
        ],
        travelTips: [
            'Riyadh traffic can be heavy in the late afternoon; plan accordingly.',
            'Confirm your flight terminal (International vs. Domestic) before departure.',
            'Departing Olaya 3.5 hours before your flight is recommended.',
            'Ensure all passengers have their travel documents ready.',
        ],
        faq: [
            { question: 'How do I arrange a taxi to the airport from Olaya?', answer: 'Book online or via WhatsApp. Provide your location in Olaya and flight time.' },
            { question: 'How early should I leave for a flight from Riyadh?', answer: 'We suggest leaving Olaya 3 to 4 hours before your scheduled departure.' },
            { question: 'Can taxis pick up from office towers in Olaya?', answer: 'Yes, we provide pickups from all commercial and residential buildings.' },
            { question: 'Are executive sedans available?', answer: 'Yes, Mercedes S-Class and BMW models are available for professional travel.' },
            { question: 'Is the service available daily?', answer: 'Yes, we operate 24/7 every day in Riyadh.' },
        ],
        relatedRoutes: [
            { name: 'Riyadh Airport Taxi', slug: '/airport/riyadh-airport-taxi', type: 'airport' },
            { name: 'Riyadh Taxi Service', slug: '/city/riyadh-taxi', type: 'city' },
            { name: 'Taxi to Olaya District', slug: '/taxi-to-area/riyadh-airport-to-olaya-district', type: 'route' },
        ],
    },
    {
        slug: 'west-bay-doha-to-hamad-airport',
        areaName: 'West Bay',
        airportName: 'Hamad International Airport (DOH)',
        city: 'Doha',
        country: 'Qatar',
        distance: '20 km',
        travelTime: '20–30 minutes',
        description: 'Taxi from West Bay to Hamad Airport. Reliable departure transfers from Doha business district.',
        longDescription: 'Travel from any tower or residence in West Bay to Hamad International Airport (DOH) with our professional transfer service. We provide door-to-door transportation from Doha modern commercial center to the airport departures terminal, ensuring a comfortable and timely journey.',
        pickupProcess: [
            'Professional driver awaits you at your West Bay location.',
            'Support with luggage handling and passenger boarding.',
            'Direct transportation via the Corniche or expressway to DOH.',
            'Drop-off at the airport departures gate for your airline.',
        ],
        travelTips: [
            'West Bay traffic can be busy during morning rush hours; leave with extra time.',
            'Confirm your airline departure zone with the driver.',
            'The drive to Hamad Airport typically takes 20 to 30 minutes.',
            'Request a child seat in advance if traveling with family.',
        ],
        faq: [
            { question: 'How long to reach the airport from West Bay?', answer: 'The journey typically takes 20 to 30 minutes depending on the time of day.' },
            { question: 'Can the taxi pick up from residential towers?', answer: 'Yes, we provide pickups from all hotels and towers in West Bay.' },
            { question: 'Are SUVs available for travelers with many bags?', answer: 'Yes, GMC and Cadillac models are available.' },
            { question: 'Is the service available for late-night flights?', answer: 'Yes, we provide 24/7 transfers from West Bay.' },
            { question: 'Can I book a return service from the airport?', answer: 'Yes, airport-to-West Bay transfers are also available.' },
        ],
        relatedRoutes: [
            { name: 'Doha Airport Taxi', slug: '/airport/doha-airport-taxi', type: 'airport' },
            { name: 'Doha Taxi Service', slug: '/city/doha-taxi', type: 'city' },
            { name: 'Taxi to West Bay', slug: '/taxi-to-area/doha-airport-to-west-bay', type: 'route' },
        ],
    },
    {
        slug: 'salmiya-to-kuwait-airport',
        areaName: 'Salmiya',
        airportName: 'Kuwait International Airport (KWI)',
        city: 'Salmiya',
        country: 'Kuwait',
        distance: '22 km',
        travelTime: '20–30 minutes',
        description: 'Taxi from Salmiya to Kuwait Airport. Direct departure transfers from the Salmiya district.',
        longDescription: 'Arrange your departure transfer from Salmiya to Kuwait International Airport (KWI). Our service provides a reliable connection from this popular residential and commercial area, ensuring you reach your flight terminal efficiently.',
        pickupProcess: [
            'Driver meets you at your Salmiya residence or hotel lobby.',
            'Full assistance with suitcases and baggage handling.',
            'Direct transportation to Terminal 1, 4, or 5 at the airport.',
            'Drop-off at the departures level entrance for your airline.',
        ],
        travelTips: [
            'Confirm which terminal your airline uses (T1, T4, or T5).',
            'Salmiya traffic can be slow during evening hours; leave early.',
            'The drive to KWI is approximately 20 to 30 minutes.',
            'Ensure you have your passport and ticket ready for airport entrance.',
        ],
        faq: [
            { question: 'How long to reach the airport from Salmiya?', answer: 'The journey usually takes 20 to 30 minutes.' },
            { question: 'Can the taxi pick up from private apartments?', answer: 'Yes, we provide pickups from all addresses in Salmiya.' },
            { question: 'Are larger vehicles available for families?', answer: 'Yes, we have high-capacity vans for family travel.' },
            { question: 'Is the service available at night?', answer: 'Yes, we provide 24/7 departure transfers in Kuwait.' },
            { question: 'How early should I book?', answer: 'We recommend booking at least 12 hours in advance.' },
        ],
        relatedRoutes: [
            { name: 'Kuwait Airport Taxi', slug: '/airport/kuwait-airport-taxi', type: 'airport' },
            { name: 'Kuwait City Taxi Service', slug: '/city/kuwait-city-taxi', type: 'city' },
            { name: 'Taxi to Salmiya', slug: '/taxi-to-area/kuwait-airport-to-salmiya', type: 'route' },
        ],
    },
    {
        slug: 'juffair-to-bahrain-airport',
        areaName: 'Juffair',
        airportName: 'Bahrain International Airport (BAH)',
        city: 'Manama',
        country: 'Bahrain',
        distance: '12 km',
        travelTime: '15–20 minutes',
        description: 'Taxi from Juffair to Bahrain Airport. Reliable departure transfers from the Juffair district.',
        longDescription: 'Efficient transportation from the Juffair area in Manama to Bahrain International Airport (BAH). Our professional chauffeur service ensures a comfortable and punctual journey from your residence or hotel to the airport departures.',
        pickupProcess: [
            'Driver meets you at your Juffair residence or hotel entrance.',
            'Assistance with luggage from your location to the vehicle.',
            'Direct transit through Manama to the airport terminal.',
            'Drop-off at the departures hall entrance.',
        ],
        travelTips: [
            'Juffair is close to the airport; a 20-minute journey is typical.',
            'Confirm your flight departure time during booking.',
            'Morning traffic in Manama can be busy; plan accordingly.',
            'Ensure you have all travel documents ready for inspection.',
        ],
        faq: [
            { question: 'How long is the transfer to Bahrain Airport from Juffair?', answer: 'The journey typically takes 15 to 20 minutes.' },
            { question: 'Can the driver help with multiple suitcases?', answer: 'Yes, our drivers provide full assistance with your luggage.' },
            { question: 'Are SUVs available for family travel?', answer: 'Yes, we have spacious SUVs for families.' },
            { question: 'Is the service available on holidays?', answer: 'Yes, we operate throughout the year.' },
            { question: 'How early should I leave?', answer: 'We suggest departing Juffair 2 to 3 hours before your flight.' },
        ],
        relatedRoutes: [
            { name: 'Bahrain Airport Taxi', slug: '/airport/bahrain-airport-taxi', type: 'airport' },
            { name: 'Manama Taxi Service', slug: '/city/manama-taxi', type: 'city' },
            { name: 'Taxi to Juffair', slug: '/taxi-to-area/bahrain-airport-to-juffair', type: 'route' },
        ],
    },
    {
        slug: 'qurum-to-muscat-airport',
        areaName: 'Qurum',
        airportName: 'Muscat International Airport (MCT)',
        city: 'Muscat',
        country: 'Oman',
        distance: '25 km',
        travelTime: '20–30 minutes',
        description: 'Taxi from Qurum to Muscat Airport. Professional departure transfers from the Qurum district.',
        longDescription: 'Our transfer service provides reliable transportation from the Qurum district to Muscat International Airport (MCT). We offer a professional connection from this central Muscat area, ensuring you reach the departures level comfortably and on time.',
        pickupProcess: [
            'Professional driver awaits you at your Qurum residence or hotel.',
            'Assistance with luggage and baggage loading.',
            'Comfortable transit along the Sultan Qaboos Highway.',
            'Drop-off at the departures zone of Muscat International Airport.',
        ],
        travelTips: [
            'Check your airline terminal number before departure.',
            'Traffic on the highway can be busy during rush hours; allow extra time.',
            'The drive is approximately 25 km; leaving 3 hours early is standard.',
            'Pre-booking is recommended for guaranteed availability.',
        ],
        faq: [
            { question: 'How long to reach Muscat Airport from Qurum?', answer: 'The journey typically takes 20 to 30 minutes.' },
            { question: 'Can I book a van for a large group?', answer: 'Yes, we have high-capacity vans available.' },
            { question: 'Is the service available 24/7?', answer: 'Yes, we operate all day and night in Muscat.' },
            { question: 'Does the driver assist with luggage?', answer: 'Yes, our drivers provide full support with suitcases.' },
            { question: 'How early should I book?', answer: 'We recommend booking at least 12 to 24 hours in advance.' },
        ],
        relatedRoutes: [
            { name: 'Muscat Airport Taxi', slug: '/airport/muscat-airport-taxi', type: 'airport' },
            { name: 'Muscat Taxi Service', slug: '/city/muscat-taxi', type: 'city' },
            { name: 'Taxi to Qurum', slug: '/taxi-to-area/muscat-airport-to-qurum', type: 'route' },
        ],
    },
    {
        slug: 'saadiyat-island-to-abu-dhabi-airport',
        areaName: 'Saadiyat Island',
        airportName: 'Zayed International Airport (AUH)',
        city: 'Abu Dhabi',
        country: 'United Arab Emirates',
        distance: '30 km',
        travelTime: '30–40 minutes',
        description: 'Taxi from Saadiyat Island to Abu Dhabi Airport. Reliable departure transfers from the island.',
        longDescription: 'Arrange your departure transfer from Saadiyat Island to Zayed International Airport (AUH). Our professional service provides a direct and punctual connection from any resort or residence on Saadiyat directly to the airport departures, ensuring a smooth end to your stay.',
        pickupProcess: [
            'Driver meets you at your Saadiyat residence or hotel entrance.',
            'Full assistance with baggage handling and loading.',
            'Punctual transit via the city highways to AUH terminals.',
            'Drop-off at the correct departures hall entrance.',
        ],
        travelTips: [
            'Confirm your airline terminal (T1 or Terminal A) before departure.',
            'Allow at least 40 minutes for the journey to the airport.',
            'Morning traffic can affect travel time; leave early.',
            'Ensure all members of your group are ready at the pickup point.',
        ],
        faq: [
            { question: 'How long is the transfer from Saadiyat to Abu Dhabi Airport?', answer: 'The journey typically takes 30 to 40 minutes.' },
            { question: 'Can the taxi pick up from private apartments on Saadiyat?', answer: 'Yes, we provide pickups from all addresses across the island.' },
            { question: 'Are larger vehicles available for families?', answer: 'Yes, we have high-capacity SUVs and vans.' },
            { question: 'Is the service available at night?', answer: 'Yes, we provide 24/7 departure transfers in Abu Dhabi.' },
            { question: 'How early should I book?', answer: 'We suggest booking at least 12 hours in advance.' },
        ],
        relatedRoutes: [
            { name: 'Abu Dhabi Airport Taxi', slug: '/airport/abu-dhabi-airport-taxi', type: 'airport' },
            { name: 'Abu Dhabi Taxi Service', slug: '/city/abu-dhabi-taxi', type: 'city' },
            { name: 'Taxi to Saadiyat Island', slug: '/taxi-to-area/abu-dhabi-airport-to-saadiyat-island', type: 'route' },
        ],
    },
    {
        slug: 'yas-island-to-abu-dhabi-airport',
        areaName: 'Yas Island',
        airportName: 'Zayed International Airport (AUH)',
        city: 'Abu Dhabi',
        country: 'United Arab Emirates',
        distance: '10 km',
        travelTime: '10–15 minutes',
        description: 'Taxi from Yas Island to Abu Dhabi Airport. Quick departure transfers from Yas Island.',
        longDescription: 'Efficient transportation from any hotel or attraction on Yas Island to Zayed International Airport (AUH). Our service provides a fast and reliable connection, ensuring you reach the airport departures efficiently after your stay or visit to Yas Island.',
        pickupProcess: [
            'Driver meets you at your Yas Island hotel entrance or preferred point.',
            'Assistance with luggage and baggage loading.',
            'Direct transportation to the nearby airport terminals.',
            'Drop-off at the departures level for immediate check-in.',
        ],
        travelTips: [
            'Yas Island is very close to AUH; a 15-minute journey is typical.',
            'Confirm your flight terminal (T1 or Terminal A).',
            'Allow extra time if there is a major event happening on the island.',
            'Ensure baggage matches the capacity of the chosen vehicle.',
        ],
        faq: [
            { question: 'How long to reach Abu Dhabi Airport from Yas Island?', answer: 'The drive usually takes 10 to 15 minutes.' },
            { question: 'Can the taxi pick up from Yas Mall?', answer: 'Yes, we can arrange pickups from the mall or any hotel.' },
            { question: 'Are SUVs available for families?', answer: 'Yes, we have spacious vehicles for family groups.' },
            { question: 'Is the service available daily?', answer: 'Yes, we provide 24/7 transfers in Abu Dhabi.' },
            { question: 'How early should I book?', answer: 'We recommend booking 6 to 12 hours in advance for Yas Island.' },
        ],
        relatedRoutes: [
            { name: 'Abu Dhabi Airport Taxi', slug: '/airport/abu-dhabi-airport-taxi', type: 'airport' },
            { name: 'Abu Dhabi Taxi Service', slug: '/city/abu-dhabi-taxi', type: 'city' },
            { name: 'Taxi to Yas Island', slug: '/taxi-to-area/abu-dhabi-airport-to-yas-island', type: 'route' },
        ],
    },
    {
        slug: 'kafd-riyadh-to-riyadh-airport',
        areaName: 'KAFD',
        airportName: 'King Khalid International Airport (RUH)',
        city: 'Riyadh',
        country: 'Saudi Arabia',
        distance: '28 km',
        travelTime: '25–35 minutes',
        description: 'Taxi from KAFD to Riyadh Airport. Professional departure transfers from the financial district.',
        longDescription: 'Travel from the King Abdullah Financial District (KAFD) to King Khalid International Airport (RUH) with our professional transfer service. We provide door-to-door transportation from Riyadh modern business area to the airport departures terminal, ensuring a comfortable and timely journey.',
        pickupProcess: [
            'Professional driver awaits you at your KAFD tower or hotel.',
            'Full assistance with suitcases and baggage handling.',
            'Direct transit via the North Ring Road to the airport.',
            'Drop-off at the correct departures portal for your airline.',
        ],
        travelTips: [
            'KAFD traffic can be busy during the afternoon; leave with extra time.',
            'Confirm your airline terminal number (T1-T5).',
            'The drive to RUH typically takes 25 to 35 minutes.',
            'Ensure you have all physical travel documents ready.',
        ],
        faq: [
            { question: 'How long to reach the airport from KAFD?', answer: 'The journey typically takes 25 to 35 minutes.' },
            { question: 'Can the taxi pick up from office towers in KAFD?', answer: 'Yes, we provide pickups from all towers and hotels in the district.' },
            { question: 'Are executive sedans available?', answer: 'Yes, Mercedes S-Class models are available for business travel.' },
            { question: 'Is the service available at night?', answer: 'Yes, we provide 24/7 transfers from KAFD.' },
            { question: 'How early should I book?', answer: 'We recommend booking at least 12 hours in advance.' },
        ],
        relatedRoutes: [
            { name: 'Riyadh Airport Taxi', slug: '/airport/riyadh-airport-taxi', type: 'airport' },
            { name: 'Riyadh Taxi Service', slug: '/city/riyadh-taxi', type: 'city' },
            { name: 'Taxi to KAFD', slug: '/taxi-to-area/riyadh-airport-to-kafd', type: 'route' },
        ],
    },
    {
        slug: 'jeddah-corniche-to-jeddah-airport',
        areaName: 'Jeddah Corniche',
        airportName: 'King Abdulaziz International Airport (JED)',
        city: 'Jeddah',
        country: 'Saudi Arabia',
        distance: '25 km',
        travelTime: '25–35 minutes',
        description: 'Taxi from Jeddah Corniche to Jeddah Airport. Reliable departure transfers from the waterfront.',
        longDescription: 'Arrange your departure transfer from any hotel or residence on the Jeddah Corniche to King Abdulaziz International Airport (JED). Our service provides a reliable and punctual connection from the waterfront directly to the airport departures terminal.',
        pickupProcess: [
            'Driver meets you at your Corniche location or hotel lobby.',
            'Full support with luggage loading and baggage handling.',
            'Direct transit via the city expressways to JED.',
            'Drop-off at the departures level for your specified terminal.',
        ],
        travelTips: [
            'Confirm if you are flying from the New Terminal (Terminal 1) or North Terminal.',
            'Corniche traffic can be slow in the evenings; plan accordingly.',
            'The drive to the airport is approximately 25 to 35 minutes.',
            'Ensure all passengers have their travel documents ready.',
        ],
        faq: [
            { question: 'How long is the transfer to Jeddah Airport from the Corniche?', answer: 'The journey usually takes 25 to 35 minutes.' },
            { question: 'Can I book a van for 7 passengers?', answer: 'Yes, we have high-capacity vans for family groups.' },
            { question: 'Is the service available for Umrah pilgrims?', answer: 'Yes, we provide transfers for all passengers heading to the airport.' },
            { question: 'Is pickup from the hotel lobby standard?', answer: 'Yes, our driver will meet you at the main hotel entrance.' },
            { question: 'How early should I book?', answer: 'We suggest booking at least 12 to 24 hours in advance.' },
        ],
        relatedRoutes: [
            { name: 'Jeddah Airport Taxi', slug: '/airport/king-abdulaziz-airport-taxi', type: 'airport' },
            { name: 'Jeddah Taxi Service', slug: '/city/jeddah-taxi', type: 'city' },
            { name: 'Taxi to Jeddah Corniche', slug: '/taxi-to-area/jeddah-airport-to-jeddah-corniche', type: 'route' },
        ],
    },
    {
        slug: 'lusail-city-to-hamad-airport',
        areaName: 'Lusail City',
        airportName: 'Hamad International Airport (DOH)',
        city: 'Doha',
        country: 'Qatar',
        distance: '30 km',
        travelTime: '30–40 minutes',
        description: 'Taxi from Lusail City to Hamad Airport. Professional departure transfers from Lusail.',
        longDescription: 'Reliable transportation from Lusail City to Hamad International Airport (DOH). Our service provides a professional connection for travelers heading from northern Doha to the airport departure terminal, ensuring a punctual and comfortable journey.',
        pickupProcess: [
            'Driver arrives at your specified residence or hotel in Lusail.',
            'Assistance with luggage and suitcases.',
            'Direct transit via the Lusail Expressway towards DOH.',
            'Drop-off at the airport departures hall for your airline.',
        ],
        travelTips: [
            'Lusail is north of central Doha; plan for a 35-minute journey.',
            'Confirm your airline terminal zone with the driver.',
            'Traffic on the expressway can be significant; leave early.',
            'Ensure you have all physical travel documents ready.',
        ],
        faq: [
            { question: 'How long to reach the airport from Lusail City?', answer: 'The journey typically takes 30 to 40 minutes.' },
            { question: 'Can the taxi pick up from any tower in Lusail?', answer: 'Yes, we provide pickups from all hotels and residential towers in the district.' },
            { question: 'Are SUVs available for travelers with many bags?', answer: 'Yes, Cadillac Escalade and GMC models are available.' },
            { question: 'Is the service available 24/7?', answer: 'Yes, we provide departure transfers all day and night.' },
            { question: 'Can I book a return service?', answer: 'Yes, airport-to-Lusail transfers are also available.' },
        ],
        relatedRoutes: [
            { name: 'Doha Airport Taxi', slug: '/airport/doha-airport-taxi', type: 'airport' },
            { name: 'Doha Taxi Service', slug: '/city/doha-taxi', type: 'city' },
            { name: 'Taxi to Lusail City', slug: '/taxi-to-area/doha-airport-to-lusail-city', type: 'route' },
        ],
    },
];
