export interface AttractionPage {
    slug: string;
    attractionName: string;
    attractionType: 'Theme Park' | 'Amusement Park' | 'Entertainment Venue' | 'Family Attraction' | 'Water Park';
    city: string;
    cityCountry: string;
    locationDetails: string;
    approxTravelTime: string;
    description: string;
    longDescription: string;
    features: string[];
    travelTips: string[];
    faq: { question: string; answer: string }[];
    relatedRoutes: { name: string; slug: string; type: 'city' | 'airport' | 'route' }[];
}

export const attractionPages: AttractionPage[] = [
    {
        slug: 'ferrari-world-abu-dhabi',
        attractionName: 'Ferrari World',
        attractionType: 'Theme Park',
        city: 'Abu Dhabi',
        cityCountry: 'United Arab Emirates',
        locationDetails: 'Yas Island, Abu Dhabi',
        approxTravelTime: '20–40 minutes from Abu Dhabi city, 60–90 minutes from Dubai',
        description: 'Taxi to Ferrari World Abu Dhabi. Direct transfers to the world\'s first Ferrari-themed park on Yas Island for high-speed thrills and family fun.',
        longDescription: 'Ferrari World Abu Dhabi is a premier indoor theme park located on Yas Island. It features the world\'s fastest roller coaster, Formula Rossa, along with numerous Ferrari-inspired rides, driving experiences, and family attractions. Our taxi service provides reliable door-to-door transfers from any location in Abu Dhabi or Dubai directly to the park entrance.',
        features: [
            'Home to Formula Rossa, the world\'s fastest roller coaster',
            'Over 40 record-breaking rides and attractions',
            'Interactive Ferrari driving experiences and simulators',
            'A wide variety of Italian-themed dining and retail outlets',
            'Completely climate-controlled indoor environment for year-round visits',
        ],
        travelTips: [
            'Arrive early at the park opening to experience popular rides with shorter wait times.',
            'Confirm the specific entrance location on Yas Island with your driver.',
            'Plan for a full day visit to experience all the major rides and shows.',
            'Book your taxi well in advance if traveling from Dubai or other emirates.',
            'Check for seasonal events or maintenance schedules on the official park website.',
        ],
        faq: [
            { question: 'How do I get to Ferrari World by taxi?', answer: 'We offer direct transfers from any hotel, residence, or airport in the UAE to Ferrari World on Yas Island.' },
            { question: 'Can taxis pick up from hotels or airports?', answer: 'Yes. We provide pickups from Zayed International Airport, Dubai Airport, and all regional hotels.' },
            { question: 'How long is the drive from Dubai?', answer: 'The journey from Dubai typically takes 60 to 90 minutes depending on your specific pickup point.' },
            { question: 'Can large groups travel together to the park?', answer: 'Yes. We have high-capacity vans and minibuses available for families and large groups.' },
            { question: 'Can I arrange a return transfer?', answer: 'Yes. You can schedule a return trip in advance to ensure a driver is ready after your visit.' },
        ],
        relatedRoutes: [
            { name: 'Abu Dhabi Taxi Service', slug: '/city/abu-dhabi-taxi', type: 'city' },
            { name: 'Abu Dhabi Airport Taxi', slug: '/airport/abu-dhabi-airport-taxi', type: 'airport' },
            { name: 'Taxi to Yas Island', slug: '/taxi-to-destination/yas-island-abu-dhabi', type: 'route' },
        ],
    },
    {
        slug: 'motiongate-dubai',
        attractionName: 'Motiongate Dubai',
        attractionType: 'Theme Park',
        city: 'Dubai',
        cityCountry: 'United Arab Emirates',
        locationDetails: 'Dubai Parks and Resorts, Sheikh Zayed Road',
        approxTravelTime: '30–50 minutes from central Dubai',
        description: 'Taxi to Motiongate Dubai. Transfers to the Hollywood-inspired theme park featuring DreamWorks, Columbia Pictures, and Lionsgate attractions.',
        longDescription: 'Motiongate Dubai is the largest Hollywood-inspired theme park in the Middle East, located within Dubai Parks and Resorts. It features cinematic rides and attractions based on famous films from DreamWorks Animation, Columbia Pictures, and Lionsgate. Our taxi service provides convenient transfers from any part of Dubai or the airport directly to the park hub.',
        features: [
            'Cinematic rides inspired by Hollywood blockbusters',
            'Themed zones including DreamWorks, Lionsgate, and Columbia Pictures',
            'Live entertainment and meet-and-greet sessions with movie characters',
            'Located within the Dubai Parks and Resorts destination',
            'Features both thrilling roller coasters and family-friendly attractions',
        ],
        travelTips: [
            'Plan your travel time during the morning to maximize your stay at the park.',
            'Confirm your drop-off point at the main entrance hub of Dubai Parks and Resorts.',
            'Wear comfortable footwear as the park involves significant walking between zones.',
            'Check the daily show schedule upon arrival to plan your visit around live performances.',
            'Allow extra time for travel during weekends and public holidays when the park is busiest.',
        ],
        faq: [
            { question: 'How do I reach Motiongate Dubai from the city center?', answer: 'We offer direct taxi transfers from any Dubai location to Motiongate on Sheikh Zayed Road.' },
            { question: 'Is airport pickup available for the theme park?', answer: 'Yes. We provide transfers from Dubai International Airport (DXB) and Al Maktoum Airport (DWC).' },
            { question: 'Can groups travel together to Motiongate?', answer: 'Yes. SUVs and passenger vans are available for families and tourist groups.' },
            { question: 'What is the best time to arrive?', answer: 'Arriving at park opening is recommended to avoid long queues for the most popular rides.' },
            { question: 'Can I book a return transfer after the park closes?', answer: 'Yes. We recommend pre-booking your return journey to ensure availability during park closing hours.' },
        ],
        relatedRoutes: [
            { name: 'Dubai Taxi Service', slug: '/city/dubai-taxi', type: 'city' },
            { name: 'Dubai Airport Taxi', slug: '/airport/dubai-airport-taxi', type: 'airport' },
            { name: 'Taxi to Legoland Dubai', slug: '/taxi-to-attraction/legoland-dubai-dubai', type: 'route' },
        ],
    },
    {
        slug: 'riyadh-winter-wonderland-riyadh',
        attractionName: 'Riyadh Winter Wonderland',
        attractionType: 'Amusement Park',
        city: 'Riyadh',
        cityCountry: 'Saudi Arabia',
        locationDetails: 'Riyadh Season Zone, Northern Riyadh',
        approxTravelTime: '20–40 minutes from central Riyadh',
        description: 'Taxi to Riyadh Winter Wonderland. Direct transfers to the iconic amusement park and winter festival zone in Riyadh.',
        longDescription: 'Riyadh Winter Wonderland is a massive seasonal amusement park and a centerpiece of the Riyadh Season festival. It features an extensive collection of international rides, games, and winter-themed attractions. Our taxi service provides easy access to the venue from any part of Riyadh, ensuring a smooth journey for families and tourists.',
        features: [
            'One of the largest seasonal amusement parks in the region',
            'Wide array of international rides for all age groups',
            'Winter-themed festive atmosphere with global dining options',
            'Major zone within the city-wide Riyadh Season festival',
            'Features live shows, competitions, and entertainment events',
        ],
        travelTips: [
            'Arrive early as evening traffic near the venue can be very heavy.',
            'Check the specific gate entrance on your booking or the Riyadh Season app.',
            'Evening visits are cooler and more popular; plan travel time accordingly.',
            'Ensure you have your digital entry tickets ready for the gate security.',
            'Book your return taxi in advance to avoid waiting after the park closes.',
        ],
        faq: [
            { question: 'How do I get to Riyadh Winter Wonderland?', answer: 'We provide direct transfers from any hotel or residence in Riyadh to the venue gates.' },
            { question: 'Can taxis pick up from Riyadh Airport?', answer: 'Yes. Direct transfers are available from King Khalid International Airport (RUH).' },
            { question: 'Are there vehicles for large families?', answer: 'Yes. We have high-capacity SUVs and vans available for family groups.' },
            { question: 'How long is the journey from the city center?', answer: 'The drive typically takes 20 to 35 minutes depending on current traffic conditions.' },
            { question: 'Do you operate late at night?', answer: 'Yes. Our service is available 24/7 to cover all late-night festival activities.' },
        ],
        relatedRoutes: [
            { name: 'Riyadh Taxi Service', slug: '/city/riyadh-taxi', type: 'city' },
            { name: 'Riyadh Airport Taxi', slug: '/airport/riyadh-airport-taxi', type: 'airport' },
            { name: 'Taxi to Riyadh Season', slug: '/taxi-to-event/riyadh-season-riyadh', type: 'route' },
        ],
    },
    {
        slug: 'img-worlds-of-adventure-dubai',
        attractionName: 'IMG Worlds of Adventure',
        attractionType: 'Theme Park',
        city: 'Dubai',
        cityCountry: 'United Arab Emirates',
        locationDetails: 'Sheikh Mohammed Bin Zayed Road, Dubai',
        approxTravelTime: '20–40 minutes from central Dubai',
        description: 'Taxi to IMG Worlds of Adventure Dubai. Professional transfers to the world\'s largest indoor theme park featuring Marvel and Cartoon Network zones.',
        longDescription: 'IMG Worlds of Adventure is the world\'s largest indoor theme park, offering year-round climate-controlled entertainment. It features distinct zones themed around Marvel, Cartoon Network, and the Lost Valley Dinosaur Adventure. Our taxi service provides reliable transportation from anywhere in Dubai or the airport to the theme park entrance.',
        features: [
            'World\'s largest indoor theme park with full climate control',
            'Themed zones including Marvel Universe and Cartoon Network',
            'Thrilling roller coasters and state-of-the-art interactive rides',
            'Home to the Lost Valley Dinosaur Adventure zone',
            'Extensive retail and dining options within the facility',
        ],
        travelTips: [
            'The park is completely indoor, making it an ideal destination for summer visits.',
            'Confirm your pickup time well in advance for weekend afternoon trips.',
            'Arrive at the park opening to experience the major rides before peak crowds.',
            'Inform your driver whether you need the main entrance or a group drop-off point.',
            'Allow for extra travel time on the E311 highway during evening rush hours.',
        ],
        faq: [
            { question: 'How do I reach IMG Worlds of Adventure?', answer: 'We offer direct transfers from any hotel or apartment in Dubai to the park entrance.' },
            { question: 'Can I book a taxi from Dubai Airport?', answer: 'Yes. We provide direct pickups from DXB and DWC airports.' },
            { question: 'Can families travel together in one vehicle?', answer: 'Yes. Large SUVs and passenger vans are available for family groups.' },
            { question: 'How far is the park from Dubai Marina?', answer: 'The drive from Dubai Marina typically takes 25 to 35 minutes.' },
            { question: 'Can I book a return transfer?', answer: 'Yes. Return journeys can be pre-scheduled to ensure a driver is ready after your visit.' },
        ],
        relatedRoutes: [
            { name: 'Dubai Taxi Service', slug: '/city/dubai-taxi', type: 'city' },
            { name: 'Dubai Airport Taxi', slug: '/airport/dubai-airport-taxi', type: 'airport' },
            { name: 'Taxi to Global Village', slug: '/taxi-to-attraction/global-village-dubai', type: 'route' },
        ],
    },
    {
        slug: 'legoland-dubai-dubai',
        attractionName: 'Legoland Dubai',
        attractionType: 'Theme Park',
        city: 'Dubai',
        cityCountry: 'United Arab Emirates',
        locationDetails: 'Dubai Parks and Resorts, Sheikh Zayed Road',
        approxTravelTime: '30–50 minutes from central Dubai',
        description: 'Taxi to Legoland Dubai. Family-friendly transfers to the Lego-themed park and water park at Dubai Parks and Resorts.',
        longDescription: 'Legoland Dubai is a major family attraction located within Dubai Parks and Resorts. Designed for families with children aged 2-12, it features Lego-themed rides, building experiences, and a dedicated water park. Our taxi service provides comfortable and safe transportation for families from any part of Dubai or the airport directly to the park gates.',
        features: [
            'Over 40 Lego-themed rides, shows, and building experiences',
            'Includes Miniland — iconic architecture built with Lego bricks',
            'Specifically designed for families with younger children',
            'Located within the Dubai Parks and Resorts complex',
            'Adjacent to the Legoland Water Park',
        ],
        travelTips: [
            'Arrive early to enjoy the indoor building experiences during the warmer daytime hours.',
            'Confirm which specific entrance you need (Legoland Theme Park or Water Park).',
            'Most visitors spend a full day; plan your return transfer accordingly.',
            'Weekend mornings are the most popular time for family visits.',
            'Dress children in comfortable clothing suitable for active play and walking.',
        ],
        faq: [
            { question: 'How do I get to Legoland Dubai by taxi?', answer: 'We provide direct transfers from anywhere in Dubai to the Legoland entrance at Dubai Parks and Resorts.' },
            { question: 'Can taxis pick up from Dubai Airport?', answer: 'Yes. We offer direct transfers from DXB and DWC airports to the park.' },
            { question: 'Are child seats available for families?', answer: 'Yes. Child seats can be requested when you place your booking.' },
            { question: 'How long is the drive from Downtown Dubai?', answer: 'The journey typically takes 40 to 50 minutes depending on traffic.' },
            { question: 'Can I book a return transfer?', answer: 'Yes. You can schedule a return trip in advance to ensure a driver is ready.' },
        ],
        relatedRoutes: [
            { name: 'Dubai Taxi Service', slug: '/city/dubai-taxi', type: 'city' },
            { name: 'Dubai Airport Taxi', slug: '/airport/dubai-airport-taxi', type: 'airport' },
            { name: 'Taxi to Motiongate Dubai', slug: '/taxi-to-attraction/motiongate-dubai', type: 'route' },
        ],
    },
    {
        slug: 'doha-quest-doha',
        attractionName: 'Doha Quest',
        attractionType: 'Theme Park',
        city: 'Doha',
        cityCountry: 'Qatar',
        locationDetails: 'Doha Oasis, Msheireb',
        approxTravelTime: '10–25 minutes from central Doha',
        description: 'Taxi to Doha Quest. Direct transfers to Qatar\'s largest indoor theme park located in the Doha Oasis complex.',
        longDescription: 'Doha Quest is a premier indoor theme park located within the Doha Oasis complex in the Msheireb area. It features over 30 rides and attractions, including the world\'s tallest indoor roller coaster and indoor drop tower. Our taxi service provides quick and professional transfers to this central entertainment hub from any location in Doha.',
        features: [
            'Qatar\'s largest indoor theme park with over 30 attractions',
            'Home to the world\'s tallest indoor roller coaster (EpiQ Coaster)',
            'Themed zones representing the past, present, and future',
            'Centrally located within the upscale Doha Oasis complex',
            'Ideal destination for year-round indoor family entertainment',
        ],
        travelTips: [
            'The park is centrally located in Msheireb; allow for city traffic during peak hours.',
            'Confirm your drop-off at the Doha Oasis complex entrance for the theme park.',
            'Arriving during the morning or early afternoon on weekdays is recommended.',
            'Plan your visit around the main show times featured in the park app.',
            'Check for age and height restrictions on major rides before your visit.',
        ],
        faq: [
            { question: 'How do I reach Doha Quest by taxi?', answer: 'We offer direct transfers to the Doha Oasis complex from any part of the city.' },
            { question: 'Can I get a taxi from Hamad Airport to Doha Quest?', answer: 'Yes. We provide direct transfers from Hamad International Airport (DOH).' },
            { question: 'Are vehicles available for groups?', answer: 'Yes. SUVs and passenger vans are available for family and group outings.' },
            { question: 'How far is it from West Bay?', answer: 'The drive from West Bay typically takes 10 to 20 minutes.' },
            { question: 'Can I book a return pickup?', answer: 'Yes. You can schedule a return transfer to ensure a vehicle is ready when you finish.' },
        ],
        relatedRoutes: [
            { name: 'Doha Taxi Service', slug: '/city/doha-taxi', type: 'city' },
            { name: 'Doha Airport Taxi', slug: '/airport/doha-airport-taxi', type: 'airport' },
            { name: 'Taxi to Msheireb', slug: '/taxi-to-business/msheireb-downtown-doha', type: 'route' },
        ],
    },
    {
        slug: 'warner-bros-world-abu-dhabi',
        attractionName: 'Warner Bros. World',
        attractionType: 'Theme Park',
        city: 'Abu Dhabi',
        cityCountry: 'United Arab Emirates',
        locationDetails: 'Yas Island, Abu Dhabi',
        approxTravelTime: '20–40 minutes from Abu Dhabi city, 60–90 minutes from Dubai',
        description: 'Taxi to Warner Bros. World Abu Dhabi. Direct transfers to the fully indoor theme park featuring DC Comics and Looney Tunes characters.',
        longDescription: 'Warner Bros. World Abu Dhabi is a massive fully indoor theme park on Yas Island. It features six immersive lands, including Metropolis, Gotham City, and Cartoon Junction, housing over 29 state-of-the-art rides and attractions. Our taxi service provides reliable door-to-door transfers from any part of the UAE directly to the park.',
        features: [
            'World\'s first-ever Warner Bros. branded indoor theme park',
            'Six immersive themed lands featuring iconic characters',
            'Fully climate-controlled environment ideal for all seasons',
            'Includes major rides based on Batman, Superman, and Wonder Woman',
            'Extensive live entertainment and meet-and-greet sessions',
        ],
        travelTips: [
            'As an indoor park, it is a perfect destination during the summer months.',
            'Plan to arrive when the park opens to explore the most popular zones first.',
            'Confirm the specific Yas Island drop-off point with your driver.',
            'Allow for city traffic if traveling from central Abu Dhabi during evening hours.',
            'Pre-book your return taxi to ensure a driver is ready after the park closes.',
        ],
        faq: [
            { question: 'How do I reach Warner Bros. World by taxi?', answer: 'We offer direct transfers from any location in Abu Dhabi or Dubai to the park entrance.' },
            { question: 'Is airport pickup available for the theme park?', answer: 'Yes. We provide transfers from Zayed International Airport (AUH) directly to Yas Island.' },
            { question: 'Are there vehicles for large families?', answer: 'Yes. SUVs and passenger vans are available for group travel.' },
            { question: 'How long is the journey from central Abu Dhabi?', answer: 'The drive typically takes 20 to 35 minutes depending on traffic.' },
            { question: 'Can I schedule a return transfer?', answer: 'Yes. Round-trip bookings can be arranged when you place your reservation.' },
        ],
        relatedRoutes: [
            { name: 'Abu Dhabi Taxi Service', slug: '/city/abu-dhabi-taxi', type: 'city' },
            { name: 'Abu Dhabi Airport Taxi', slug: '/airport/abu-dhabi-airport-taxi', type: 'airport' },
            { name: 'Taxi to Ferrari World', slug: '/taxi-to-attraction/ferrari-world-abu-dhabi', type: 'route' },
        ],
    },
    {
        slug: 'global-village-dubai',
        attractionName: 'Global Village',
        attractionType: 'Entertainment Venue',
        city: 'Dubai',
        cityCountry: 'United Arab Emirates',
        locationDetails: 'Sheikh Mohammed Bin Zayed Road, Dubai',
        approxTravelTime: '20–40 minutes from central Dubai',
        description: 'Taxi to Global Village Dubai. Transfers to the city’s premier multicultural festival and amusement park for shopping, dining, and live entertainment.',
        longDescription: 'Global Village is Dubai’s most popular multicultural destination, operating seasonally from October to April. It features numerous international pavilions, an extensive amusement park (Carnaval), and daily live performances. Our taxi service provides easy and reliable transportation from any part of Dubai directly to the Global Village taxi hub.',
        features: [
            'Massive multicultural destination with global trade pavilions',
            'Extensive amusement park area with international rides',
            'Multicultural dining and street food from around the world',
            'Daily live shows, cultural performances, and major concerts',
            'Open seasonally during the cooler months in the UAE',
        ],
        travelTips: [
            'Global Village is only open during the evenings; check daily operating hours.',
            'Arrive early as evening traffic on Sheikh Mohammed Bin Zayed Road is very heavy.',
            'Expect significant crowds during weekends and public holidays.',
            'Follow signage to the designated taxi and chauffeur pickup area for your return.',
            'Wear comfortable footwear as the site is vast and involves a lot of walking.',
        ],
        faq: [
            { question: 'How do I get to Global Village by taxi?', answer: 'We provide direct door-to-door transfers to the Global Village entrance hub.' },
            { question: 'Is airport transfer available to Global Village?', answer: 'Yes. We offer transfers from Dubai International Airport (DXB) and DWC.' },
            { question: 'Can large groups travel together?', answer: 'Yes. SUVs and high-capacity vans are available for families and groups.' },
            { question: 'How far is it from Downtown Dubai?', answer: 'The drive typically takes 20 to 30 minutes depending on traffic conditions.' },
            { question: 'Can I book a return transfer from the venue?', answer: 'Yes. We recommend pre-booking your return to ensure a vehicle is available.' },
        ],
        relatedRoutes: [
            { name: 'Dubai Taxi Service', slug: '/city/dubai-taxi', type: 'city' },
            { name: 'Dubai Airport Taxi', slug: '/airport/dubai-airport-taxi', type: 'airport' },
            { name: 'Taxi to IMG Worlds', slug: '/taxi-to-attraction/img-worlds-of-adventure-dubai', type: 'route' },
        ],
    },
];
