export interface BusinessPage {
    slug: string;
    districtName: string;
    districtType: 'Financial District' | 'Business Hub' | 'Corporate Office Area';
    city: string;
    cityCountry: string;
    locationDetails: string;
    approxTravelTime: string;
    description: string;
    longDescription: string;
    features: string[];
    travelTips: string[];
    faq: { question: string; answer: string }[];
    relatedRoutes: { name: string; slug: string; type: 'city' | 'airport' | 'route' }[];
}

export const businessPages: BusinessPage[] = [
    {
        slug: 'king-abdullah-financial-district-riyadh',
        districtName: 'King Abdullah Financial District (KAFD)',
        districtType: 'Financial District',
        city: 'Riyadh',
        cityCountry: 'Saudi Arabia',
        locationDetails: 'Northern Riyadh, near Northern Ring Road',
        approxTravelTime: '20–40 minutes from central Riyadh',
        description: 'Taxi to KAFD Riyadh. Direct transfers for business meetings, corporate visits, and finance professional travel in Northern Riyadh.',
        longDescription: 'King Abdullah Financial District (KAFD) is the premier financial and business hub of Riyadh. It houses major banks, corporate headquarters, and government institutions. Our taxi service provides reliable transportation for business professionals traveling from hotels, the airport, or other city areas to their meetings in KAFD.',
        features: [
            'Major center for international banking and finance',
            'Home to numerous corporate headquarters',
            'Modern office towers and conference facilities',
            'Integrated residential and retail spaces',
            'Central location in Saudi Arabia\'s financial landscape',
        ],
        travelTips: [
            'Allow extra travel time during the morning and evening rush hours.',
            'Confirm the specific tower and entrance for your meeting.',
            'Plan to arrive at least 15 minutes before your scheduled meeting.',
            'Use designated taxi drop-off points within the district.',
            'Keep your appointment confirmation ready if needed for building security.',
        ],
        faq: [
            { question: 'How do I reach the KAFD business district?', answer: 'We offer direct taxi transfers from any location in Riyadh. You can book in advance for a punctual arrival.' },
            { question: 'Can taxis pick up from hotels in Riyadh?', answer: 'Yes. We provide collection services from all major hotels and residential compounds in Riyadh.' },
            { question: 'Are airport pickups available for business travelers?', answer: 'Yes. We offer direct transfers from King Khalid International Airport to KAFD.' },
            { question: 'Can I book a return taxi for after my meeting?', answer: 'Yes. You can schedule a return pickup to ensure minimum waiting time after your business day.' },
            { question: 'Are larger vehicles available for business teams?', answer: 'Yes. We have vans and minibuses available for groups or delegations traveling together.' },
        ],
        relatedRoutes: [
            { name: 'Riyadh Taxi Service', slug: '/city/riyadh-taxi', type: 'city' },
            { name: 'Riyadh Airport Taxi', slug: '/airport/riyadh-airport-taxi', type: 'airport' },
            { name: 'Taxi to Riyadh Season', slug: '/taxi-to-event/riyadh-season-riyadh', type: 'route' },
        ],
    },
    {
        slug: 'difc-dubai',
        districtName: 'Dubai International Financial Centre (DIFC)',
        districtType: 'Financial District',
        city: 'Dubai',
        cityCountry: 'United Arab Emirates',
        locationDetails: 'Sheikh Zayed Road area, near Downtown Dubai',
        approxTravelTime: '15–30 minutes from most central Dubai areas',
        description: 'Taxi to DIFC Dubai. Reliable transportation for corporate meetings, legal services, and business visits on Sheikh Zayed Road.',
        longDescription: 'Dubai International Financial Centre (DIFC) is the leading global financial hub in the Middle East and South Asia. It is home to hundreds of financial institutions, law firms, and corporate offices. Our taxi service offers direct and comfortable transfers from any part of the city or the airport to the various towers within DIFC.',
        features: [
            'Global financial hub with international regulation',
            'Prime location on Sheikh Zayed Road',
            'Concentration of international banks and law firms',
            'Home to the Gate District and various office towers',
            'Professional business environment with dining and retail',
        ],
        travelTips: [
            'Confirm whether your meeting is in the Gate District or one of the surrounding towers.',
            'Sheikh Zayed Road traffic can be heavy; plan your travel accordingly.',
            'Drop-off at the closest building entrance is more efficient than self-parking.',
            'Most buildings in DIFC require visitor registration at the reception.',
            'Wear formal business attire as appropriate for the DIFC professional environment.',
        ],
        faq: [
            { question: 'How do I reach DIFC by taxi?', answer: 'We provide door-to-door transfers from anywhere in Dubai directly to your office at DIFC.' },
            { question: 'Can I get a taxi from Dubai Airport to DIFC?', answer: 'Yes. We offer direct transfers from DXB and DWC airports to the DIFC district.' },
            { question: 'Is pickup available from any hotel in Dubai?', answer: 'Yes. We collect passengers from all hotels, including those in Downtown, Marina, and the Palm.' },
            { question: 'Are vehicles available for a delegation of 5 people?', answer: 'Yes. We have SUVs and executive vans that can accommodate larger business groups.' },
            { question: 'Can I arrange a return pickup from my meeting?', answer: 'Yes. Pre-booked return transfers are recommended for a seamless end to your business trip.' },
        ],
        relatedRoutes: [
            { name: 'Dubai Taxi Service', slug: '/city/dubai-taxi', type: 'city' },
            { name: 'Dubai Airport Taxi', slug: '/airport/dubai-airport-taxi', type: 'airport' },
            { name: 'Taxi to Dubai Mall', slug: '/taxi-to-mall/dubai-mall-dubai', type: 'route' },
        ],
    },
    {
        slug: 'lusail-business-district-doha',
        districtName: 'Lusail Business District',
        districtType: 'Business Hub',
        city: 'Doha',
        cityCountry: 'Qatar',
        locationDetails: 'Lusail City, North of Doha',
        approxTravelTime: '20–35 minutes from central Doha',
        description: 'Taxi to Lusail Business District. Professional transfers for meetings, corporate visits, and business travel in Qatar\'s new urban hub.',
        longDescription: 'Lusail Business District is a modern commercial center located within Lusail City, just north of Doha. It features state-of-the-art office spaces and attracts a growing number of local and international businesses. Our taxi service provides efficient transportation from anywhere in Doha, including Hamad Airport, to Lusail.',
        features: [
            'Qatar\'s newest commercial and business center',
            'Modern skyscrapers and office infrastructure',
            'Sustainable city planning and smart facilities',
            'Close proximity to Lusail Stadium and residential areas',
            'Growing hub for international corporations and agencies',
        ],
        travelTips: [
            'Lusail is a developing city; confirm the exact tower address with your driver.',
            'Road layouts in Lusail can change with development; allow for extra navigation time.',
            'Plan to arrive early for your appointment to locate the correct office building.',
            'Check for parking or visitor drop-off signs as you enter the business district.',
            'Request a return pickup in advance as Lusail is slightly north of the main city.',
        ],
        faq: [
            { question: 'How do I reach the Lusail Business District?', answer: 'We offer direct transfers from any location in Doha to your specific office in Lusail City.' },
            { question: 'Is airport pickup available for Lusail?', answer: 'Yes. We provide direct transfers from Hamad International Airport (DOH) to Lusail.' },
            { question: 'Can taxis pick up from hotels in West Bay?', answer: 'Yes. We serve all hotels in West Bay and other Doha districts.' },
            { question: 'Are there vehicles for large corporate groups?', answer: 'Yes. We have vans and minibuses available for business teams and delegations.' },
            { question: 'How long before my meeting should I book?', answer: 'For a punctual arrival in Lusail, we recommend booking at least 2 hours in advance during peak periods.' },
        ],
        relatedRoutes: [
            { name: 'Doha Taxi Service', slug: '/city/doha-taxi', type: 'city' },
            { name: 'Doha Airport Taxi', slug: '/airport/doha-airport-taxi', type: 'airport' },
            { name: 'Taxi to Lusail Stadium', slug: '/taxi-to-event/lusail-stadium-doha', type: 'route' },
        ],
    },
    {
        slug: 'kuwait-financial-centre-kuwait-city',
        districtName: 'Kuwait Financial Centre',
        districtType: 'Financial District',
        city: 'Kuwait City',
        cityCountry: 'Kuwait',
        locationDetails: 'Central Business District, Kuwait City',
        approxTravelTime: '15–30 minutes from most city areas',
        description: 'Taxi to Kuwait Financial Centre. Direct transfers for banking, finance, and corporate meetings in central Kuwait City.',
        longDescription: 'The Kuwait Financial Centre is the heart of the country\'s banking and investment sector. Located in the central business district of Kuwait City, it houses major financial institutions and corporate offices. Our taxi service provides reliable transportation for professionals traveling from all districts of Kuwait.',
        features: [
            'Kuwait\'s primary hub for banking and finance',
            'Central location in the heart of the capital city',
            'High concentration of investment and financial firms',
            'Professional business setting near the Kuwait Towers',
            'Major center for national and international corporate offices',
        ],
        travelTips: [
            'Traffic in central Kuwait City can be heavy during office hours.',
            'Ensure you have the specific building or entrance name for your destination.',
            'Allow for potential security checks when entering major financial buildings.',
            'Most offices in the financial center follow standard business hours.',
            'Book your return trip in advance to avoid waiting after your workday.',
        ],
        faq: [
            { question: 'How do I reach the Kuwait Financial Centre?', answer: 'We offer direct transfers from any area in Kuwait to the central financial district.' },
            { question: 'Can airport transfers be arranged?', answer: 'Yes. We provide direct transfers from Kuwait International Airport to the financial center.' },
            { question: 'Do you pick up from hotels in Salmiya?', answer: 'Yes. We serve all major hotels in districts like Salmiya and the city center.' },
            { question: 'Can larger vehicles be booked for a team?', answer: 'Yes. We have SUVs and vans available for corporate groups traveling together.' },
            { question: 'Is the service available for evening meetings?', answer: 'Yes. Our taxi services are available 24/7 to suit all business schedules.' },
        ],
        relatedRoutes: [
            { name: 'Kuwait City Taxi Service', slug: '/city/kuwait-city-taxi', type: 'city' },
            { name: 'Kuwait Airport Taxi', slug: '/airport/kuwait-airport-taxi', type: 'airport' },
            { name: 'Taxi to Avenues Mall', slug: '/taxi-to-mall/avenues-mall-kuwait-city', type: 'route' },
        ],
    },
    {
        slug: 'bahrain-financial-harbour-manama',
        districtName: 'Bahrain Financial Harbour',
        districtType: 'Financial District',
        city: 'Manama',
        cityCountry: 'Bahrain',
        locationDetails: 'Waterfront, Manama',
        approxTravelTime: '10–25 minutes from central Manama',
        description: 'Taxi to Bahrain Financial Harbour. Professional transfers for finance, business meetings, and corporate travel in Manama\'s waterfront district.',
        longDescription: 'Bahrain Financial Harbour (BFH) is the kingdom\'s premier financial district, located on the waterfront of Manama. It is an iconic business hub housing international banks, insurance firms, and major corporations. Our taxi service provides punctual and professional transfers for all your business needs in BFH.',
        features: [
            'Iconic waterfront business and financial district',
            'Home to numerous international banks and financial firms',
            'Integrated office towers with state-of-the-art facilities',
            'Central business location in the heart of Manama',
            'Premier destination for Bahrain\'s corporate community',
        ],
        travelTips: [
            'Bahrain Financial Harbour consists of several towers; confirm your tower and floor.',
            'Manama traffic can be busy on weekday mornings; leave early for meetings.',
            'Drop-off at the main car park or building entrance is recommended.',
            'Visitors may need to register at the main security office or reception.',
            'Inform your driver whether you need a specific tower entrance.',
        ],
        faq: [
            { question: 'How do I reaching Bahrain Financial Harbour?', answer: 'We provide direct door-to-door transfers from anywhere in Bahrain to BFH.' },
            { question: 'Are airport pickups available for Manama?', answer: 'Yes. We offer transfers from Bahrain International Airport (BAH) to Financial Harbour.' },
            { question: 'Can taxis pick up from hotels in the Seef District?', answer: 'Yes. we pick up from all hotels and residences across Manama and Bahrain.' },
            { question: 'Are there vehicles for corporate delegations?', answer: 'Yes. We have executive vans and larger vehicles for professional groups.' },
            { question: 'Can a return pickup be booked after a meeting?', answer: 'Yes. Round-trip bookings can be arranged easily when you make your reservation.' },
        ],
        relatedRoutes: [
            { name: 'Bahrain Taxi Service', slug: '/city/bahrain-taxi', type: 'city' },
            { name: 'Bahrain Airport Taxi', slug: '/airport/bahrain-airport-taxi', type: 'airport' },
            { name: 'Taxi to City Centre Bahrain', slug: '/taxi-to-mall/city-centre-bahrain-manama', type: 'route' },
        ],
    },
    {
        slug: 'business-bay-dubai',
        districtName: 'Business Bay',
        districtType: 'Business Hub',
        city: 'Dubai',
        cityCountry: 'United Arab Emirates',
        locationDetails: 'South of Downtown Dubai, along Dubai Canal',
        approxTravelTime: '10–25 minutes from Downtown Dubai',
        description: 'Taxi to Business Bay Dubai. Direct transfers for office meetings, corporate visits, and professional travel in this major commercial hub.',
        longDescription: 'Business Bay is a major commercial hub in Dubai, located adjacent to Downtown Dubai and the Dubai Canal. It features scores of office towers and is home to thousands of companies across diverse sectors. Our taxi service provides efficient transportation for all your corporate and professional needs in Business Bay.',
        features: [
            'Dense commercial and office district in the city center',
            'Home to thousands of international and local companies',
            'Scenic location along the Dubai Canal',
            'Modern skyscrapers with executive office facilities',
            'Professional business environment in close proximity to Downtown',
        ],
        travelTips: [
            'Business Bay is very large; confirm the exact name of your office tower.',
            'Traffic within Business Bay can be heavy, especially near the main access roads.',
            'Coordinate with your office host for any specific visitor parking or access info.',
            'Allow for walking time as some towers are located within larger complexes.',
            'Pre-book for morning arrivals to ensure a punctual meeting start.',
        ],
        faq: [
            { question: 'How do I reach Business Bay by taxi?', answer: 'We offer direct transfers from any location in Dubai to all towers in Business Bay.' },
            { question: 'Can I get a taxi from Dubai Airport?', answer: 'Yes. We provide direct transfers from DXB and DWC to the Business Bay area.' },
            { question: 'Do you serve all office towers in Business Bay?', answer: 'Yes. Our drivers are familiar with all major commercial buildings in the district.' },
            { question: 'Are group vehicles available for business teams?', answer: 'Yes. Vans and SUVs are available for larger groups traveling together.' },
            { question: 'Can I arrange a return transfer after work?', answer: 'Yes. You can schedule a pickup at any time to return to your hotel or the airport.' },
        ],
        relatedRoutes: [
            { name: 'Dubai Taxi Service', slug: '/city/dubai-taxi', type: 'city' },
            { name: 'Dubai Airport Taxi', slug: '/airport/dubai-airport-taxi', type: 'airport' },
            { name: 'Taxi to Burj Khalifa', slug: '/taxi-to-destination/dubai-mall-dubai', type: 'route' },
        ],
    },
    {
        slug: 'abu-dhabi-global-market-abu-dhabi',
        districtName: 'Abu Dhabi Global Market (ADGM)',
        districtType: 'Financial District',
        city: 'Abu Dhabi',
        cityCountry: 'United Arab Emirates',
        locationDetails: 'Al Maryah Island, Abu Dhabi',
        approxTravelTime: '15–30 minutes from central Abu Dhabi',
        description: 'Taxi to ADGM Abu Dhabi. Professional transfers for financial services, business visits, and meetings on Al Maryah Island.',
        longDescription: 'Abu Dhabi Global Market (ADGM) is an international financial center located on Al Maryah Island in Abu Dhabi. It is a premier business venue housing international financial institutions, asset managers, and corporate offices. Our taxi service provides direct and professional transportation to ADGM.',
        features: [
            'Leading international financial center in the UAE capital',
            'Located on the prestigious Al Maryah Island waterfront',
            'Home to global banks and institutional investors',
            'State-of-the-art business and conference infrastructure',
            'High-profile location for the Abu Dhabi business community',
        ],
        travelTips: [
            'ADGM is located on Al Maryah Island; follow directional signs for the financial center.',
            'Confirm which specific building or plaza entrance you need to enter.',
            'Nearby hotels like Rosewood and Four Seasons are common for business visitors.',
            'Business attire is standard for professionals visiting ADGM.',
            'Allow extra time if your meeting involves passing through multiple security checks.',
        ],
        faq: [
            { question: 'How do I reach ADGM by taxi?', answer: 'We provide door-to-door transfers from anywhere in Abu Dhabi or Dubai to Al Maryah Island.' },
            { question: 'Is airport transfer available to Al Maryah Island?', answer: 'Yes. We offer direct transfers from Zayed International Airport to the ADGM.' },
            { question: 'Can I book a taxi from Dubai to ADGM?', answer: 'Yes. We provide intercity transfers for business travelers from Dubai to Abu Dhabi.' },
            { question: 'Are vehicles for executive travel available?', answer: 'Yes. We offer Mercedes S-Class and other executive models for business guests.' },
            { question: 'Can I schedule a return pickup to the airport?', answer: 'Yes. Pre-booked return transfers can be arranged easily when you plan your trip.' },
        ],
        relatedRoutes: [
            { name: 'Abu Dhabi Taxi Service', slug: '/city/abu-dhabi-taxi', type: 'city' },
            { name: 'Abu Dhabi Airport Taxi', slug: '/airport/abu-dhabi-airport-taxi', type: 'airport' },
            { name: 'Taxi to Yas Island', slug: '/taxi-to-destination/yas-island-abu-dhabi', type: 'route' },
        ],
    },
    {
        slug: 'west-bay-business-district-doha',
        districtName: 'West Bay Business District',
        districtType: 'Business Hub',
        city: 'Doha',
        cityCountry: 'Qatar',
        locationDetails: 'West Bay (Al Dafna), Doha',
        approxTravelTime: '10–25 minutes from central Doha districts',
        description: 'Taxi to West Bay Doha. Reliable transportation for corporate meetings, government visits, and business travel in the heart of Doha.',
        longDescription: 'West Bay (also known as Al Dafna) is the primary commercial and business district of Doha. It is home to many of the city\'s tallest skyscrapers, international embassies, corporate headquarters, and government ministries. Our taxi service provides efficient and comfortable transfers to any part of West Bay.',
        features: [
            'Central commercial and government district of Doha',
            'Concentration of high-rise skyscrapers and corporate offices',
            'Home to many international hotels and major organizations',
            'Premier central location overlooking the Doha Corniche',
            'Main hub for Qatar\'s diplomatic and business community',
        ],
        travelTips: [
            'Identify the specific tower name or landmark as many buildings in West Bay look similar.',
            'Traffic can be congested during peak morning and evening office hours.',
            'Dropping off directly at the building entrance is recommended for convenience.',
            'Carry identification if your meeting is at a government or diplomatic office.',
            'Book your return pickup in the morning to ensure minimal wait time after work.',
        ],
        faq: [
            { question: 'How do I reaches West Bay by taxi?', answer: 'We provide direct door-to-door transfers from any area in Doha to your office in West Bay.' },
            { question: 'Can I get a taxi from Hamad Airport to West Bay hotels?', answer: 'Yes. Direct transfers are available from the airport to all major hotels in West Bay.' },
            { question: 'Do you serve the government ministries in West Bay?', answer: 'Yes. Our drivers are familiar with all the major towers and ministries in the district.' },
            { question: 'Are larger vehicles available for business teams?', answer: 'Yes. We have SUVs and vans available for group shopping or meetings.' },
            { question: 'Can I book a return transfer after my meeting?', answer: 'Yes. Pre-booked return pickups are available for a professional end to your visit.' },
        ],
        relatedRoutes: [
            { name: 'Doha Taxi Service', slug: '/city/doha-taxi', type: 'city' },
            { name: 'Doha Airport Taxi', slug: '/airport/doha-airport-taxi', type: 'airport' },
            { name: 'Taxi to The Pearl-Qatar', slug: '/taxi-to-destination/the-pearl-qatar-doha', type: 'route' },
        ],
    },
];
