export interface EmbassyPage {
    slug: string;
    embassyName: string;
    country: string;
    city: string;
    citySlug: string;
    cityCountry: string;
    airportSlug?: string;
    cityTaxiSlug?: string;
    address: string;
    district: string;
    approxTravelTime: string;
    description: string;
    longDescription: string;
    visitReasons: string[];
    travelTips: string[];
    faq: { question: string; answer: string }[];
    relatedRoutes: { name: string; slug: string; type: 'city' | 'airport' | 'route' }[];
}

export const embassyPages: EmbassyPage[] = [
    // ─── Riyadh Embassies ────────────────────────────────
    {
        slug: 'us-embassy-riyadh',
        embassyName: 'US Embassy',
        country: 'United States',
        city: 'Riyadh',
        citySlug: 'riyadh-taxi',
        cityCountry: 'Saudi Arabia',
        airportSlug: 'riyadh-airport-taxi',
        cityTaxiSlug: 'riyadh-taxi',
        address: 'Collector Road M, Riyadh Diplomatic Quarter',
        district: 'Diplomatic Quarter (DQ)',
        approxTravelTime: '20–40 minutes from most Riyadh districts',
        description: 'Taxi service to the US Embassy in Riyadh. Reliable door-to-door transfers for visa appointments, passport services, and consular visits.',
        longDescription: 'The US Embassy in Riyadh is located in the Diplomatic Quarter. It handles consular services for US citizens and visa applicants. Our taxi service provides pickups from homes, hotels, and Riyadh airport directly to the embassy entrance.',
        visitReasons: [
            'Visa application and renewal appointments',
            'US passport renewal and issuance',
            'Consular registration for US citizens',
            'Document authentication and notarial services',
            'Emergency travel document assistance',
        ],
        travelTips: [
            'Arrive at least 30 minutes before your appointment for security screening.',
            'Carry a printed copy of your appointment confirmation.',
            'Bring your original passport and required supporting documents.',
            'Electronic devices may need to be stored outside the embassy.',
            'Inform your driver of the specific gate or entrance you need.',
        ],
        faq: [
            { question: 'Where is the US Embassy in Riyadh?', answer: 'The US Embassy is located in the Diplomatic Quarter (DQ) of Riyadh, off Collector Road M.' },
            { question: 'Can a taxi pick me up from my hotel in Riyadh?', answer: 'Yes, we offer pickups from all hotels, residences, and serviced apartments across Riyadh.' },
            { question: 'Can I arrange a pickup from Riyadh Airport to the embassy?', answer: 'Yes, we provide direct transfers from King Khalid International Airport to the US Embassy.' },
            { question: 'What vehicles are available for embassy trips?', answer: 'We offer sedans such as the Ford Taurus and Camry, and SUVs such as the Cadillac Escalade and GMC for group or family trips.' },
            { question: 'Can I book a return trip after my embassy appointment?', answer: 'Yes, we can arrange a pickup after your appointment. Waiting time can also be arranged.' },
        ],
        relatedRoutes: [
            { name: 'Riyadh Taxi Service', slug: '/city/riyadh-taxi', type: 'city' },
            { name: 'Riyadh Airport Taxi', slug: '/airport/riyadh-airport-taxi', type: 'airport' },
            { name: 'Riyadh to Jeddah Taxi', slug: '/routes/riyadh-to-jeddah-taxi', type: 'route' },
        ],
    },
    {
        slug: 'uk-embassy-riyadh',
        embassyName: 'UK Embassy',
        country: 'United Kingdom',
        city: 'Riyadh',
        citySlug: 'riyadh-taxi',
        cityCountry: 'Saudi Arabia',
        airportSlug: 'riyadh-airport-taxi',
        cityTaxiSlug: 'riyadh-taxi',
        address: 'Diplomatic Quarter, Riyadh',
        district: 'Diplomatic Quarter (DQ)',
        approxTravelTime: '20–40 minutes from most Riyadh districts',
        description: 'Taxi service to the British Embassy in Riyadh. Door-to-door transfers for visa appointments, passport services, and consular visits.',
        longDescription: 'The British Embassy in Riyadh is situated in the Diplomatic Quarter and provides consular services for UK nationals and visa applicants. Our taxi service offers reliable, on-time pickups from anywhere in Riyadh, including the airport, hotels, and residential areas.',
        visitReasons: [
            'UK visa applications and renewals',
            'British passport renewal and emergency travel documents',
            'Consular assistance for British nationals',
            'Document certification and notarization',
            'Registration of births and marriages abroad',
        ],
        travelTips: [
            'Carry your appointment reference number in printed or digital form.',
            'Security checks at the gate require adequate time; arrive early.',
            'Personal electronic devices are generally not allowed inside.',
            'Bring original documents as photocopies alone may not be accepted.',
            'Inform your driver of the specific gate required for your appointment.',
        ],
        faq: [
            { question: 'Where is the British Embassy in Riyadh?', answer: 'The British Embassy is in the Diplomatic Quarter of Riyadh.' },
            { question: 'Can I get a taxi from my hotel to the UK Embassy?', answer: 'Yes, we provide hotel pickups from all areas of Riyadh.' },
            { question: 'Is airport transfer to the UK Embassy available?', answer: 'Yes, we can arrange transfers from King Khalid International Airport directly to the British Embassy.' },
            { question: 'Can I book a driver to wait for me during my appointment?', answer: 'Yes, driver waiting can be arranged. Please mention this when booking.' },
            { question: 'What is the nearest landmark to the UK Embassy in Riyadh?', answer: 'The British Embassy is located in the Diplomatic Quarter, near the International Medical Center.' },
        ],
        relatedRoutes: [
            { name: 'Riyadh Taxi Service', slug: '/city/riyadh-taxi', type: 'city' },
            { name: 'Riyadh Airport Taxi', slug: '/airport/riyadh-airport-taxi', type: 'airport' },
            { name: 'Riyadh to Dammam Taxi', slug: '/routes/riyadh-to-dammam-taxi', type: 'route' },
        ],
    },
    {
        slug: 'pakistan-embassy-riyadh',
        embassyName: 'Pakistan Embassy',
        country: 'Pakistan',
        city: 'Riyadh',
        citySlug: 'riyadh-taxi',
        cityCountry: 'Saudi Arabia',
        airportSlug: 'riyadh-airport-taxi',
        cityTaxiSlug: 'riyadh-taxi',
        address: 'Diplomatic Quarter, Riyadh',
        district: 'Diplomatic Quarter (DQ)',
        approxTravelTime: '20–40 minutes from most Riyadh districts',
        description: 'Taxi to the Pakistan Embassy in Riyadh. Transfers for passport, visa, and consular services for Pakistani nationals in Saudi Arabia.',
        longDescription: 'The Pakistan Embassy in Riyadh serves the large Pakistani expatriate community in Saudi Arabia. Services include passport renewal, attestation, CNIC verification, and other consular needs. Our taxi service ensures you reach the embassy on time with a comfortable, door-to-door pickup.',
        visitReasons: [
            'Pakistani passport renewal and collection',
            'Document attestation and verification',
            'CNIC (National Identity Card) services',
            'Power of attorney attestation',
            'Consular assistance for Pakistani nationals',
        ],
        travelTips: [
            'Bring the original and photocopies of all required documents.',
            'Queues can be long; early morning appointments are generally smoother.',
            'Have your token or appointment number ready before arriving.',
            'Dress appropriately for embassy visits.',
            'Keep your Saudi Iqama (residency permit) with you if applicable.',
        ],
        faq: [
            { question: 'Where is the Pakistan Embassy in Riyadh?', answer: 'The Pakistan Embassy is located in the Diplomatic Quarter of Riyadh.' },
            { question: 'Can I book a taxi from the Riyadh Diplomatic Quarter?', answer: 'Yes, we provide pickups and drop-offs throughout the Diplomatic Quarter and all Riyadh districts.' },
            { question: 'Can a driver pick me up from the airport?', answer: 'Yes, we offer transfers from King Khalid International Airport to the Pakistan Embassy.' },
            { question: 'How long does the ride from South Riyadh to the Embassy take?', answer: 'From areas like Al Diriyah or South Riyadh, the journey typically takes 30 to 40 minutes.' },
            { question: 'What vehicle types are available?', answer: 'We offer family sedans, large SUVs like the GMC and Cadillac Escalade, and vans for group travel.' },
        ],
        relatedRoutes: [
            { name: 'Riyadh Taxi Service', slug: '/city/riyadh-taxi', type: 'city' },
            { name: 'Riyadh Airport Taxi', slug: '/airport/riyadh-airport-taxi', type: 'airport' },
            { name: 'Riyadh to Doha Taxi', slug: '/routes/riyadh-to-doha-taxi', type: 'route' },
        ],
    },
    {
        slug: 'indian-embassy-riyadh',
        embassyName: 'Indian Embassy',
        country: 'India',
        city: 'Riyadh',
        citySlug: 'riyadh-taxi',
        cityCountry: 'Saudi Arabia',
        airportSlug: 'riyadh-airport-taxi',
        cityTaxiSlug: 'riyadh-taxi',
        address: 'Diplomatic Quarter, Riyadh',
        district: 'Diplomatic Quarter (DQ)',
        approxTravelTime: '20–40 minutes from most Riyadh districts',
        description: 'Taxi to the Indian Embassy in Riyadh. Reliable transfers for passport renewal, OCI, and consular appointments for Indian nationals.',
        longDescription: 'The Indian Embassy in Riyadh serves one of the largest expatriate communities in Saudi Arabia. Services include passport renewal, emergency certificates, OCI applications, and document attestation. Our taxi service offers convenient and timely pickups from anywhere in Riyadh.',
        visitReasons: [
            'Indian passport renewal and reissuance',
            'OCI card applications and renewals',
            'Emergency certificate for travel',
            'Document attestation for Indian nationals',
            'Police clearance certificate applications',
        ],
        travelTips: [
            'Carry all original documents along with self-attested photocopies.',
            'Check the Indian Embassy website for the appointment booking system.',
            'Arrive a minimum of 30 minutes before your appointment slot.',
            'The embassy observes both Indian and Saudi public holidays.',
            'Keep your residency permit (Iqama) accessible throughout your visit.',
        ],
        faq: [
            { question: 'Where is the Indian Embassy in Riyadh?', answer: 'The Indian Embassy is located in the Diplomatic Quarter of Riyadh, Saudi Arabia.' },
            { question: 'Can I get a pickup from my apartment in Riyadh?', answer: 'Yes, we offer residential pickups throughout all parts of Riyadh.' },
            { question: 'Is airport transfer to the Indian Embassy available?', answer: 'Yes, we provide direct rides from Riyadh Airport to the Indian Embassy.' },
            { question: 'Do you serve Indian communities in Al Malaz or Batha?', answer: 'Yes, we provide pickups from all Riyadh neighborhoods including Al Malaz, Batha, and Olaya.' },
            { question: 'Can I book a round trip?', answer: 'Yes, round-trip bookings are available. Our driver can wait or you can schedule a return pickup after your appointment.' },
        ],
        relatedRoutes: [
            { name: 'Riyadh Taxi Service', slug: '/city/riyadh-taxi', type: 'city' },
            { name: 'Riyadh Airport Taxi', slug: '/airport/riyadh-airport-taxi', type: 'airport' },
            { name: 'Riyadh to Kuwait City Taxi', slug: '/routes/riyadh-to-kuwait-city-taxi', type: 'route' },
        ],
    },
    // ─── Dubai Embassies ─────────────────────────────────
    {
        slug: 'uk-embassy-dubai',
        embassyName: 'UK Consulate-General',
        country: 'United Kingdom',
        city: 'Dubai',
        citySlug: 'dubai-taxi',
        cityCountry: 'United Arab Emirates',
        airportSlug: 'dubai-airport-taxi',
        cityTaxiSlug: 'dubai-taxi',
        address: 'Al Seef Road, Bur Dubai',
        district: 'Bur Dubai',
        approxTravelTime: '15–35 minutes from most Dubai areas',
        description: 'Taxi to the UK Consulate-General in Dubai. Reliable transfers for British passport, visa, and consular services.',
        longDescription: 'The British Consulate-General in Dubai is located in Bur Dubai and handles consular services for UK nationals living or visiting the UAE. From emergency travel documents to notarial services, our taxi service provides comfortable, punctual transfers from any part of Dubai.',
        visitReasons: [
            'UK visa enquiries and applications',
            'British passport renewal and emergency document services',
            'Notarial and document legalization services',
            'Consular assistance for UK nationals',
            'Registration of overseas births and marriages',
        ],
        travelTips: [
            'The Consulate-General is in Bur Dubai — allow time for possible traffic through city areas.',
            'Keep a printed confirmation of your appointment.',
            'Phones and electronic devices may need to be left outside the premises.',
            'Bring all original documents; copies alone are usually insufficient.',
            'Consider booking a return trip or waiting service with your driver.',
        ],
        faq: [
            { question: 'Where is the UK Consulate in Dubai?', answer: 'The British Consulate-General is located on Al Seef Road in Bur Dubai.' },
            { question: 'Can I get a taxi from Dubai Marina to the Consulate?', answer: 'Yes, we provide pickups from Dubai Marina, JBR, Palm Jumeirah, and all other Dubai areas.' },
            { question: 'Can I arrange an airport transfer to the Consulate?', answer: 'Yes, we can transfer you from Dubai International Airport (DXB) directly to the Consulate-General.' },
            { question: 'How long does the drive from Downtown Dubai take?', answer: 'From Downtown Dubai, the journey to Bur Dubai typically takes 15 to 25 minutes depending on traffic.' },
            { question: 'Is there parking near the UK Consulate?', answer: 'Limited street parking is available in the Bur Dubai area. A driver waiting service avoids the hassle of parking.' },
        ],
        relatedRoutes: [
            { name: 'Dubai Taxi Service', slug: '/city/dubai-taxi', type: 'city' },
            { name: 'Dubai Airport Taxi', slug: '/airport/dubai-airport-taxi', type: 'airport' },
            { name: 'Dubai to Abu Dhabi Taxi', slug: '/routes/dubai-to-abu-dhabi-taxi', type: 'route' },
        ],
    },
    {
        slug: 'us-embassy-abu-dhabi',
        embassyName: 'US Embassy',
        country: 'United States',
        city: 'Abu Dhabi',
        citySlug: 'abu-dhabi-taxi',
        cityCountry: 'United Arab Emirates',
        airportSlug: 'abu-dhabi-airport-taxi',
        cityTaxiSlug: 'abu-dhabi-taxi',
        address: 'Embassies District, Al Qubaisat, Abu Dhabi',
        district: 'Al Qubaisat Embassies District',
        approxTravelTime: '20–40 minutes from most Abu Dhabi areas',
        description: 'Taxi to the US Embassy in Abu Dhabi. Transfers for American visa applications, passport renewal, and consular appointments.',
        longDescription: 'The US Embassy in Abu Dhabi is located in the Embassies District and provides full consular services for US nationals residents and visa applicants. Our taxi service ensures a smooth, on-time transfer from any location in Abu Dhabi or Dubai to the embassy.',
        visitReasons: [
            'US visa applications and renewals',
            'American passport renewal and issuance',
            'Consular services for US citizens in UAE',
            'Document authentication and apostille',
            'Emergency travel assistance',
        ],
        travelTips: [
            'The embassy requires appointment confirmation before entry.',
            'No electronic devices are permitted inside; store them safely beforehand.',
            'Arrive at least 30 minutes before your appointment time.',
            'Non-immigrant visa applicants must have enrolled biometrics.',
            'Inform your driver of the exact gate for your appointment type.',
        ],
        faq: [
            { question: 'Where is the US Embassy in Abu Dhabi?', answer: 'The US Embassy is located in the Embassies District, Al Qubaisat area of Abu Dhabi.' },
            { question: 'Can I travel from Dubai to the US Embassy in Abu Dhabi?', answer: 'Yes, we provide intercity transfers from Dubai to the US Embassy in Abu Dhabi, approximately a 1.5-hour drive.' },
            { question: 'Can I get a pickup from Abu Dhabi Airport?', answer: 'Yes, we provide direct transfers from Zayed International Airport to the US Embassy.' },
            { question: 'What vehicles are available for Abu Dhabi embassy trips?', answer: 'We offer sedans like the BMW and Mercedes S-Class, and family SUVs like the GMC Yukon and Cadillac Escalade.' },
            { question: 'Can my driver wait while I am inside the embassy?', answer: 'Yes, driver waiting time can be arranged. Please mention this at the time of booking.' },
        ],
        relatedRoutes: [
            { name: 'Abu Dhabi Taxi Service', slug: '/city/abu-dhabi-taxi', type: 'city' },
            { name: 'Abu Dhabi Airport Taxi', slug: '/airport/abu-dhabi-airport-taxi', type: 'airport' },
            { name: 'Dubai to Abu Dhabi Taxi', slug: '/routes/dubai-to-abu-dhabi-taxi', type: 'route' },
        ],
    },
    // ─── Doha Embassies ──────────────────────────────────
    {
        slug: 'us-embassy-doha',
        embassyName: 'US Embassy',
        country: 'United States',
        city: 'Doha',
        citySlug: 'doha-taxi',
        cityCountry: 'Qatar',
        airportSlug: 'doha-airport-taxi',
        cityTaxiSlug: 'doha-taxi',
        address: 'Al Luqta Street, Doha',
        district: 'Al Luqta District',
        approxTravelTime: '15–30 minutes from most Doha areas',
        description: 'Taxi to the US Embassy in Doha. Reliable transfers for visa appointments, passport services, and consular visits in Qatar.',
        longDescription: 'The US Embassy in Doha serves American citizens and visa applicants in Qatar. Located in the Al Luqta area, the embassy handles a range of consular services. Our taxi service provides comfortable and on-time pickups from anywhere in Doha, including the airport and major hotels.',
        visitReasons: [
            'US visa applications for Qatar residents',
            'American passport renewal and replacement',
            'Consular services for US expatriates in Qatar',
            'Document legalization and notarial services',
            'Emergency travel document assistance',
        ],
        travelTips: [
            'Book your embassy appointment in advance through the embassy website.',
            'Security checks are thorough; arrive 30 minutes before your slot.',
            'Electronic devices are not permitted inside the compound.',
            'Carry printed documents and appointment confirmation.',
            'Let your driver know the exact entrance for your appointment type.',
        ],
        faq: [
            { question: 'Where is the US Embassy in Doha, Qatar?', answer: 'The US Embassy is located on Al Luqta Street in Doha, Qatar.' },
            { question: 'Can a taxi pick me up from The Pearl or West Bay?', answer: 'Yes, we serve all Doha areas including The Pearl, West Bay, and Lusail City.' },
            { question: 'Can I arrange a transfer from Hamad International Airport?', answer: 'Yes, we offer direct transfers from Hamad Airport (DOH) to the US Embassy in Doha.' },
            { question: 'How long is the ride from Lusail City to the US Embassy?', answer: 'From Lusail City, the drive typically takes 25 to 35 minutes depending on traffic.' },
            { question: 'What vehicle options are available?', answer: 'We offer sedans like the Toyota Camry and Ford Taurus, and larger SUVs like the GMC Yukon for families.' },
        ],
        relatedRoutes: [
            { name: 'Doha Taxi Service', slug: '/city/doha-taxi', type: 'city' },
            { name: 'Doha Airport Taxi', slug: '/airport/doha-airport-taxi', type: 'airport' },
            { name: 'Doha to Riyadh Taxi', slug: '/routes/doha-to-riyadh-taxi', type: 'route' },
        ],
    },
    // ─── Kuwait Embassies ─────────────────────────────────
    {
        slug: 'us-embassy-kuwait',
        embassyName: 'US Embassy',
        country: 'United States',
        city: 'Kuwait City',
        citySlug: 'kuwait-city-taxi',
        cityCountry: 'Kuwait',
        airportSlug: 'kuwait-airport-taxi',
        cityTaxiSlug: 'kuwait-city-taxi',
        address: 'Al-Masjid Al-Aqsa Street, Block 14, Bayan, Kuwait City',
        district: 'Bayan',
        approxTravelTime: '15–35 minutes from most Kuwait City areas',
        description: 'Taxi to the US Embassy in Kuwait City. Transfers for visa services, American passport renewal, and consular appointments.',
        longDescription: 'The US Embassy in Kuwait is located in the Bayan residential area of Kuwait City. It provides visa services, consular assistance for US citizens, and document authentication. Our taxi service offers easy, punctual pickups from any location in Kuwait City and its surroundings.',
        visitReasons: [
            'US visa applications and renewals for Kuwait residents',
            'American passport renewal and emergency documents',
            'Consular services for US nationals in Kuwait',
            'Apostille and document authentication',
            'Notarial services',
        ],
        travelTips: [
            'The Bayan area may have limited access; inform your driver in advance.',
            'Carry your appointment confirmation and all required documents.',
            'Arrive at least 30 minutes before your scheduled appointment.',
            'Electronic devices are generally not permitted inside the compound.',
            'Keep a copy of your Resident Permit (Iqama) if you are an expat.',
        ],
        faq: [
            { question: 'Where is the US Embassy in Kuwait City?', answer: 'The US Embassy is in the Bayan area of Kuwait City, on Al-Masjid Al-Aqsa Street, Block 14.' },
            { question: 'Can I book a taxi from Salmiya to the US Embassy?', answer: 'Yes, we serve all Kuwait City areas including Salmiya, Hawally, and Jahra for embassy transfers.' },
            { question: 'Can I arrange a transfer from Kuwait Airport to the embassy?', answer: 'Yes, we provide transfers from Kuwait International Airport (KWI) to the US Embassy.' },
            { question: 'What vehicles are available in Kuwait City?', answer: 'We offer sedans, SUVs, and larger passenger vans depending on your group size and requirements.' },
            { question: 'Can the driver wait for me during my embassy appointment?', answer: 'Yes, waiting time can be arranged. Let us know when you book your taxi.' },
        ],
        relatedRoutes: [
            { name: 'Kuwait City Taxi Service', slug: '/city/kuwait-city-taxi', type: 'city' },
            { name: 'Kuwait Airport Taxi', slug: '/airport/kuwait-airport-taxi', type: 'airport' },
            { name: 'Kuwait to Dammam Taxi', slug: '/routes/kuwait-to-dammam-taxi', type: 'route' },
        ],
    },
    {
        slug: 'indian-embassy-kuwait',
        embassyName: 'Indian Embassy',
        country: 'India',
        city: 'Kuwait City',
        citySlug: 'kuwait-city-taxi',
        cityCountry: 'Kuwait',
        airportSlug: 'kuwait-airport-taxi',
        cityTaxiSlug: 'kuwait-city-taxi',
        address: 'Arabian Gulf Street, Kuwait City',
        district: 'Arabian Gulf Street Area',
        approxTravelTime: '10–25 minutes from central Kuwait City',
        description: 'Taxi to the Indian Embassy in Kuwait City. Transfers for passport services, OCI applications, and consular appointments for Indian nationals.',
        longDescription: 'The Indian Embassy in Kuwait serves one of the largest Indian expatriate communities in the Gulf. Services include passport renewal, OCI cards, police clearance certificates, and document attestation. Our taxi service provides reliable and timely pickups from all Kuwait City neighborhoods.',
        visitReasons: [
            'Indian passport renewal and reissuance',
            'OCI card applications and renewals',
            'Police clearance certificate',
            'Document attestation for Indian nationals',
            'Emergency travel certificates',
        ],
        travelTips: [
            'Carry original documents and photocopies for all processes.',
            'Appointment slots book up quickly; schedule well in advance.',
            'The embassy compound is on the main Gulf Road; allow for traffic.',
            'Dress modestly when visiting the embassy.',
            'Keep your Kuwaiti Civil ID or Iqama accessible.',
        ],
        faq: [
            { question: 'Where is the Indian Embassy in Kuwait City?', answer: 'The Indian Embassy is located on Arabian Gulf Street, Kuwait City.' },
            { question: 'Can a taxi pick me up from Farwaniya for the Indian Embassy?', answer: 'Yes, we pick up from all Kuwait City areas and suburbs including Farwaniya, Hawalli, and Jahra.' },
            { question: 'Is airport-to-embassy transfer available?', answer: 'Yes, we provide transfers from Kuwait International Airport to the Indian Embassy.' },
            { question: 'How early should I book my taxi for a morning embassy appointment?', answer: 'We recommend booking at least a day in advance to ensure driver availability for early morning slots.' },
            { question: 'Can multiple people travel to the embassy together?', answer: 'Yes, family groups can use larger SUVs or vans like the Mercedes Vito or Hiace for shared transfers.' },
        ],
        relatedRoutes: [
            { name: 'Kuwait City Taxi Service', slug: '/city/kuwait-city-taxi', type: 'city' },
            { name: 'Kuwait Airport Taxi', slug: '/airport/kuwait-airport-taxi', type: 'airport' },
            { name: 'Kuwait to Dammam Taxi', slug: '/routes/kuwait-to-dammam-taxi', type: 'route' },
        ],
    },
];
