export interface GovernmentPage {
    slug: string;
    officeName: string;
    officeType: 'Immigration Office' | 'Visa Center' | 'Government Ministry' | 'Public Service Center';
    city: string;
    cityCountry: string;
    locationDetails: string;
    approxTravelTime: string;
    description: string;
    longDescription: string;
    features: string[];
    travelTips: string[];
    faq: { question: string; answer: string }[];
    relatedRoutes: { name: string; slug: string; type: 'city' | 'airport' | 'route' }[];
}

export const governmentPages: GovernmentPage[] = [
    {
        slug: 'ministry-of-interior-riyadh',
        officeName: 'Ministry of Interior',
        officeType: 'Government Ministry',
        city: 'Riyadh',
        cityCountry: 'Saudi Arabia',
        locationDetails: 'Al-Maather District, Riyadh',
        approxTravelTime: '20–35 minutes from central Riyadh',
        description: 'Taxi to Ministry of Interior Riyadh. Professional transfers for official appointments and government services in the capital.',
        longDescription: 'The Ministry of Interior in Riyadh is a major government headquarters responsible for national security and public services. Our taxi service provides punctual and professional transportation for visitors with official appointments or documentation needs at this central government facility.',
        features: [
            'Central headquarters for national security and interior affairs',
            'Primary location for various public service departments',
            'Key venue for official government appointments',
            'Located in the Al-Maather administrative district',
            'Modern facility designed for public and official visits',
        ],
        travelTips: [
            'Arrive at least 15 to 30 minutes before your scheduled appointment.',
            'Ensure you have your national ID or passport ready for entry security.',
            'Check the specific department location within the ministry complex.',
            'Morning hours are typically the busiest for public services.',
            'Confirm the office opening hours before scheduling your taxi.',
        ],
        faq: [
            { question: 'How do I reach the Ministry of Interior in Riyadh?', answer: 'We offer direct taxi transfers from any hotel or residence in Riyadh to the Ministry office.' },
            { question: 'Can I book a taxi from Riyadh Airport?', answer: 'Yes. Direct transfers are available from King Khalid International Airport (RUH).' },
            { question: 'Are vehicles available for official delegations?', answer: 'Yes. We have executive sedans and SUVs available for professional travel.' },
            { question: 'Can I arrange a return pickup?', answer: 'Yes. You can schedule a return journey to ensure a vehicle is ready after your visit.' },
            { question: 'How long is the drive from Olaya?', answer: 'The drive from the Olaya business district typically takes 15 to 25 minutes.' },
        ],
        relatedRoutes: [
            { name: 'Riyadh Taxi Service', slug: '/city/riyadh-taxi', type: 'city' },
            { name: 'Riyadh Airport Taxi', slug: '/airport/riyadh-airport-taxi', type: 'airport' },
            { name: 'Taxi to Riyadh Season', slug: '/taxi-to-event/riyadh-season-riyadh', type: 'route' },
        ],
    },
    {
        slug: 'dubai-immigration-office-dubai',
        officeName: 'Dubai Immigration Office (GDRFA)',
        officeType: 'Immigration Office',
        city: 'Dubai',
        cityCountry: 'United Arab Emirates',
        locationDetails: 'Jafiliya, Near Zabeel Park, Dubai',
        approxTravelTime: '15–30 minutes from central Dubai',
        description: 'Taxi to Dubai Immigration Office (GDRFA). Direct transfers for visa applications, residency services, and passport matters.',
        longDescription: 'The General Directorate of Residency and Foreigners Affairs (GDRFA) in Dubai, commonly known as the Immigration Office, is the primary hub for residency and visa services. Our taxi service provides reliable transportation for residents and visitors needing to visit the Jafiliya headquarters for documentation and official services.',
        features: [
            'Main headquarters for Dubai residency and visa services',
            'Primary center for passport and immigration documentation',
            'Located centrally in Jafiliya near major road networks',
            'Modern service center for individuals and corporate representatives',
            'Key facility for international visitors and expatriates',
        ],
        travelTips: [
            'Arrive early to allow time for security checks and queuing.',
            'Carry all required original documents and photocopies as required.',
            'The office is located near Zabeel Park; follow signage for GDRFA.',
            'Check for parking restrictions if you plan to be there for a long duration.',
            'Verify your appointment time on the official GDRFA website or app.',
        ],
        faq: [
            { question: 'How do I reach the Dubai Immigration Office?', answer: 'We provide direct transfers from any Dubai hotel or residence to the GDRFA office in Jafiliya.' },
            { question: 'Can I get a taxi from Dubai Airport?', answer: 'Yes. It is a 10-15 minute drive from DXB Airport to the office.' },
            { question: 'Are there vehicles for families visiting the office?', answer: 'Yes. SUVs and passenger vans are available for family groups.' },
            { question: 'Can I book a return transfer?', answer: 'Yes. You can schedule a pickup from the designated taxi area at the office.' },
            { question: 'Is the service available during workday hours?', answer: 'Yes. Our taxi service is available 24/7 to cover all morning and afternoon visits.' },
        ],
        relatedRoutes: [
            { name: 'Dubai Taxi Service', slug: '/city/dubai-taxi', type: 'city' },
            { name: 'Dubai Airport Taxi', slug: '/airport/dubai-airport-taxi', type: 'airport' },
            { name: 'Taxi to Dubai Mall', slug: '/taxi-to-mall/dubai-mall-dubai', type: 'route' },
        ],
    },
    {
        slug: 'qatar-visa-center-doha',
        officeName: 'Qatar Visa Center',
        officeType: 'Visa Center',
        city: 'Doha',
        cityCountry: 'Qatar',
        locationDetails: 'Industrial Area or Al Gharaffa, Doha',
        approxTravelTime: '20–40 minutes from central Doha',
        description: 'Taxi to Qatar Visa Center Doha. Professional transfers for visa processing, medical checkups, and biometric enrollment.',
        longDescription: 'Qatar Visa Centers (QVC) are dedicated facilities for processing employment visas, medical examinations, and biometric data. Our taxi service provides punctual transportation for workers and visitors needing to reach the centers in Doha for their visa requirements and documentation.',
        features: [
            'Dedicated facility for overseas visa and residency processing',
            'Central hub for medical checkups and biometric enrollment',
            'Located in accessible areas like Al Gharaffa and the Industrial Area',
            'Efficient processing center for expatriate documentation',
            'Modern technology-driven facility for public services',
        ],
        travelTips: [
            'Arrive at least 20 minutes before your biometric or medical appointment.',
            'Ensure you have your appointment letter and passport ready.',
            'Confirm which specific QVC location your appointment is at.',
            'Expect heavier traffic in the Industrial Area during work hours.',
            'Arrange your return taxi in advance to avoid waiting after your appointment.',
        ],
        faq: [
            { question: 'How do I reach the Qatar Visa Center?', answer: 'We offer direct transfers from any location in Doha to the designated Visa Center.' },
            { question: 'Can I book a taxi from Hamad Airport?', answer: 'Yes. Direct transfers are available from Hamad International Airport (DOH).' },
            { question: 'Are vehicles available for group workers?', answer: 'Yes. SUVs and high-capacity vans are available for group transfers.' },
            { question: 'How long is the journey from West Bay?', answer: 'The drive typically takes 20 to 30 minutes depending on traffic.' },
            { question: 'Can I arrange a return pickup?', answer: 'Yes. You can schedule a pickup to ensure a vehicle is waiting after your visit.' },
        ],
        relatedRoutes: [
            { name: 'Doha Taxi Service', slug: '/city/doha-taxi', type: 'city' },
            { name: 'Doha Airport Taxi', slug: '/airport/doha-airport-taxi', type: 'airport' },
            { name: 'Taxi to Msheireb', slug: '/taxi-to-station/doha-metro-station-doha', type: 'route' },
        ],
    },
    {
        slug: 'kuwait-ministry-of-justice-kuwait-city',
        officeName: 'Ministry of Justice',
        officeType: 'Government Ministry',
        city: 'Kuwait City',
        cityCountry: 'Kuwait',
        locationDetails: 'Al-Mirqab, Kuwait City',
        approxTravelTime: '15–30 minutes from central districts',
        description: 'Taxi to Ministry of Justice Kuwait City. Reliable transportation for legal matters, documentation, and official government visits.',
        longDescription: 'The Ministry of Justice in Kuwait City is the central authority for legal and judicial services in the country. Our taxi service provides professional transportation for individuals with court appointments, legal documentation needs, or official visits to the ministry headquarters in Al-Mirqab.',
        features: [
            'Central authority for judicial and legal services in Kuwait',
            'Primary location for official legal documentation and certificates',
            'Located in the Al-Mirqab district of Kuwait City',
            'Key facility for residents and business professionals',
            'Central hub for administrative and judicial affairs',
        ],
        travelTips: [
            'Arrive early as central Kuwait City can experience heavy morning traffic.',
            'Ensure you have all necessary case files or ID documents with you.',
            'Confirm the specific hall or department location before your visit.',
            'Check the ministry’s operating hours for public services.',
            'Pre-book your arrival taxi to ensure you reach your appointment on time.',
        ],
        faq: [
            { question: 'How do I reach the Ministry of Justice?', answer: 'We provide direct transfers from any area in Kuwait City to the Ministry entrance.' },
            { question: 'Is airport transfer available to the Ministry?', answer: 'Yes. We offer direct transfers from Kuwait International Airport (KWI).' },
            { question: 'Are executive sedans available for business visits?', answer: 'Yes. We have Mercedes and BMW models available for professional travel.' },
            { question: 'Can I book a return transfer?', answer: 'Yes. You can schedule a pickup from the designated area near the Ministry.' },
            { question: 'How long is the journey from Salmiya?', answer: 'The journey from Salmiya typically takes 20 to 25 minutes.' },
        ],
        relatedRoutes: [
            { name: 'Kuwait City Taxi Service', slug: '/city/kuwait-city-taxi', type: 'city' },
            { name: 'Kuwait Airport Taxi', slug: '/airport/kuwait-airport-taxi', type: 'airport' },
            { name: 'Taxi to Avenues Mall', slug: '/taxi-to-mall/avenues-mall-kuwait-city', type: 'route' },
        ],
    },
    {
        slug: 'bahrain-government-service-center-manama',
        officeName: 'Government Service Center',
        officeType: 'Public Service Center',
        city: 'Manama',
        cityCountry: 'Bahrain',
        locationDetails: 'Central Manama near the Diplomatic Area',
        approxTravelTime: '15–30 minutes from Bahrain Airport',
        description: 'Taxi to Bahrain Government Service Center Manama. Professional transfers for public services, IDs, and official documentation.',
        longDescription: 'The Government Service Centers in Bahrain provide a wide range of public services, including ID card renewals, documentation, and official certifications. Our taxi service offers reliable door-to-door transportation for residents and visitors needing to visit these central facilities in Manama for their administrative needs.',
        features: [
            'Flagship center for integrated government public services',
            'Primary location for ID cards, permits, and certifications',
            'Centrally located with easy access to the business district',
            'Modern facility designed for efficient public interaction',
            'Key hub for administrative services for residents and expats',
        ],
        travelTips: [
            'Arrive early as the Diplomatic Area can be very busy during business hours.',
            'Ensure you have your appointment QR code or confirmation ready.',
            'Check for required original documents before leaving for your visit.',
            'Morning visits are usually more efficient for documentation services.',
            'Pre-book your return taxi to ensure a vehicle is waiting after your visit.',
        ],
        faq: [
            { question: 'How do I reach the Government Service Center?', answer: 'We provide direct transfers from Manama and any part of Bahrain to the center.' },
            { question: 'Can I get a taxi from Bahrain Airport?', answer: 'Yes. Direct transfers are available from Bahrain International Airport (BAH).' },
            { question: 'Are vehicles available for family documentation visits?', answer: 'Yes. SUVs and high-capacity vans are available for larger groups.' },
            { question: 'How long is the journey from Juffair?', answer: 'The drive from Juffair typically takes 10 to 15 minutes.' },
            { question: 'Can I schedule a return pickup?', answer: 'Yes. You can pre-book a vehicle to be ready at a designated time.' },
        ],
        relatedRoutes: [
            { name: 'Bahrain Airport Taxi', slug: '/airport/bahrain-airport-taxi', type: 'airport' },
            { name: 'Manama to Al Khobar Taxi', slug: '/routes/manama-to-al-khobar-taxi', type: 'route' },
            { name: 'Taxi to City Centre Bahrain', slug: '/taxi-to-mall/city-centre-bahrain-manama', type: 'route' },
        ],
    },
    {
        slug: 'ministry-of-foreign-affairs-muscat',
        officeName: 'Ministry of Foreign Affairs',
        officeType: 'Government Ministry',
        city: 'Muscat',
        cityCountry: 'Oman',
        locationDetails: 'Al Sarooj, Muscat',
        approxTravelTime: '15–30 minutes from central Muscat',
        description: 'Taxi to Ministry of Foreign Affairs Muscat. Direct transfers for attestation services, official visits, and diplomatic matters.',
        longDescription: 'The Ministry of Foreign Affairs in Muscat is the central authority for international relations and document attestation services. Our taxi service provides punctual and professional transportation for visitors with official appointments or attestation needs at the ministry headquarters in Al Sarooj.',
        features: [
            'Central headquarters for Oman’s international and diplomatic affairs',
            'Primary location for official document attestation services',
            'Located in the beautiful Al Sarooj district of Muscat',
            'Key venue for diplomatic meetings and official visits',
            'Modern administrative complex with public service facilities',
        ],
        travelTips: [
            'Arrive at the ministry at least 15 minutes before your attestation appointment.',
            'Carry your original documents and the required fees for attestation.',
            'Ensure you have your national ID or passport for entry clearance.',
            'Check the specific gate for public service and attestation entrance.',
            'Pre-book your return taxi to ensure a dedicated vehicle is ready after your visit.',
        ],
        faq: [
            { question: 'How do I reach the Ministry of Foreign Affairs?', answer: 'We offer direct taxi transfers from any hotel or district in Muscat to the Ministry.' },
            { question: 'Is airport transfer available to the Ministry?', answer: 'Yes. We provide direct transfers from Muscat International Airport (MCT).' },
            { question: 'Are executive sedans available for diplomatic visits?', answer: 'Yes. We have Mercedes and BMW models available for official travel.' },
            { question: 'How long from the Al Khuwair district?', answer: 'The drive from Al Khuwair typically takes 10 to 15 minutes.' },
            { question: 'Can I book both arrival and return transfers?', answer: 'Yes. Pre-booked round-trip transfers can be arranged for your convenience.' },
        ],
        relatedRoutes: [
            { name: 'Muscat Taxi Service', slug: '/city/muscat-taxi', type: 'city' },
            { name: 'Muscat Airport Taxi', slug: '/airport/muscat-airport-taxi', type: 'airport' },
            { name: 'Taxi to Muscat Old Town', slug: '/taxi-to-landmark/muscat-old-town-muscat', type: 'route' },
        ],
    },
    {
        slug: 'ministry-of-hajj-and-umrah-jeddah',
        officeName: 'Ministry of Hajj and Umrah',
        officeType: 'Government Ministry',
        city: 'Jeddah',
        cityCountry: 'Saudi Arabia',
        locationDetails: 'Al-Hamra District, Jeddah',
        approxTravelTime: '20–35 minutes from Jeddah Airport',
        description: 'Taxi to Ministry of Hajj and Umrah Jeddah. Reliable transfers for pilgrims, travel agencies, and official hajj documentation visits.',
        longDescription: 'The Ministry of Hajj and Umrah in Jeddah is a vital government facility responsible for coordinating pilgrim services and international missions. Our taxi service provides punctual and professional transportation for visitors and representatives needing to reach the ministry for documentation or official appointments.',
        features: [
            'Primary center for coordinating international hajj and umrah missions',
            'Key facility for travel agency permits and pilgrim documentation',
            'Located in the central Al-Hamra administrative district of Jeddah',
            'Modern service center for official representatives and the public',
            'Central hub for hajj-related government planning and services',
        ],
        travelTips: [
            'Arrive early as Jeddah traffic can be heavy during the hajj and umrah seasons.',
            'Ensure you have all relevant agency permits or ID ready for the visit.',
            'Confirm the specific ministry branch if you are visiting for general services.',
            'Check the ministry operating hours, which may vary during religious seasons.',
            'Pre-book your arrival taxi to ensure you reach the office during business hours.',
        ],
        faq: [
            { question: 'How do I reach the Ministry of Hajj in Jeddah?', answer: 'We offer direct transfers from any hotel or residence in Jeddah to the Ministry office.' },
            { question: 'Can I book a taxi from Jeddah Airport to the Ministry?', answer: 'Yes. Direct transfers are available from King Abdulaziz International Airport (JED).' },
            { question: 'Are vehicles available for larger delegations?', answer: 'Yes. SUVs and high-capacity vans are available for official groups.' },
            { question: 'Can I arrange a return transfer after my visit?', answer: 'Yes. Scheduled return pickups can be arranged when you place your booking.' },
            { question: 'How long is the drive from the Corniche?', answer: 'The drive typically takes 15 to 25 minutes depending on current traffic.' },
        ],
        relatedRoutes: [
            { name: 'Jeddah Taxi Service', slug: '/city/jeddah-taxi', type: 'city' },
            { name: 'Jeddah Airport Taxi', slug: '/airport/jeddah-airport-taxi', type: 'airport' },
            { name: 'Jeddah to Makkah Taxi', slug: '/routes/jeddah-to-makkah-taxi', type: 'route' },
        ],
    },
    {
        slug: 'ministry-of-economy-abu-dhabi',
        officeName: 'Ministry of Economy',
        officeType: 'Government Ministry',
        city: 'Abu Dhabi',
        cityCountry: 'United Arab Emirates',
        locationDetails: 'Administrative District, Abu Dhabi',
        approxTravelTime: '20–40 minutes from Zayed International Airport',
        description: 'Taxi to Ministry of Economy Abu Dhabi. Professional transfers for business owners, corporate representatives, and official meetings.',
        longDescription: 'The Ministry of Economy headquarters in Abu Dhabi is the central authority for economic development, trade, and commercial regulations in the UAE. Our taxi service provides reliable transportation for business professionals and representatives needing to reach the ministry for official appointments or corporate documentation.',
        features: [
            'Central headquarters for UAE economic and trade regulations',
            'Primary location for major commercial permits and economic planning',
            'Key venue for meetings between government and private sectors',
            'Located in the primary administrative district of the capital',
            'Modern facility designed to support economic growth and business services',
        ],
        travelTips: [
            'Arrive at least 15 minutes before your scheduled business meeting.',
            'Ensure you have your Emirates ID or passport for security clearance.',
            'Confirm the specific flour or department within the ministry complex.',
            'The administrative district can experience heavy morning traffic.',
            'Pre-book your return taxi to ensure a dedicated vehicle is ready after your meeting.',
        ],
        faq: [
            { question: 'How do I get to the Ministry of Economy in Abu Dhabi?', answer: 'We provide direct transfers from any hotel or office in Abu Dhabi to the Ministry.' },
            { question: 'Is airport pickup available for ministry visits?', answer: 'Yes. We offer direct transfers from Zayed International Airport (AUH).' },
            { question: 'Are executive sedans available for corporate travel?', answer: 'Yes. We have Mercedes and BMW models available for professional use.' },
            { question: 'Can I book a return transfer from the office?', answer: 'Yes. You can schedule a pickup to ensure a vehicle is waiting after your visit.' },
            { question: 'How far is it from Al Maryah Island?', answer: 'The drive typically takes 15 to 25 minutes depending on traffic.' },
        ],
        relatedRoutes: [
            { name: 'Abu Dhabi Taxi Service', slug: '/city/abu-dhabi-taxi', type: 'city' },
            { name: 'Abu Dhabi Airport Taxi', slug: '/airport/abu-dhabi-airport-taxi', type: 'airport' },
            { name: 'Taxi to Ferrari World', slug: '/taxi-to-attraction/ferrari-world-abu-dhabi', type: 'route' },
        ],
    },
    {
        slug: 'public-authority-for-civil-information-kuwait',
        officeName: 'Public Authority for Civil Information (PACI)',
        officeType: 'Public Service Center',
        city: 'Kuwait City',
        cityCountry: 'Kuwait',
        locationDetails: 'South Surra, Kuwait City',
        approxTravelTime: '15–30 minutes from central districts',
        description: 'Taxi to PACI Kuwait City. Reliable transportation for Civil ID applications, updates, and public service collections.',
        longDescription: 'The Public Authority for Civil Information (PACI) is the primary government facility for issuing and updating Civil IDs in Kuwait. Our taxi service provides convenient transportation for residents and visitors needing to visit the South Surra headquarters for documentation, renewals, or official inquiries.',
        features: [
            'Main headquarters for Kuwait Civil ID issuance and records',
            'Primary service center for residents’ documentation and updates',
            'Located centrally in South Surra with easy road access',
            'Modern facility with dedicated halls for public interaction',
            'Key hub for all administrative services related to civil identity',
        ],
        travelTips: [
            'Arrive early as PACI service halls are often very busy in the morning.',
            'Ensure you have your appointment QR code or confirmation message.',
            'Check for any required documentation or photocopies before leaving.',
            'Morning hours on weekdays are much busier than evening service slots.',
            'Book your arrival taxi to ensure you reach the hall at your appointment time.',
        ],
        faq: [
            { question: 'How do I reach the PACI office in South Surra?', answer: 'We offer direct transfers from any area in Kuwait City to the PACI entrance.' },
            { question: 'Is airport transfer available to PACI?', answer: 'Yes. We provide direct transfers from Kuwait International Airport (KWI) to the office.' },
            { question: 'Can families travel together for their IDs?', answer: 'Yes. SUVs and high-capacity vans are available for family groups.' },
            { question: 'How long from the Salmiya district?', answer: 'The journey typically takes 15 to 25 minutes depending on traffic.' },
            { question: 'Can I book a return transfer from the office?', answer: 'Yes. You can schedule a pickup to ensure a vehicle is waiting after your appointment.' },
        ],
        relatedRoutes: [
            { name: 'Kuwait City Taxi Service', slug: '/city/kuwait-city-taxi', type: 'city' },
            { name: 'Kuwait Airport Taxi', slug: '/airport/kuwait-airport-taxi', type: 'airport' },
            { name: 'Taxi to Jaber Stadium', slug: '/taxi-to-stadium/jaber-al-ahmad-stadium-kuwait', type: 'route' },
        ],
    },
    {
        slug: 'information-egovernment-authority-bahrain',
        officeName: 'Information & eGovernment Authority (iGA)',
        officeType: 'Public Service Center',
        city: 'Isa Town',
        cityCountry: 'Bahrain',
        locationDetails: 'Isa Town, Bahrain',
        approxTravelTime: '20–35 minutes from Manama city center',
        description: 'Taxi to iGA Bahrain. Professional transfers for ID cards, eGovernment services, and official documentation in Isa Town.',
        longDescription: 'The Information & eGovernment Authority (iGA) in Isa Town is the primary center for identity and digital government services in Bahrain. Our taxi service provides reliable door-to-door transportation for residents and expatriates needing to visit the headquarters for ID card processing, documentation, and various public services.',
        features: [
            'Central hub for Bahrain identity management and eGovernment services',
            'Primary location for ID card issuance and data updates',
            'Located in Isa Town with convenient access for all residents',
            'Modern service center designed for digital and physical public interaction',
            'Key facility for the Kingdom’s administrative and identity affairs',
        ],
        travelTips: [
            'Isa Town can experience heavy traffic during peak morning hours.',
            'Ensure you have your appointment confirmation and required ID ready.',
            'Check for the specific service hall number for your appointment.',
            'Morning visits are generally more efficient for public documentation.',
            'Pre-book your return taxi to ensure a dedicated vehicle is ready after your visit.',
        ],
        faq: [
            { question: 'How do I reach the iGA office in Isa Town?', answer: 'We provide direct transfers from Manama and all parts of Bahrain to the Isa Town center.' },
            { question: 'Can I get a taxi from Bahrain Airport to iGA?', answer: 'Yes. Direct transfers are available from Bahrain International Airport (BAH).' },
            { question: 'Are vehicles available for families visiting the office?', answer: 'Yes. SUVs and passenger vans are available for larger groups.' },
            { question: 'How long is the journey from Manama?', answer: 'The drive from central Manama typically takes 15 to 25 minutes.' },
            { question: 'Can I schedule a return pickup?', answer: 'Yes. You can pre-book a vehicle for your arrival or departure from the station.' },
        ],
        relatedRoutes: [
            { name: 'Bahrain Airport Taxi', slug: '/airport/bahrain-airport-taxi', type: 'airport' },
            { name: 'Manama to Dammam Taxi', slug: '/routes/manama-to-al-khobar-taxi', type: 'route' },
            { name: 'Taxi to Bahrain Stadium', slug: '/taxi-to-stadium/bahrain-national-stadium-riffa', type: 'route' },
        ],
    },
    {
        slug: 'ministry-of-commerce-industry-muscat',
        officeName: 'Ministry of Commerce, Industry and Investment Promotion',
        officeType: 'Government Ministry',
        city: 'Muscat',
        cityCountry: 'Oman',
        locationDetails: 'Ruwi, Muscat',
        approxTravelTime: '15–30 minutes from Muscat International Airport',
        description: 'Taxi to Ministry of Commerce Muscat. Reliable transfers for business registrations, investment permits, and official documentation.',
        longDescription: 'The Ministry of Commerce, Industry and Investment Promotion in Muscat is the central authority for business and economic development in Oman. Our taxi service provides punctual transportation for business professionals and investors needing to reach the ministry headquarters in Ruwi for registration, permits, or official consultations.',
        features: [
            'Central authority for Omani business registration and trade',
            'Primary location for industrial investment permits and documentation',
            'Located in the historic business district of Ruwi in Muscat',
            'Key venue for meetings between government officials and business leaders',
            'Modern facility designed to support economic diversification and investment',
        ],
        travelTips: [
            'Ruwi is a busy business district; allow extra travel time during work hours.',
            'Ensure you have all relevant corporate documents and ID ready.',
            'Confirm the specific bureau or department for your visit.',
            'Morning and late-afternoon periods are the busiest in the Ruwi area.',
            'Pre-book your return taxi to ensure a devoted vehicle is ready after your visit.',
        ],
        faq: [
            { question: 'How do I reach the Ministry of Commerce in Muscat?', answer: 'We offer direct taxi transfers from any hotel or district in Muscat to the Ministry in Ruwi.' },
            { question: 'Is airport transfer available to the Ministry?', answer: 'Yes. We provide direct transfers from Muscat International Airport (MCT).' },
            { question: 'Are executive sedans available for investment visits?', answer: 'Yes. We have Mercedes and BMW models available for official travel.' },
            { question: 'How long from the Qurum district?', answer: 'The journey from Qurum typically takes 15 to 25 minutes.' },
            { question: 'Can I book a return transfer from the office?', answer: 'Yes. You can schedule a pickup to ensure a vehicle is waiting at a designated time.' },
        ],
        relatedRoutes: [
            { name: 'Muscat Taxi Service', slug: '/city/muscat-taxi', type: 'city' },
            { name: 'Muscat Airport Taxi', slug: '/airport/muscat-airport-taxi', type: 'airport' },
            { name: 'Taxi to Muscat Old Town', slug: '/taxi-to-landmark/muscat-old-town-muscat', type: 'route' },
        ],
    },
];
