export interface HotelTransferPage {
    slug: string;
    hotelName: string;
    airportName: string;
    city: string;
    country: string;
    distance: string;
    travelTime: string;
    description: string;
    longDescription: string;
    pickupProcess: string[];
    travelTips: string[];
    faq: { question: string; answer: string }[];
    relatedRoutes: { name: string; slug: string; type: 'city' | 'airport' | 'route' }[];
}

export const hotelTransferPages: HotelTransferPage[] = [
    {
        slug: 'burj-al-arab-to-dubai-airport',
        hotelName: 'Burj Al Arab',
        airportName: 'Dubai International Airport (DXB)',
        city: 'Dubai',
        country: 'United Arab Emirates',
        distance: '27 km',
        travelTime: '25–35 minutes',
        description: 'Taxi from Burj Al Arab to Dubai Airport. Reliable hotel pickup for return airport transfers in Dubai.',
        longDescription: 'Arrange a professional taxi transfer from the Burj Al Arab hotel directly to Dubai International Airport (DXB). Our service ensures you reach your departure terminal on time, with a driver meeting you at the hotel entrance to assist with luggage and provide a smooth journey through the city.',
        pickupProcess: [
            'Driver meets passengers at the main hotel entrance/lobby.',
            'Assistance with luggage from the hotel bell desk to the vehicle.',
            'Direct transportation to Terminal 1, 2, or 3 at DXB.',
            'Drop-off at the departures level for immediate check-in.',
        ],
        travelTips: [
            'Schedule your pickup at least 3 hours before international flights.',
            'Confirm your airline terminal (T1, T2, or T3) with the driver.',
            'Allow extra travel time during the evening rush hour in Dubai.',
            'Notify the hotel concierge if you need assistance with heavy baggage.',
        ],
        faq: [
            { question: 'How do I arrange a taxi from my hotel to the airport?', answer: 'You can book online or via WhatsApp. Provide your hotel name and flight departure time.' },
            { question: 'How early should I leave for my flight?', answer: 'We recommend leaving 3 to 4 hours before your scheduled departure for international travel.' },
            { question: 'Can taxis pick up from the hotel entrance?', answer: 'Yes, our drivers coordinate with the hotel security for direct pickup at the main entrance.' },
            { question: 'Are larger vehicles available for group transfers?', answer: 'Yes, we offer SUVs and passenger vans for families and groups.' },
            { question: 'Do you monitor flight schedules for return trips?', answer: 'For hotel pickups, we focus on your requested pickup time to ensure a timely airport arrival.' },
        ],
        relatedRoutes: [
            { name: 'Dubai Airport Taxi', slug: '/airport/dubai-airport-taxi', type: 'airport' },
            { name: 'Dubai Taxi Service', slug: '/city/dubai-taxi', type: 'city' },
            { name: 'Taxi to Dubai Mall', slug: '/taxi-to-mall/dubai-mall-dubai', type: 'route' },
        ],
    },
    {
        slug: 'atlantis-the-palm-to-dubai-airport',
        hotelName: 'Atlantis The Palm',
        airportName: 'Dubai International Airport (DXB)',
        city: 'Dubai',
        country: 'United Arab Emirates',
        distance: '37 km',
        travelTime: '35–50 minutes',
        description: 'Taxi from Atlantis The Palm to Dubai Airport. Direct airport transfers from the Palm Jumeirah.',
        longDescription: 'Our hotel transfer service provides reliable transportation from Atlantis The Palm to Dubai International Airport (DXB). We handle all the logistics, from meeting you at the hotel lobby to ensuring you reach your airline departures gate efficiently, navigating the Palm and city highways comfortably.',
        pickupProcess: [
            'Driver coordinates with hotel staff for pickup at the Atlantis lobby.',
            'Full support with baggage loading and passenger boarding.',
            'Comfortable transit from the Palm Jumeirah to the airport terminals.',
            'Drop-off directly at your specified departure terminal.',
        ],
        travelTips: [
            'Traveling from the Palm Jumeirah can take longer due to distance; leave early.',
            'Confirm your specific departure gate or concourse with the driver.',
            'Peak traffic on the Crescent can add 15 minutes to your journey.',
            'Request a child seat in advance if traveling to the airport with infants.',
        ],
        faq: [
            { question: 'How long is the drive from Atlantis to Dubai Airport?', answer: 'The journey usually takes 35 to 50 minutes depending on traffic conditions.' },
            { question: 'Can I book a van for 6 passengers and luggage?', answer: 'Yes, we have GMC and Mercedes Vito vans available for larger groups.' },
            { question: 'Is the service available for early morning flights?', answer: 'Yes, we provide 24/7 hotel-to-airport transfers in Dubai.' },
            { question: 'Can the driver help with luggage at the airport?', answer: 'The driver will drop you at the departures door where airport trolleys are available.' },
            { question: 'Do I need to pay road tolls (Salik)?', answer: 'Standard service typically includes all road tolls and surcharges.' },
        ],
        relatedRoutes: [
            { name: 'Dubai Airport Taxi', slug: '/airport/dubai-airport-taxi', type: 'airport' },
            { name: 'Dubai Taxi Service', slug: '/city/dubai-taxi', type: 'city' },
            { name: 'Taxi to Palm Jumeirah', slug: '/taxi-to-area/dubai-airport-to-palm-jumeirah', type: 'route' },
        ],
    },
    {
        slug: 'ritz-carlton-riyadh-to-riyadh-airport',
        hotelName: 'The Ritz-Carlton Riyadh',
        airportName: 'King Khalid International Airport (RUH)',
        city: 'Riyadh',
        country: 'Saudi Arabia',
        distance: '45 km',
        travelTime: '35–45 minutes',
        description: 'Taxi from Ritz-Carlton Riyadh to Riyadh Airport. Professional transfers to King Khalid International Airport.',
        longDescription: 'Reliable transportation from The Ritz-Carlton Riyadh to King Khalid International Airport (RUH). Our service provides a professional connection for business and leisure travelers heading from the hotel to the airport departure terminals, ensuring punctual arrival for check-in.',
        pickupProcess: [
            'Driver meets passengers at the hotel entrance or porte-cochère.',
            'Assistance with luggage from the hotel to the vehicle.',
            'Direct transfer to Terminal 1, 2, 3, 4, or 5 at RUH.',
            'Drop-off at the correct departures level for your airline.',
        ],
        travelTips: [
            'Allow for Riyadh traffic during the evening, which can be heavy.',
            'Confirm if your flight departs from the international or domestic terminal.',
            'The drive to RUH is approximately 45 km; leaving 3.5 hours early is recommended.',
            'Ensure you have all travel documents ready for inspection at the airport.',
        ],
        faq: [
            { question: 'How do I book a taxi from the Ritz-Carlton to the airport?', answer: 'Book online or via WhatsApp. Provide your room number or name and departure time.' },
            { question: 'How early should I leave for a flight from Riyadh?', answer: 'We recommend departing the hotel 3 to 4 hours before your flight time.' },
            { question: 'Are executive sedans available?', answer: 'Yes, Mercedes S-Class and BMW models are available for professional travel.' },
            { question: 'Can I book for a large group?', answer: 'Yes, we provide Mercedes Sprinter and Coaster buses for group departures.' },
            { question: 'Is the service available on Fridays?', answer: 'Yes, we operate 24/7 every day of the week in Riyadh.' },
        ],
        relatedRoutes: [
            { name: 'Riyadh Airport Taxi', slug: '/airport/riyadh-airport-taxi', type: 'airport' },
            { name: 'Riyadh Taxi Service', slug: '/city/riyadh-taxi', type: 'city' },
            { name: 'Taxi to Olaya District', slug: '/taxi-to-area/riyadh-airport-to-olaya-district', type: 'route' },
        ],
    },
    {
        slug: 'lusail-hotel-to-hamad-airport',
        hotelName: 'Lusail Hotels',
        airportName: 'Hamad International Airport (DOH)',
        city: 'Lusail',
        country: 'Qatar',
        distance: '30 km',
        travelTime: '25–35 minutes',
        description: 'Taxi from Lusail to Hamad Airport. Reliable return transfers from northern Doha and Lusail City.',
        longDescription: 'Travel from any hotel in Lusail City to Hamad International Airport (DOH) with our professional airport transfer service. We provide door-to-door transportation from the modern Lusail district to the Qatar departures terminal, ensuring a comfortable and timely journey for all passengers.',
        pickupProcess: [
            'Professional driver awaits you at the hotel main lobby.',
            'Support with luggage handling and vehicle loading.',
            'Efficient transit via the Lusail Expressway and C-Ring road.',
            'Drop-off at the airport departures gate for your airline.',
        ],
        travelTips: [
            'Lusail is located north of central Doha; plan for a 30-minute journey.',
            'Confirm your flight details so the driver can take you to the correct zone.',
            'Morning traffic on the expressway can be busy; leave with extra time.',
            'Ensure you have your Qatar departure clearance or travel documents ready.',
        ],
        faq: [
            { question: 'How long from Lusail to Hamad Airport?', answer: 'The journey typically takes 25 to 35 minutes depending on the time of day.' },
            { question: 'Can the taxi pick up from apartments in Lusail?', answer: 'Yes, we provide pickups from all hotels and residential towers in Lusail.' },
            { question: 'Are SUVs available for travelers with several bags?', answer: 'Yes, Cadillac Escalade and GMC models are available for heavy luggage.' },
            { question: 'Is the service available for late-night flights?', answer: 'Yes, we provide 24/7 airport transfers from all Lusail properties.' },
            { question: 'Can I book a return service from the airport?', answer: 'Yes, return pickups from the airport to Lusail can also be arranged.' },
        ],
        relatedRoutes: [
            { name: 'Doha Airport Taxi', slug: '/airport/doha-airport-taxi', type: 'airport' },
            { name: 'Doha Taxi Service', slug: '/city/doha-taxi', type: 'city' },
            { name: 'Taxi to West Bay', slug: '/taxi-to-area/doha-airport-to-west-bay', type: 'route' },
        ],
    },
    {
        slug: 'avenues-hotel-to-kuwait-airport',
        hotelName: 'The Avenues Hotels',
        airportName: 'Kuwait International Airport (KWI)',
        city: 'Kuwait City',
        country: 'Kuwait',
        distance: '15 km',
        travelTime: '15–20 minutes',
        description: 'Taxi from The Avenues to Kuwait Airport. Direct airport transfers from the Avenues mall area.',
        longDescription: 'Arrange your return transfer from hotels near The Avenues to Kuwait International Airport (KWI). Our service provides a quick and reliable connection, ensuring you reach the departure terminal efficiently after your stay or shopping visit in Kuwait City.',
        pickupProcess: [
            'Driver meets you at your hotel entrance near The Avenues.',
            'Assistance with suitcases and shopping bags.',
            'Direct transportation to Terminal 1, 4 (Kuwait Airways), or 5 (Jazeera).',
            'Drop-off at the departures level for immediate check-in.',
        ],
        travelTips: [
            'Confirm which terminal your airline operates from (T1, T4, or T5).',
            'The area around The Avenues can be busy during weekends; leave early.',
            'Traffic on the Fifth Ring Road may affect travel time during rush hours.',
            'Ensure your baggage matches the capacity of the vehicle selected.',
        ],
        faq: [
            { question: 'How long to reach the airport from The Avenues?', answer: 'The drive from The Avenues area to the airport is usually 15 to 20 minutes.' },
            { question: 'Can I get a pickup directly from the mall?', answer: 'Yes, we can arrange pickup from designated mall entrances or hotel lobbies.' },
            { question: 'Are vans available for families?', answer: 'Yes, we have high-capacity vans for families and shoppers with many bags.' },
            { question: 'Is the service available at night?', answer: 'Yes, we provide 24/7 airport transfers across Kuwait City.' },
            { question: 'How early should I book?', answer: 'We recommend booking at least 12 hours in advance for a guaranteed pickup.' },
        ],
        relatedRoutes: [
            { name: 'Kuwait Airport Taxi', slug: '/airport/kuwait-airport-taxi', type: 'airport' },
            { name: 'Kuwait City Taxi Service', slug: '/city/kuwait-city-taxi', type: 'city' },
            { name: 'Taxi to Salmiya', slug: '/taxi-to-area/kuwait-airport-to-salmiya', type: 'route' },
        ],
    },
    {
        slug: 'ritz-carlton-bahrain-to-bahrain-airport',
        hotelName: 'The Ritz-Carlton Bahrain',
        airportName: 'Bahrain International Airport (BAH)',
        city: 'Manama',
        country: 'Bahrain',
        distance: '12 km',
        travelTime: '15–20 minutes',
        description: 'Taxi from Ritz-Carlton Bahrain to Bahrain Airport. Reliable hotel pickup for return transfers in Manama.',
        longDescription: 'Efficient transportation from The Ritz-Carlton Bahrain in Manama to Bahrain International Airport (BAH). Our professional chauffeur service ensures a comfortable and punctual journey from the hotel to the airport departures, allowing you to travel with peace of mind.',
        pickupProcess: [
            'Driver meets you at the main hotel entrance gate or lobby.',
            'Full support with baggage loading and passenger assistance.',
            'Direct transit through central Manama to the airport.',
            'Drop-off at the airport departures hall entrance.',
        ],
        travelTips: [
            'The airport is relatively close; a 20-minute journey is typical.',
            'Confirm your flight terminal and departure time during booking.',
            'Peak traffic in Manama occurs during the late afternoon.',
            'Ensure you have your Bahrain residency card or passport ready.',
        ],
        faq: [
            { question: 'How long is the transfer to Bahrain Airport?', answer: 'The journey usually takes 15 to 20 minutes depending on traffic.' },
            { question: 'Can the driver help with multiple suitcases?', answer: 'Yes, our drivers provide full assistance with your luggage.' },
            { question: 'Are SUVs available for family travel?', answer: 'Yes, we have spacious SUVs for families and groups.' },
            { question: 'Is the service available on holidays?', answer: 'Yes, we operate throughout the year including public holidays.' },
            { question: 'How early should I leave?', answer: 'Departing 2 to 3 hours before your flight is standard for Bahrain.' },
        ],
        relatedRoutes: [
            { name: 'Bahrain Airport Taxi', slug: '/airport/bahrain-airport-taxi', type: 'airport' },
            { name: 'Manama Taxi Service', slug: '/city/manama-taxi', type: 'city' },
            { name: 'Taxi to Juffair', slug: '/taxi-to-area/bahrain-airport-to-juffair', type: 'route' },
        ],
    },
    {
        slug: 'al-bustan-palace-to-muscat-airport',
        hotelName: 'Al Bustan Palace',
        airportName: 'Muscat International Airport (MCT)',
        city: 'Muscat',
        country: 'Oman',
        distance: '40 km',
        travelTime: '35–45 minutes',
        description: 'Taxi from Al Bustan Palace to Muscat Airport. Professional hotel pickup for airport departures in Oman.',
        longDescription: 'Our hotel transfer service provides reliable transportation from Al Bustan Palace to Muscat International Airport (MCT). We offer a professional connection from this iconic Muscat property to the airport, ensuring you reach the departures level comfortably and on time for your flight.',
        pickupProcess: [
            'Professional driver awaits you at the hotel lobby or main gate.',
            'Assistance with luggage from the hotel to the vehicle.',
            'Comfortable transit along the Muscat coastal and city highways.',
            'Drop-off at the departures zone of Muscat International Airport.',
        ],
        travelTips: [
            'The route to the airport can take up to 45 minutes; leave early.',
            'Confirm your airline and terminal number with the driver.',
            'Traffic on the Sultan Qaboos Highway can be busy during rush hours.',
            'Pre-booking is recommended to ensure vehicle availability.',
        ],
        faq: [
            { question: 'How long to reach Muscat Airport from Al Bustan?', answer: 'The journey typically takes 35 to 45 minutes.' },
            { question: 'Can I book a van for 8 passengers?', answer: 'Yes, we have high-capacity vans for larger groups and families.' },
            { question: 'Is the service available for early morning flights?', answer: 'Yes, we operate 24/7 in Muscat for all airport transfers.' },
            { question: 'Does the driver assist with luggage?', answer: 'Yes, our drivers provide full support with your suitcases.' },
            { question: 'How early should I book my transfer?', answer: 'We recommend booking at least 24 hours in advance.' },
        ],
        relatedRoutes: [
            { name: 'Muscat Airport Taxi', slug: '/airport/muscat-airport-taxi', type: 'airport' },
            { name: 'Muscat Taxi Service', slug: '/city/muscat-taxi', type: 'city' },
            { name: 'Taxi to Qurum', slug: '/taxi-to-area/muscat-airport-to-qurum', type: 'route' },
        ],
    },
    {
        slug: 'emirates-palace-to-abu-dhabi-airport',
        hotelName: 'Emirates Palace Mandarin Oriental',
        airportName: 'Zayed International Airport (AUH)',
        city: 'Abu Dhabi',
        country: 'United Arab Emirates',
        distance: '38 km',
        travelTime: '35–45 minutes',
        description: 'Taxi from Emirates Palace to Abu Dhabi Airport. Professional transfers from central Abu Dhabi to the airport.',
        longDescription: 'Arrange your return transfer from the Emirates Palace Mandarin Oriental to Zayed International Airport (AUH) with our professional taxi service. We provide a reliable and punctual connection from this landmark property directly to the airport departures, ensuring a smooth end to your stay in the UAE capital.',
        pickupProcess: [
            'Driver meets you at the main hotel entrance gate or lobby.',
            'Full assistance with baggage handling and loading.',
            'Punctual transit via the city highways to the airport terminals.',
            'Drop-off at the correct departures entrance for your flight.',
        ],
        travelTips: [
            'Allow at least 45 minutes for the drive to Zayed International Airport.',
            'Confirm your airline and departure terminal (T1 or Terminal A).',
            'Business hours traffic can affect travel time across Abu Dhabi.',
            'Request an executive sedan for the highest standard of travel comfort.',
        ],
        faq: [
            { question: 'How long does the transfer to Abu Dhabi Airport take?', answer: 'The journey usually takes 35 to 45 minutes from Emirates Palace.' },
            { question: 'Can I book a van for a family with many suitcases?', answer: 'Yes, we have large SUVs and vans like the GMC and Vito available.' },
            { question: 'Is the service available for night departures?', answer: 'Yes, we provide 24/7 airport transfers in Abu Dhabi.' },
            { question: 'How do I identify my driver?', answer: 'Your driver will coordinate with the hotel valet or be waiting at the lobby.' },
            { question: 'Can I book a transfer from Sharjah to Abu Dhabi?', answer: 'Yes, we also provide inter-emirate transfers to the airport.' },
        ],
        relatedRoutes: [
            { name: 'Abu Dhabi Airport Taxi', slug: '/airport/abu-dhabi-airport-taxi', type: 'airport' },
            { name: 'Abu Dhabi Taxi Service', slug: '/city/abu-dhabi-taxi', type: 'city' },
            { name: 'Taxi to Saadiyat Island', slug: '/taxi-to-area/abu-dhabi-airport-to-saadiyat-island', type: 'route' },
        ],
    },
    {
        slug: 'four-seasons-doha-to-hamad-airport',
        hotelName: 'Four Seasons Resort Doha',
        airportName: 'Hamad International Airport (DOH)',
        city: 'Doha',
        country: 'Qatar',
        distance: '22 km',
        travelTime: '20–30 minutes',
        description: 'Taxi from Four Seasons Doha to Hamad Airport. Reliable airport transfers from the Corniche area.',
        longDescription: 'Professional transportation from the Four Seasons Resort Doha to Hamad International Airport (DOH). Our service offers a direct and comfortable connection from the heart of the Doha Corniche to the departures level, ensuring a timely arrival for your international flight.',
        pickupProcess: [
            'Driver meets you at the hotel main entrance or porte-cochère.',
            'Full support with luggage loading and vehicle setup.',
            'Direct transit along the Corniche road to the airport.',
            'Drop-off at the departures portal for your airline zone.',
        ],
        travelTips: [
            'Doha Corniche traffic can be heavy in the morning; leave with extra time.',
            'Confirm your airline departure zone with the driver before drop-off.',
            'The drive to Hamad Airport is approximately 20 to 30 minutes.',
            'Ensure your Qatar exit requirements are clarified if needed.',
        ],
        faq: [
            { question: 'How long to reach the airport from Four Seasons Doha?', answer: 'The journey typically takes 20 to 30 minutes.' },
            { question: 'Can I book an SUV for a group of 5?', answer: 'Yes, we have GMC and Cadillac Escalade models for family groups.' },
            { question: 'Is the service available at 3 AM?', answer: 'Yes, we provide 24/7 airport transfers from all Doha hotels.' },
            { question: 'Can I schedule a return pickup from the airport?', answer: 'Yes, airport-to-hotel transfers can also be pre-booked.' },
            { question: 'Does the driver assist with bags at the hotel?', answer: 'Yes, our drivers provide complete assistance with your luggage.' },
        ],
        relatedRoutes: [
            { name: 'Doha Airport Taxi', slug: '/airport/doha-airport-taxi', type: 'airport' },
            { name: 'Doha Taxi Service', slug: '/city/doha-taxi', type: 'city' },
            { name: 'Taxi to Souq Waqif', slug: '/taxi-to-landmark/souq-waqif-doha', type: 'route' },
        ],
    },
    {
        slug: 'sheraton-kuwait-to-kuwait-airport',
        hotelName: 'Sheraton Kuwait',
        airportName: 'Kuwait International Airport (KWI)',
        city: 'Kuwait City',
        country: 'Kuwait',
        distance: '18 km',
        travelTime: '20–25 minutes',
        description: 'Taxi from Sheraton Kuwait to Kuwait Airport. Reliable return transfers from central Kuwait City.',
        longDescription: 'Arrange your return transfer from the Sheraton Kuwait in central Kuwait City to Kuwait International Airport (KWI). Our professional service ensures you reach the airport departures level on time, with a driver meeting you at the hotel lobby to assist with your luggage and provide a comfortable journey.',
        pickupProcess: [
            'Driver meets passengers at the Sheraton lobby main entrance.',
            'Assistance with suitcases and baggage handling.',
            'Direct transportation to Terminal 1, 4, or 5 at the airport.',
            'Drop-off at the arrivals level entrance for your airline.',
        ],
        travelTips: [
            'Confirm whether you are flying from Terminal 1, 4, or 5.',
            'Central Kuwait City traffic can be slow during weekday mornings.',
            'The drive is approximately 20 to 25 minutes; leave 3 hours early.',
            'Carry your passport and ticket for quick airport inspections.',
        ],
        faq: [
            { question: 'How long to reach Kuwait Airport from the Sheraton?', answer: 'The journey typically takes 20 to 25 minutes depending on traffic.' },
            { question: 'Are larger vehicles available for group transfers?', answer: 'Yes, we offer SUVs and passenger vans for families.' },
            { question: 'Is pickup from the hotel lobby standard?', answer: 'Yes, our driver will wait at the main lobby of the Sheraton.' },
            { question: 'Is the service available on weekends?', answer: 'Yes, we operate 24 hours a day throughout the week.' },
            { question: 'How do I book for a specific time?', answer: 'Enter your preferred pickup time when booking online or by WhatsApp.' },
        ],
        relatedRoutes: [
            { name: 'Kuwait Airport Taxi', slug: '/airport/kuwait-airport-taxi', type: 'airport' },
            { name: 'Kuwait City Taxi Service', slug: '/city/kuwait-city-taxi', type: 'city' },
            { name: 'Taxi to Kuwait Towers', slug: '/taxi-to-landmark/kuwait-towers-kuwait-city', type: 'route' },
        ],
    },
];
