export interface LandmarkPage {
    slug: string;
    landmarkName: string;
    landmarkType: 'Tourist Attraction' | 'Cultural Site' | 'Iconic Building' | 'Observation Tower' | 'Historic District' | 'Landmark';
    city: string;
    cityCountry: string;
    locationDetails: string;
    approxTravelTime: string;
    description: string;
    longDescription: string;
    features: string[];
    travelTips: string[];
    faq: { question: string; answer: string }[];
    relatedRoutes: { name: string; slug: string; type: 'city' | 'airport' | 'route' }[];
}

export const landmarkPages: LandmarkPage[] = [
    {
        slug: 'burj-khalifa-dubai',
        landmarkName: 'Burj Khalifa',
        landmarkType: 'Iconic Building',
        city: 'Dubai',
        cityCountry: 'United Arab Emirates',
        locationDetails: 'Downtown Dubai',
        approxTravelTime: '15–30 minutes from most central Dubai areas',
        description: 'Taxi to Burj Khalifa Dubai. Transfers to the world\'s tallest building for observation deck visits, dining, and sightseeing in Downtown Dubai.',
        longDescription: 'The Burj Khalifa is the world\'s tallest building and the most iconic landmark in Dubai. Located in the heart of Downtown Dubai, it features the "At the Top" observation decks, high-standard residences, and the Armani Hotel. Our taxi service provides direct and comfortable transfers from any part of the city, hotels, or the airport to the Burj Khalifa entrance.',
        features: [
            'World\'s tallest building and free-standing structure',
            'Home to "At the Top" observation decks on levels 124, 125, and 148',
            'Located adjacent to the Dubai Mall and Dubai Fountain',
            'Iconic global symbol of modern architecture',
            'Features the atmosphere restaurant and Armani Hotel',
        ],
        travelTips: [
            'Book your observation deck tickets in advance to secure preferred time slots.',
            'The main entrance for visitors is through the Lower Ground level of the Dubai Mall.',
            'Plan your visit during sunset for the most scenic views of the city.',
            'Allow extra travel time during the evening fountain shows when traffic is peak.',
            'Drop-off at the Armani Hotel entrance is separate from the mall entrance.',
        ],
        faq: [
            { question: 'How do I reach the Burj Khalifa by taxi?', answer: 'We offer direct transfers to the Burj Khalifa. Most visitors are dropped at the Dubai Mall entrance for the observation deck access.' },
            { question: 'Can I get a taxi from Dubai Airport to Burj Khalifa?', answer: 'Yes. We provide direct transfers from Dubai International Airport (DXB) and DWC to the landmark.' },
            { question: 'Is pickup available from Dubai Marina hotels?', answer: 'Yes. We collect passengers from all hotels and residences in JBR, Marina, and surrounding areas.' },
            { question: 'Can large groups travel together to the landmark?', answer: 'Yes. We have vans and minibuses available for families and tourist groups.' },
            { question: 'How long is the drive from the Palm Jumeirah?', answer: 'The drive from Palm Jumeirah to Burj Khalifa typically takes 25 to 35 minutes depending on traffic.' },
        ],
        relatedRoutes: [
            { name: 'Dubai Taxi Service', slug: '/city/dubai-taxi', type: 'city' },
            { name: 'Dubai Airport Taxi', slug: '/airport/dubai-airport-taxi', type: 'airport' },
            { name: 'Taxi to Dubai Mall', slug: '/taxi-to-mall/dubai-mall-dubai', type: 'route' },
        ],
    },
    {
        slug: 'sheikh-zayed-grand-mosque-abu-dhabi',
        landmarkName: 'Sheikh Zayed Grand Mosque',
        landmarkType: 'Cultural Site',
        city: 'Abu Dhabi',
        cityCountry: 'United Arab Emirates',
        locationDetails: 'Sheikh Rashid Bin Saeed Street, Abu Dhabi',
        approxTravelTime: '15–35 minutes from most Abu Dhabi areas',
        description: 'Taxi to Sheikh Zayed Grand Mosque Abu Dhabi. Transfers for visitors and worshippers to one of the most iconic cultural sites in the UAE.',
        longDescription: 'The Sheikh Zayed Grand Mosque is a masterpiece of Islamic architecture and one of the most visited landmarks in the UAE. Located in Abu Dhabi, it welcomes visitors of all faiths to experience its stunning white marble domes, floral inlays, and the world\'s largest hand-knotted carpet. Our taxi service provides reliable transportation from anywhere in Abu Dhabi or Dubai to the mosque.',
        features: [
            'One of the largest and most beautiful mosques in the world',
            'Masterpiece of modern Islamic architecture and design',
            'Open to visitors outside of prayer times for cultural tours',
            'Features 82 domes and four 107-meter tall minarets',
            'Major destination for international tourists and spiritual visitors',
        ],
        travelTips: [
            'Visitors must adhere to modest dress codes; shoulders and knees must be covered.',
            'Check the visiting hours as the mosque closes to tourists during prayer times.',
            'Morning visits are generally quieter and better for photography.',
            'Inform your driver whether you are visiting for prayer or as a tourist.',
            'Expect security and dress code checks at the main visitor entrance.',
        ],
        faq: [
            { question: 'How do I reach the Sheikh Zayed Grand Mosque?', answer: 'We provide direct transfers from any location in Abu Dhabi or Dubai to the mosque visitor center.' },
            { question: 'Can I take a taxi from Dubai to the mosque?', answer: 'Yes. We offer intercity transfers from Dubai to the Grand Mosque, taking about 90 minutes.' },
            { question: 'Is airport transfer available to the mosque?', answer: 'Yes. We provide direct transfers from Zayed International Airport to the landmark.' },
            { question: 'Are there vehicles for large tour groups?', answer: 'Yes. We have vans and minibuses available for tourist groups and families.' },
            { question: 'What is the best time to visit the mosque?', answer: 'Weekday mornings are recommended to avoid crowds. The mosque looks stunning at sunset.' },
        ],
        relatedRoutes: [
            { name: 'Abu Dhabi Taxi Service', slug: '/city/abu-dhabi-taxi', type: 'city' },
            { name: 'Abu Dhabi Airport Taxi', slug: '/airport/abu-dhabi-airport-taxi', type: 'airport' },
            { name: 'Taxi to Yas Island', slug: '/taxi-to-destination/yas-island-abu-dhabi', type: 'route' },
        ],
    },
    {
        slug: 'doha-corniche-doha',
        landmarkName: 'Doha Corniche',
        landmarkType: 'Tourist Attraction',
        city: 'Doha',
        cityCountry: 'Qatar',
        locationDetails: 'Waterfront, Doha Bay',
        approxTravelTime: '10–25 minutes from central Doha',
        description: 'Taxi to Doha Corniche. Transfers to Doha\'s iconic waterfront promenade for sightseeing, dhow cruises, and leisure walks.',
        longDescription: 'The Doha Corniche is a seven-kilometer waterfront promenade extending in a horseshoe shape around Doha Bay. It offers stunning views of the city skyline, traditional dhow boats, and the Museum of Islamic Art. Our taxi service provides easy access to various points along the Corniche for sightseeing, dining, and evening leisure.',
        features: [
            'Iconic waterfront promenade with city skyline views',
            'Access to the Museum of Islamic Art and National Museum of Qatar',
            'Major hub for traditional dhow boat tours',
            'Scenic leisure destination for walking and photography',
            'Central location connecting West Bay to the historic city center',
        ],
        travelTips: [
            'The Corniche is seven kilometers long; specify your preferred drop-off point.',
            'Popular areas include the MIA Park, the Pearl Monument, and West Bay Park.',
            'Evenings and weekends are busy; allow for extra travel time.',
            'The Corniche is especially beautiful at sunset and when the skyline is lit up.',
            'Carry water and sun protection if visiting during the daytime.',
        ],
        faq: [
            { question: 'How do I reach the Doha Corniche?', answer: 'We offer direct transfers to any point along the Corniche from anywhere in Doha.' },
            { question: 'Can taxis pick up from West Bay hotels?', answer: 'Yes. We provide quick pickups from all hotels in the West Bay business district.' },
            { question: 'Is airport pickup available for the Corniche?', answer: 'Yes. We offer transfers from Hamad International Airport (DOH) to the waterfront.' },
            { question: 'Can groups travel together for a Corniche walk?', answer: 'Yes. SUVs and vans are available for families and small groups.' },
            { question: 'Where is the best place to be dropped off?', answer: 'The Museum of Islamic Art park or the Pearl Monument are popular drop-off locations.' },
        ],
        relatedRoutes: [
            { name: 'Doha Taxi Service', slug: '/city/doha-taxi', type: 'city' },
            { name: 'Doha Airport Taxi', slug: '/airport/doha-airport-taxi', type: 'airport' },
            { name: 'Taxi to Souq Waqif', slug: '/taxi-to-destination/souq-waqif-doha', type: 'route' },
        ],
    },
    {
        slug: 'kuwait-towers-kuwait-city',
        landmarkName: 'Kuwait Towers',
        landmarkType: 'Landmark',
        city: 'Kuwait City',
        cityCountry: 'Kuwait',
        locationDetails: 'Arabian Gulf Street, Kuwait City',
        approxTravelTime: '10–25 minutes from most Kuwait City areas',
        description: 'Taxi to Kuwait Towers. Transfers to the iconic national symbol of Kuwait for observation deck visits and seaside dining.',
        longDescription: 'Kuwait Towers are a group of three slender towers standing on a promontory overlooking the Arabian Gulf. They are the most recognized national landmark of Kuwait City, featuring a revolving restaurant and a panoramic observation deck. Our taxi service provides reliable transportation to the towers for sightseeing and corporate visits.',
        features: [
            'Most iconic national symbol and landmark of Kuwait',
            'Revolving observation deck with 360-degree city and gulf views',
            'Unique architectural design representing traditional Arab culture',
            'Located along the scenic Arabian Gulf Street corniche',
            'Popular destination for both local residents and international tourists',
        ],
        travelTips: [
            'Check the opening hours for the observation deck and dining venues.',
            'Traffic along Gulf Street can be heavy during weekend evenings.',
            'Observation deck access requires a ticket, which can be purchased on-site.',
            'Combine your visit with a walk along the Gulf Road waterfront.',
            'Evening visits offer the best views of the towers\' illumination.',
        ],
        faq: [
            { question: 'How do I reach Kuwait Towers by taxi?', answer: 'We provide direct door-to-door transfers from any area in Kuwait to the Towers.' },
            { question: 'Can airport transfers be arranged?', answer: 'Yes. We offer direct transfers from Kuwait International Airport to Kuwait Towers.' },
            { question: 'Can a family group travel together?', answer: 'Yes. We have SUVs and vans available for families visiting the landmark.' },
            { question: 'How far is it from the Salmiya district?', answer: 'From Salmiya, it typically takes 15 to 25 minutes by road to reach the towers.' },
            { question: 'Can I book a return pickup from the towers?', answer: 'Yes. You can schedule a return transfer to ensure a driver is ready after your visit.' },
        ],
        relatedRoutes: [
            { name: 'Kuwait City Taxi Service', slug: '/city/kuwait-city-taxi', type: 'city' },
            { name: 'Kuwait Airport Taxi', slug: '/airport/kuwait-airport-taxi', type: 'airport' },
            { name: 'Taxi to Avenues Mall', slug: '/taxi-to-mall/avenues-mall-kuwait-city', type: 'route' },
        ],
    },
    {
        slug: 'al-faisaliah-tower-riyadh',
        landmarkName: 'Al Faisaliah Tower',
        landmarkType: 'Iconic Building',
        city: 'Riyadh',
        cityCountry: 'Saudi Arabia',
        locationDetails: 'Olaya District, Riyadh',
        approxTravelTime: '15–30 minutes from central Riyadh',
        description: 'Taxi to Al Faisaliah Tower Riyadh. Transfers to Riyadh\'s iconic skyscraper for observation, dining, and business in the Olaya district.',
        longDescription: 'Al Faisaliah Tower is one of Riyadh\'s most iconic skyscrapers, known for its distinctive pyramid shape and the golden globe near its apex. Located in the bustling Olaya district, it houses executive offices, high-end dining, and an observation deck offering panoramic views of the capital. Our taxi service provides professional transfers to the tower for any purpose.',
        features: [
            'Iconic Riyadh skyscraper with distinctive architectural design',
            'The Globe observation deck with panoramic city views',
            'Located in the heart of the Olaya business and retail district',
            'Home to high-standard restaurants and executive office suites',
            'Part of a larger complex including a mall and high-standard hotel',
        ],
        travelTips: [
            'The tower is located in Olaya; allow for city center traffic during peak hours.',
            'Confirm whether your visit is for the mall, the offices, or the observation deck.',
            'The "Globe Experience" observation deck requires an entrance fee.',
            'Evening visits are popular for dinner with a view of the city skyline.',
            'Inform your driver whether you need the hotel lobby or the main tower entrance.',
        ],
        faq: [
            { question: 'How do I reach Al Faisaliah Tower by taxi?', answer: 'We offer direct transfers from anywhere in Riyadh. Simply book your preferred vehicle online.' },
            { question: 'Is airport pickup available to the tower?', answer: 'Yes. We provide direct transfers from King Khalid International Airport (RUH) to the tower.' },
            { question: 'Are there vehicles for business groups?', answer: 'Yes. Executive SUVs and vans are available for corporate delegations.' },
            { question: 'Can I arrange a return pickup after my visit?', answer: 'Yes. Return transfers can be scheduled in advance for a seamless departure.' },
            { question: 'How long is the drive from KAFD?', answer: 'From King Abdullah Financial District, the journey takes approximately 20 minutes.' },
        ],
        relatedRoutes: [
            { name: 'Riyadh Taxi Service', slug: '/city/riyadh-taxi', type: 'city' },
            { name: 'Riyadh Airport Taxi', slug: '/airport/riyadh-airport-taxi', type: 'airport' },
            { name: 'Taxi to KAFD', slug: '/taxi-to-business/king-abdullah-financial-district-riyadh', type: 'route' },
        ],
    },
    {
        slug: 'kingdom-centre-riyadh',
        landmarkName: 'Kingdom Centre',
        landmarkType: 'Iconic Building',
        city: 'Riyadh',
        cityCountry: 'Saudi Arabia',
        locationDetails: 'Olaya District, Riyadh',
        approxTravelTime: '15–30 minutes from central Riyadh areas',
        description: 'Taxi to Kingdom Centre Riyadh. Transfers to the iconic tower for Sky Bridge visits, high-end shopping, and sightseeing in Olaya.',
        longDescription: 'Kingdom Centre is a landmark 99-story skyscraper in Riyadh, famous for its inverted arch and the Sky Bridge observation deck. It is a leading destination for high-end shopping, fine dining, and offers one of the best views of the Riyadh skyline. Our taxi service provides comfortable and reliable transfers to the Kingdom Centre from anywhere in the city.',
        features: [
            '99-story iconic skyscraper with a unique sky bridge',
            'Sky Bridge offers breathtaking 360-degree views of Riyadh',
            'Home to a high-end shopping mall and the Four Seasons Hotel',
            'Major symbol of Riyadh\'s modern urban development',
            'Prime location in the heart of the Olaya commercial district',
        ],
        travelTips: [
            'The Sky Bridge visit is a must; check the operating hours before arriving.',
            'Park access at Kingdom Centre can be busy; a taxi drop-off is much faster.',
            'Allow extra time for travel during the evening hours on weekends.',
            'Specify whether you are visiting the Sky Bridge or the Four Seasons Hotel.',
            'Photography from the Sky Bridge is allowed and highly recommended.',
        ],
        faq: [
            { question: 'How do I reach the Kingdom Centre?', answer: 'We offer direct door-to-door transfers from any hotel or residence in Riyadh.' },
            { question: 'Is airport transfer available to the tower?', answer: 'Yes. We provide transfers from King Khalid International Airport directly to the tower.' },
            { question: 'Can a family group visit the Sky Bridge together?', answer: 'Yes. We have large SUVs and vans suitable for family sightseeing.' },
            { question: 'How long does it take from northern Riyadh?', answer: 'The journey typically takes 20 to 30 minutes depending on traffic conditions.' },
            { question: 'Can I book a return pickup after shopping?', answer: 'Yes. Return transfers can be scheduled to suit your departure time.' },
        ],
        relatedRoutes: [
            { name: 'Riyadh Taxi Service', slug: '/city/riyadh-taxi', type: 'city' },
            { name: 'Riyadh Airport Taxi', slug: '/airport/riyadh-airport-taxi', type: 'airport' },
            { name: 'Taxi to Riyadh Season', slug: '/taxi-to-event/riyadh-season-riyadh', type: 'route' },
        ],
    },
    {
        slug: 'muscat-old-town-muscat',
        landmarkName: 'Muscat Old Town',
        landmarkType: 'Historic District',
        city: 'Muscat',
        cityCountry: 'Oman',
        locationDetails: 'Muttrah and Old Muscat area',
        approxTravelTime: '15–35 minutes from most Muscat areas',
        description: 'Taxi to Muscat Old Town. Transfers to the historic core of Muscat for visits to the Muttrah Souq, Corniche, and royal palaces.',
        longDescription: 'Muscat Old Town includes the historic districts of Muttrah and the original Old Muscat area. It is the cultural heart of the city, featuring the famous Muttrah Souq, the scenic Corniche, and the Al Alam Palace. Our taxi service provides reliable transportation for tourists and cultural visitors seeking to explore Oman\'s history.',
        features: [
            'Historic heart of Muscat including Muttrah and the original city',
            'Traditional Muttrah Souq — one of the oldest in the region',
            'Scenic Muttrah Corniche with views of the harbor and mountains',
            'Al Alam Palace and historic Portuguese forts Mirani and Jalali',
            'Rich cultural atmosphere with traditional Omani architecture',
        ],
        travelTips: [
            'The Souq is best visited in the early morning or late afternoon.',
            'Dress modestly in accordance with Omani cultural values.',
            'Muttrah and Old Muscat are slightly apart; confirm which area you need.',
            'The Corniche is best explored on foot after being dropped off by taxi.',
            'Check for cruise ship schedules as the area is busiest when ships are in port.',
        ],
        faq: [
            { question: 'How do I reach the Muttrah Souq area?', answer: 'We provide direct transfers from any hotel in Muscat to the Souq entrance.' },
            { question: 'Is airport transfer available to Old Muscat?', answer: 'Yes. We offer transfers from Muscat International Airport to all historic sites.' },
            { question: 'Are there vehicles for tourist groups?', answer: 'Yes. We have vans and minibuses available for larger groups and families.' },
            { question: 'How long from the Al Khuwair district?', answer: 'The journey from Al Khuwair typically takes 15 to 25 minutes.' },
            { question: 'Can I book a return transfer from the Corniche?', answer: 'Yes. Scheduled return pickups ensure you have a ride ready after your walk.' },
        ],
        relatedRoutes: [
            { name: 'Muscat Taxi Service', slug: '/city/muscat-taxi', type: 'city' },
            { name: 'Muscat Airport Taxi', slug: '/airport/muscat-airport-taxi', type: 'airport' },
            { name: 'Taxi to Mall of Muscat', slug: '/taxi-to-mall/mall-of-muscat-muscat', type: 'route' },
        ],
    },
    {
        slug: 'souq-waqif-doha',
        landmarkName: 'Souq Waqif',
        landmarkType: 'Cultural Site',
        city: 'Doha',
        cityCountry: 'Qatar',
        locationDetails: 'B-Ring Road, Doha City Center',
        approxTravelTime: '10–25 minutes from central Doha',
        description: 'Taxi to Souq Waqif Doha. Transfers to Qatar\'s traditional market for shopping, dining, and cultural heritage experiences.',
        longDescription: 'Souq Waqif is the historic heart of Doha and its most famous traditional market. It is a hub for traditional Omani and Qatari culture, featuring spice shops, textile vendors, art galleries, and diverse dining options. Our taxi service provides direct and convenient transfers to the Souq for sightseeing and evening leisure.',
        features: [
            'Centuries-old traditional market restored to its original beauty',
            'Hub for traditional handicrafts, spices, and Qatari clothing',
            'Diverse selection of Middle Eastern and international restaurants',
            'Home to the Falcon Hospital and the Horse Stables',
            'Regular venue for cultural festivals and night markets',
        ],
        travelTips: [
            'The Souq is best enjoyed in the late afternoon and evening when it is most active.',
            'Many shops close during the early afternoon peak heat; visit after 4 PM.',
            'Dress modestly when visiting this traditional heritage location.',
            'Drop-off near the Falcon Hospital or the Al Shoumoukh tower is recommended.',
            'Explore the smaller alleyways for the most authentic experience.',
        ],
        faq: [
            { question: 'How do I reach Souq Waqif by taxi?', answer: 'We offer direct door-to-door transfers from anywhere in Doha to the Souq.' },
            { question: 'Is pickup available from West Bay hotels?', answer: 'Yes. We provide quick transfers for business guests staying in West Bay.' },
            { question: 'Can airport transfers be arranged to the Souq?', answer: 'Yes. We provide direct transfers from Hamad International Airport (DOH).' },
            { question: 'Are there vehicles for large tourist families?', answer: 'Yes. We have large SUVs and vans available for group visits.' },
            { question: 'Can I book a return pickup after dinner?', answer: 'Yes. Pre-booked return transfers can be scheduled for your convenience.' },
        ],
        relatedRoutes: [
            { name: 'Doha Taxi Service', slug: '/city/doha-taxi', type: 'city' },
            { name: 'Doha Airport Taxi', slug: '/airport/doha-airport-taxi', type: 'airport' },
            { name: 'Taxi to Doha Corniche', slug: '/taxi-to-landmark/doha-corniche-doha', type: 'route' },
        ],
    },
];
