export interface MallPage {
    slug: string;
    mallName: string;
    city: string;
    cityCountry: string;
    district: string;
    approxTravelTime: string;
    description: string;
    longDescription: string;
    features: string[];
    travelTips: string[];
    faq: { question: string; answer: string }[];
    relatedRoutes: { name: string; slug: string; type: 'city' | 'airport' | 'route' }[];
}

export const mallPages: MallPage[] = [
    {
        slug: 'dubai-mall-dubai',
        mallName: 'Dubai Mall',
        city: 'Dubai',
        cityCountry: 'United Arab Emirates',
        district: 'Downtown Dubai',
        approxTravelTime: '15–30 minutes from most central areas',
        description: 'Taxi to Dubai Mall. Reliable transportation for shopping, dining, and visiting the Burj Khalifa in Downtown Dubai.',
        longDescription: 'Dubai Mall is a major retail and entertainment destination located in Downtown Dubai, adjacent to the Burj Khalifa. It is home to hundreds of international brands, the Dubai Aquarium, and an Olympic-sized ice rink. Our taxi service provides easy access to all major mall entrances from your hotel, residence, or the airport.',
        features: [
            'Hundreds of international retail stores',
            'Dubai Aquarium and Underwater Zoo',
            'Proximity to Burj Khalifa and Dubai Fountain',
            'Olympic-sized Dubai Ice Rink',
            'Large food court and themed dining areas',
        ],
        travelTips: [
            'Visit during weekday mornings for a quieter shopping experience.',
            'Confirm which mall entrance is closest to your target store.',
            'Allow extra time for traffic in the Downtown area, especially during fountain shows.',
            'Check for seasonal sales and event schedules before your visit.',
            'The mall is very large; wear comfortable walking shoes.',
        ],
        faq: [
            { question: 'How do I get to Dubai Mall by taxi?', answer: 'We offer direct door-to-door transfers from anywhere in Dubai. Simply book online or call us.' },
            { question: 'Can I get a taxi from Dubai Airport to the mall?', answer: 'Yes. We provide direct transfers from Dubai International Airport (DXB) to all Dubai Mall entrances.' },
            { question: 'Which entrance is best for the Burj Khalifa?', answer: 'The Fashion Avenue or Lower Ground entrances provide the most direct access to the Burj Khalifa ticket office.' },
            { question: 'Are there group vehicles available for families?', answer: 'Yes. We have SUVs and vans like the GMC and Mercedes Vito for groups.' },
            { question: 'Can I arrange a return pickup from the mall?', answer: 'Yes. You can schedule a pickup at a specific time or contact us when you are ready to leave.' },
        ],
        relatedRoutes: [
            { name: 'Dubai Taxi Service', slug: '/city/dubai-taxi', type: 'city' },
            { name: 'Dubai Airport Taxi', slug: '/airport/dubai-airport-taxi', type: 'airport' },
            { name: 'Dubai to Burj Al Arab', slug: '/taxi-to-destination/burj-al-arab-dubai', type: 'route' },
        ],
    },
    {
        slug: 'mall-of-qatar-doha',
        mallName: 'Mall of Qatar',
        city: 'Doha',
        cityCountry: 'Qatar',
        district: 'Al Rayyan',
        approxTravelTime: '20–40 minutes from central Doha',
        description: 'Taxi to Mall of Qatar in Al Rayyan. Direct transfers for shopping, cinema, and family entertainment in Doha.',
        longDescription: 'The Mall of Qatar is a major shopping and entertainment complex located in the Al Rayyan area of Doha. It features a wide array of retail brands, a massive food court, and the Oasis entertainment zone. Our service provides organized transfers from all Doha neighborhoods and the airport directly to the mall.',
        features: [
            'The Oasis - central stage for live performances',
            'Wide variety of high-end and high-street brands',
            'Large Novo Cinemas complex',
            'Family entertainment centers and kids\' play areas',
            'Directly connected to the Al Rayyan stadium area',
        ],
        travelTips: [
            'The mall is located slightly outside central Doha; plan for a 30-minute drive.',
            'Check the performance schedule at The Oasis for free live shows.',
            'The mall is less crowded on weekday mornings.',
            'Be aware of the different parking zones and valet points.',
            'Ensure you have your mall entrance number for your return pickup.',
        ],
        faq: [
            { question: 'How do I get to Mall of Qatar by taxi?', answer: 'We provide transfers from any location in Doha. Our drivers know the Al Rayyan area well.' },
            { question: 'Is it possible to get a taxi from Hamad Airport?', answer: 'Yes. We offer direct airport transfers to the Mall of Qatar.' },
            { question: 'Can groups travel together in one vehicle?', answer: 'Yes. We have vans and larger SUVs available for family or group shopping trips.' },
            { question: 'How long is the drive from West Bay?', answer: 'Depending on traffic, the drive from West Bay to Mall of Qatar takes about 25 to 35 minutes.' },
            { question: 'Is the mall accessible for those with limited mobility?', answer: 'Yes. Our vehicles can accommodate mobility aids, and the mall itself is fully accessible.' },
        ],
        relatedRoutes: [
            { name: 'Doha Taxi Service', slug: '/city/doha-taxi', type: 'city' },
            { name: 'Doha Airport Taxi', slug: '/airport/doha-airport-taxi', type: 'airport' },
            { name: 'Doha to Lusail Stadium', slug: '/taxi-to-event/lusail-stadium-doha', type: 'route' },
        ],
    },
    {
        slug: 'avenues-mall-kuwait-city',
        mallName: 'The Avenues Mall',
        city: 'Kuwait City',
        cityCountry: 'Kuwait',
        district: 'Al Rai',
        approxTravelTime: '15–30 minutes from central areas',
        description: 'Taxi to The Avenues Mall in Kuwait City. Reliable transportation for shopping at Kuwait\'s largest retail destination.',
        longDescription: 'The Avenues Mall is the largest shopping mall in Kuwait and one of the largest in the region. Located in the Al Rai area, it offers a unique shopping experience with themed districts like Grand Avenue and the Prestige. Our taxi service ensures you reach any of its many gates comfortably and on time.',
        features: [
            'Themed districts including Grand Avenue and Souk',
            'Prestige district for high-end brands',
            'Vast selection of international restaurants and cafes',
            'Cinema complexes and entertainment zones',
            'Modern and traditional architectural blend',
        ],
        travelTips: [
            'The Avenues is exceptionally large; identify your target district before drop-off.',
            'Allow extra time for traffic around the Al Rai area during weekends.',
            'Inform your driver which Gate number you prefer for drop-off.',
            'Weekdays are much quieter than the very busy weekend evenings.',
            'Check for parking availability if you are meeting someone with a car.',
        ],
        faq: [
            { question: 'How do I arrange a taxi to The Avenues?', answer: 'You can book through our website or contact us directly. We serve all areas of Kuwait.' },
            { question: 'Can taxis pick up from hotels in Kuwait City?', answer: 'Yes. We pick up from all major hotels and residential complexes.' },
            { question: 'Is airport pickup available for visitors?', answer: 'Yes. We provide direct transfers from Kuwait International Airport to The Avenues.' },
            { question: 'Which gate should I choose for the cinemas?', answer: 'Gate 4 or Gate 7 are typically closest to the main cinema areas.' },
            { question: 'Are larger vehicles available for group shopping?', answer: 'Yes. We offer GMC and Mercedes vans for larger groups.' },
        ],
        relatedRoutes: [
            { name: 'Kuwait City Taxi Service', slug: '/city/kuwait-city-taxi', type: 'city' },
            { name: 'Kuwait Airport Taxi', slug: '/airport/kuwait-airport-taxi', type: 'airport' },
            { name: 'Kuwait to Al Sabah Hospital', slug: '/taxi-to-hospital/al-sabah-hospital-kuwait', type: 'route' },
        ],
    },
    {
        slug: 'red-sea-mall-jeddah',
        mallName: 'Red Sea Mall',
        city: 'Jeddah',
        cityCountry: 'Saudi Arabia',
        district: 'Northern Corniche',
        approxTravelTime: '10–25 minutes from the Corniche area',
        description: 'Taxi to Red Sea Mall in Jeddah. Direct transportation for shopping, dining, and cinema at Jeddah\'s major North Corniche destination.',
        longDescription: 'Red Sea Mall is a major shopping and entertainment hub located on Jeddah\'s Northern Corniche. It is one of the largest malls in the city, featuring a blend of international brands, local retailers, and a large cinema. Our taxi service provides reliable transfers to the mall from all parts of Jeddah and the airport.',
        features: [
            'Prime location on the Northern Corniche',
            'Mix of international and local retail brands',
            'Large food court and specialized restaurants',
            'VOX Cinemas and children\'s entertainment zones',
            'Adjacent to the Jeddah Corniche Circuit area',
        ],
        travelTips: [
            'The mall can be very busy on Thursday and Friday evenings.',
            'Allow extra travel time if there is an event at the Jeddah Corniche Circuit.',
            'Confirm your preferred gate (North or South) with your driver.',
            'Morning visits are ideal for a more relaxed shopping experience.',
            'Check for seasonal events often held in the mall atrium.',
        ],
        faq: [
            { question: 'How do I get to Red Sea Mall by taxi?', answer: 'We offer door-to-door service from anywhere in Jeddah. Just book your time and location.' },
            { question: 'Can I get a taxi from Jeddah Airport to the mall?', answer: 'Yes. We provide direct transfers from King Abdulaziz International Airport (JED) to Red Sea Mall.' },
            { question: 'Is the mall near the Jeddah Corniche?', answer: 'Yes, it is located right on the Northern Corniche, making it very accessible.' },
            { question: 'Are there vehicles for large families?', answer: 'Yes. We have SUVs and vans for families and groups.' },
            { question: 'Can I book a return trip in advance?', answer: 'Yes. Pre-booking your return ensures a driver is waiting when you finish shopping.' },
        ],
        relatedRoutes: [
            { name: 'Jeddah Airport Taxi', slug: '/airport/jeddah-airport-taxi', type: 'airport' },
            { name: 'Jeddah to Makkah Taxi', slug: '/routes/jeddah-to-makkah-taxi', type: 'route' },
            { name: 'Riyadh to Jeddah Taxi', slug: '/routes/riyadh-to-jeddah-taxi', type: 'route' },
        ],
    },
    {
        slug: 'city-centre-bahrain-manama',
        mallName: 'City Centre Bahrain',
        city: 'Manama',
        cityCountry: 'Bahrain',
        district: 'Seef District',
        approxTravelTime: '10–20 minutes from central Manama',
        description: 'Taxi to City Centre Bahrain in Manama. Comfortable transfers for shopping, Wahooo! Waterpark, and dining in the Seef District.',
        longDescription: 'City Centre Bahrain is the largest shopping, entertainment, and leisure destination in Bahrain, located in the Seef District of Manama. It features hundreds of stores, a large cinema complex, and the Wahooo! Waterpark. Our taxi service offers easy, direct transfers to the mall from your home, hotel, or the airport.',
        features: [
            'Wahooo! Indoor-Outdoor Waterpark',
            'Largest cinema complex in Bahrain',
            'Hundreds of international retail and fashion brands',
            'Diverse selection of cafes and restaurants',
            'Located in the heart of the Seef business district',
        ],
        travelTips: [
            'The Seef district can have heavy traffic during evening hours; plan accordingly.',
            'If visiting the waterpark, allow extra time for entry and lockers.',
            'The mall has multiple entrances; specify your preferred drop-off point.',
            'Weekends attract many visitors from neighboring countries; mornings are quieter.',
            'Check the mall website for current promotions and event schedules.',
        ],
        faq: [
            { question: 'How do I get to City Centre Bahrain by taxi?', answer: 'We provide door-to-door transfers from all areas of Bahrain and from the Saudi border.' },
            { question: 'Is it possible to get a taxi from Bahrain Airport?', answer: 'Yes. We offer direct transfers from Bahrain International Airport (BAH) to the mall.' },
            { question: 'How far is the mall from the King Fahd Causeway?', answer: 'The drive from the Saudi border/causeway to City Centre Bahrain takes about 20 to 30 minutes.' },
            { question: 'Are group vehicles available for visitors?', answer: 'Yes. We have SUVs and vans for groups of shoppers or families.' },
            { question: 'Can I arrange a pickup from my hotel in Manama?', answer: 'Yes. We pick up from all hotels and serviced apartments in the Manama area.' },
        ],
        relatedRoutes: [
            { name: 'Bahrain to Saudi Arabia Taxi', slug: '/routes/bahrain-to-saudi-arabia-taxi', type: 'route' },
            { name: 'Riyadh to Bahrain Taxi', slug: '/routes/riyadh-to-bahrain-taxi', type: 'route' },
            { name: 'Dubai Taxi Service', slug: '/city/dubai-taxi', type: 'city' },
        ],
    },
    {
        slug: 'mall-of-muscat-muscat',
        mallName: 'Mall of Muscat',
        city: 'Muscat',
        cityCountry: 'Oman',
        district: 'Mabela',
        approxTravelTime: '20–40 minutes from Muscat city center',
        description: 'Taxi to Mall of Muscat in Mabela. Professional transportation for the Oman Aquarium, shopping, and entertainment in Muscat.',
        longDescription: 'Mall of Muscat is a major retail and leisure destination located in the Mabela area of Muscat. It is home to the Oman Aquarium, the largest aquarium in the Middle East, as well as a wide range of international stores and a lifestyle center. Our taxi service provides reliable transport from all Muscat neighborhoods and the airport.',
        features: [
            'Oman Aquarium - largest aquarium in the Middle East',
            'Lifestyle center with numerous retail brands',
            'Major dining and cafe outlets',
            'Novo Cinemas and family entertainment zones',
            'Located in the rapidly developing Mabela area',
        ],
        travelTips: [
            'The mall is located south of the main city center; allow for appropriate drive time.',
            'Plan your visit to the Oman Aquarium in advance for ticket availability.',
            'The Mabela area is growing fast; check for any current road diversions.',
            'The mall is a popular destination for families on Friday afternoons.',
            'Note your entrance gate for a smooth return pickup by your driver.',
        ],
        faq: [
            { question: 'How do I get to Mall of Muscat by taxi?', answer: 'We offer direct transfers from anywhere in Muscat. Simply book your ride online.' },
            { question: 'Can I get a taxi from Muscat Airport to the mall?', answer: 'Yes. We provide direct transfers from Muscat International Airport (MCT) to the mall.' },
            { question: 'How long is the drive from Qurum to Mall of Muscat?', answer: 'From the Qurum area, the drive typically takes 25 to 35 minutes.' },
            { question: 'Are family vehicles available for aquarium visits?', answer: 'Yes. We have SUVs and vans for families visiting the aquarium and mall.' },
            { question: 'Can I book a return transfer for a specific time?', answer: 'Yes. You can pre-book your return trip to ensure your driver is on-site when you finish.' },
        ],
        relatedRoutes: [
            { name: 'Muscat Airport Taxi', slug: '/airport/muscat-airport-taxi', type: 'airport' },
            { name: 'Muscat to Dubai Taxi', slug: '/routes/muscat-to-dubai-taxi', type: 'route' },
            { name: 'Dubai Taxi Service', slug: '/city/dubai-taxi', type: 'city' },
        ],
    },
    {
        slug: 'riyadh-park-riyadh',
        mallName: 'Riyadh Park',
        city: 'Riyadh',
        cityCountry: 'Saudi Arabia',
        district: 'Northern Ring Road',
        approxTravelTime: '20–40 minutes from central Riyadh',
        description: 'Taxi to Riyadh Park Mall. Direct transfers for shopping, dining, and family entertainment on Riyadh\'s Northern Ring Road.',
        longDescription: 'Riyadh Park is a major shopping and lifestyle destination located on the Northern Ring Road of Riyadh. It features a wide array of international retail brands, a large VOX Cinemas, and a variety of high-end and casual dining options. Our taxi service provides easy access to the mall from all over Riyadh and the airport.',
        features: [
            'Prime location on the Northern Ring Road',
            'VOX Cinemas and family entertainment zones',
            'Variety of international fashion and retail brands',
            'Extensive outdoor and indoor dining areas',
            'Modern and spacious mall design',
        ],
        travelTips: [
            'The Northern Ring Road can be very busy during peak hours; allow extra time.',
            'Identify which gate or entrance is closest to your target store or restaurant.',
            'Weekends (Friday and Saturday) are the busiest times at Riyadh Park.',
            'Drop-off at the main entrance is generally more efficient than finding parking.',
            'Check for seasonal sales and mall-wide events.',
        ],
        faq: [
            { question: 'How do I get to Riyadh Park by taxi?', answer: 'We provide direct door-to-door transfers from any location in Riyadh to the mall.' },
            { question: 'Can I get a taxi from Riyadh Airport to the mall?', answer: 'Yes. We offer direct transfers from King Khalid International Airport (RUH) to Riyadh Park.' },
            { question: 'Is the mall near the King Abdullah Financial District?', answer: 'Yes, Riyadh Park is located quite close to the KAFD area.' },
            { question: 'Are group vehicles available for families?', answer: 'Yes. We have SUVs and vans for families and groups traveling together.' },
            { question: 'Can I book a return pickup in advance?', answer: 'Yes. Pre-booking your return transfer ensures prompt service when you are ready.' },
        ],
        relatedRoutes: [
            { name: 'Riyadh Taxi Service', slug: '/city/riyadh-taxi', type: 'city' },
            { name: 'Riyadh Airport Taxi', slug: '/airport/riyadh-airport-taxi', type: 'airport' },
            { name: 'Riyadh to Dammam Taxi', slug: '/routes/riyadh-to-dammam-taxi', type: 'route' },
        ],
    },
];
