export interface PortPage {
    slug: string;
    portName: string;
    portType: 'Cruise Terminal' | 'Seaport' | 'Ferry Terminal' | 'International Maritime Hub';
    city: string;
    cityCountry: string;
    locationDetails: string;
    approxTravelTime: string;
    description: string;
    longDescription: string;
    features: string[];
    travelTips: string[];
    faq: { question: string; answer: string }[];
    relatedRoutes: { name: string; slug: string; type: 'city' | 'airport' | 'route' }[];
}

export const portPages: PortPage[] = [
    {
        slug: 'dubai-cruise-terminal-dubai',
        portName: 'Dubai Cruise Terminal',
        portType: 'Cruise Terminal',
        city: 'Dubai',
        cityCountry: 'United Arab Emirates',
        locationDetails: 'Mina Rashid (Port Rashid), Dubai',
        approxTravelTime: '20–40 minutes from Downtown Dubai and DXB Airport',
        description: 'Taxi to Dubai Cruise Terminal at Mina Rashid. Reliable transfers for cruise passengers arriving or departing from Dubai\'s historic port.',
        longDescription: 'The Dubai Cruise Terminal at Mina Rashid is the primary international cruise hub in the Middle East. It hosts major cruise lines and provides award-winning facilities for passengers embarking on regional or international voyages. Our taxi service offers direct transportation from Dubai International Airport, city hotels, and residential areas to the specific cruise terminal gates.',
        features: [
            'International maritime hub for major cruise lines',
            'Equipped with modern facilities and passenger lounges',
            'Located at the historic Mina Rashid near Dubai city center',
            'Primary departure point for seasonal Gulf cruises',
            'Multiple berths capable of handling several large cruise ships simultaneously',
        ],
        travelTips: [
            'Arrive at least 3-4 hours before your cruise departure time for check-in.',
            'Confirm the specific terminal number (Terminal 2 or 3) with your cruise line.',
            'Allow extra time for security checks and luggage handling at the port entrance.',
            'Keep your cruise booking and passport ready for presentation at the port security gate.',
            'Plan for heavy traffic near the port during peak embarkation and disembarkation hours.',
        ],
        faq: [
            { question: 'How do I get to the Dubai Cruise Terminal?', answer: 'We provide direct door-to-door transfers to Mina Rashid from any location in Dubai or the UAE.' },
            { question: 'Can taxis pick up from Dubai Airport?', answer: 'Yes. We offer direct transfers from Dubai International (DXB) and Al Maktoum (DWC) airports to the terminal.' },
            { question: 'Can large groups travel together to the port?', answer: 'Yes. We have vans and minibuses available for families and groups traveling with large quantities of luggage.' },
            { question: 'Do you offer transfers from Abu Dhabi to the Dubai port?', answer: 'Yes. We provide intercity taxi services from Abu Dhabi directly to Mina Rashid Dubai.' },
            { question: 'Is help with luggage provided?', answer: 'Our drivers will assist with loading and unloading your luggage into the vehicle.' },
        ],
        relatedRoutes: [
            { name: 'Dubai Taxi Service', slug: '/city/dubai-taxi', type: 'city' },
            { name: 'Dubai Airport Taxi', slug: '/airport/dubai-airport-taxi', type: 'airport' },
            { name: 'Dubai to Abu Dhabi Taxi', slug: '/routes/dubai-to-abu-dhabi-taxi', type: 'route' },
        ],
    },
    {
        slug: 'doha-cruise-port-doha',
        portName: 'Doha Cruise Port',
        portType: 'Cruise Terminal',
        city: 'Doha',
        cityCountry: 'Qatar',
        locationDetails: 'Grand Cruise Terminal, Doha Old Port',
        approxTravelTime: '15–30 minutes from central Doha and Hamad Airport',
        description: 'Taxi to Doha Cruise Port. Transfers to the Grand Cruise Terminal at Old Doha Port for cruise departures and arrivals.',
        longDescription: 'The Doha Cruise Port, located within the historic Old Doha Port district, features the stunning Grand Cruise Terminal. It serves as a major gateway for cruise tourism in Qatar, located conveniently near the Museum of Islamic Art and the Corniche. Our taxi service ensures punctual arrivals for passengers heading to their cruise ships or departing for the airport.',
        features: [
            'Newly developed Grand Cruise Terminal with traditional Arab architecture',
            'Located in the scenic Old Doha Port district',
            'Close proximity to Doha’s main tourist attractions like Souq Waqif',
            'State-of-the-art facilities for international cruise travelers',
            'International maritime hub for major regional cruise circuits',
        ],
        travelTips: [
            'Check your cruise itinerary to confirm the check-in window at the terminal.',
            'Old Doha Port has specific entry points; your driver will drop you at the passenger terminal.',
            'Allow time for security and customs procedures if you are starting your cruise specifically in Doha.',
            'Carry your valid QID or passport as required for port entry.',
            'Return transfers to Hamad International Airport can be pre-booked for your disembarkation day.',
        ],
        faq: [
            { question: 'How do I get to the Doha Cruise Terminal?', answer: 'We offer direct transfers from any Doha hotel or residence to the Grand Cruise Terminal.' },
            { question: 'Can I book a taxi from Hamad Airport to the port?', answer: 'Yes. We provide dedicated transfers from Hamad International Airport directly to the cruise terminal.' },
            { question: 'Are vehicles available for families with cruise luggage?', answer: 'Yes. We offer large SUVs and vans suitable for groups with multiple suitcases.' },
            { question: 'How far is the port from West Bay?', answer: 'The cruise port is approximately 10 to 15 minutes away from the West Bay business district.' },
            { question: 'Can I arrange a return pickup from the port?', answer: 'Yes. You can schedule a return transfer to ensure a vehicle is waiting upon your return to Doha.' },
        ],
        relatedRoutes: [
            { name: 'Doha Taxi Service', slug: '/city/doha-taxi', type: 'city' },
            { name: 'Doha Airport Taxi', slug: '/airport/doha-airport-taxi', type: 'airport' },
            { name: 'Taxi to Souq Waqif', slug: '/taxi-to-landmark/souq-waqif-doha', type: 'route' },
        ],
    },
    {
        slug: 'jeddah-islamic-port-jeddah',
        portName: 'Jeddah Islamic Port',
        portType: 'Seaport',
        city: 'Jeddah',
        cityCountry: 'Saudi Arabia',
        locationDetails: 'Al-Baghdadiyah Al-Gharbiyah, Jeddah',
        approxTravelTime: '20–40 minutes from central Jeddah and hotel areas',
        description: 'Taxi to Jeddah Islamic Port. Transportation for travelers and professionals visiting the historic seaport and international terminal in Jeddah.',
        longDescription: 'Jeddah Islamic Port is the largest and most important port in Saudi Arabia and one of the oldest on the Red Sea. It handles a significant portion of the Kingdom\'s maritime trade and also hosts international ferry terminals. Our taxi service provides reliable transportation for business visitors, maritime professionals, and travelers arriving by sea.',
        features: [
            'Largest seaport in Saudi Arabia on the Red Sea coast',
            'International maritime hub for trade and passenger services',
            'Hosts ferry terminals for regional travel across the Red Sea',
            'Modern terminal facilities for cargo and passenger processing',
            'Strategic location connecting the West to the Far East',
        ],
        travelTips: [
            'Ensure you have all necessary port entry permits or business invitations ready.',
            'Allow additional time for security gate clearance when entering the port facility.',
            'Confirm which specific terminal or gate you need to visit within the vast port area.',
            'Traffic around the port area can be heavy during peak commercial hours.',
            'Carry your passport or national ID for presentation at port security checkpoints.',
        ],
        faq: [
            { question: 'How do I get to Jeddah Islamic Port?', answer: 'We provide direct taxi transfers from any location in Jeddah to the port entrance and terminals.' },
            { question: 'Is airport transfer available to the port?', answer: 'Yes. We offer transfers from King Abdulaziz International Airport (JED) to Jeddah Islamic Port.' },
            { question: 'Can I book a taxi for business visits to the port?', answer: 'Yes. We provide professional chauffeur services for corporate and business visitors to the port.' },
            { question: 'Are there vehicles for large groups?', answer: 'Yes. SUVs and vans are available for larger parties or crews traveling together.' },
            { question: 'Can I arrange a pickup from the port to a hotel?', answer: 'Yes. We can meet you at the designated passenger exit points at the port for hotel transfers.' },
        ],
        relatedRoutes: [
            { name: 'Jeddah Taxi Service', slug: '/city/jeddah-taxi', type: 'city' },
            { name: 'Jeddah Airport Taxi', slug: '/airport/jeddah-airport-taxi', type: 'airport' },
            { name: 'Makkah to Jeddah Taxi', slug: '/routes/makkah-to-jeddah-taxi', type: 'route' },
        ],
    },
    {
        slug: 'kuwait-shuwaikh-port-kuwait-city',
        portName: 'Shuwaikh Port',
        portType: 'Seaport',
        city: 'Kuwait City',
        cityCountry: 'Kuwait',
        locationDetails: 'Shuwaikh Industrial Area, Kuwait City',
        approxTravelTime: '15–30 minutes from Kuwait City center',
        description: 'Taxi to Shuwaikh Port in Kuwait City. Reliable transportation for maritime professionals and business visitors to Kuwait\'s primary commercial port.',
        longDescription: 'Shuwaikh Port is the main commercial port in Kuwait, located near the industrial and business heart of Kuwait City. It is a vital international maritime hub handling a wide range of global cargo and commercial shipping. Our taxi service offers professional transfers for business travelers and maritime staff needing efficient access to the port.',
        features: [
            'Kuwait\'s primary commercial seaport and maritime hub',
            'Strategically located near Shuwaikh Industrial Area',
            'Equipped with modern shipping and logistics facilities',
            'Handles a significant volume of Kuwait\'s international trade',
            'Essential gateway for regional and global maritime commerce',
        ],
        travelTips: [
            'Port entry often requires specific documentation; carry your business IDs or permits.',
            'Allow time for vehicle and personnel security checks at the main gates.',
            'Industrial area traffic can be heavy during weekday mornings and afternoons.',
            'Specify the terminal or office building within the port for an accurate drop-off.',
            'Keep your driver\'s contact information for arranging return trips from the port.',
        ],
        faq: [
            { question: 'How do I get to Shuwaikh Port?', answer: 'We provide direct transfers from any hotel or business address in Kuwait City to Shuwaikh Port.' },
            { question: 'Do you offer airport pickups for port visitors?', answer: 'Yes. We provide direct transfers from Kuwait International Airport (KWI) to the port.' },
            { question: 'Are executive vehicles available for business visitors?', answer: 'Yes. We offer executive sedans and SUVs for professional visits to the port.' },
            { question: 'How long is the drive from the city center?', answer: 'From Kuwait City center, the drive takes approximately 15 to 25 minutes.' },
            { question: 'Can I book a return transfer from the port?', answer: 'Yes. Scheduled return pickups ensure you have a ride ready at the scheduled time.' },
        ],
        relatedRoutes: [
            { name: 'Kuwait City Taxi Service', slug: '/city/kuwait-city-taxi', type: 'city' },
            { name: 'Kuwait Airport Taxi', slug: '/airport/kuwait-airport-taxi', type: 'airport' },
            { name: 'Taxi to Avenues Mall', slug: '/taxi-to-mall/avenues-mall-kuwait-city', type: 'route' },
        ],
    },
    {
        slug: 'khalifa-port-abu-dhabi',
        portName: 'Khalifa Port',
        portType: 'Seaport',
        city: 'Abu Dhabi',
        cityCountry: 'United Arab Emirates',
        locationDetails: 'Taweelah, Abu Dhabi (Between Abu Dhabi and Dubai)',
        approxTravelTime: '30–50 minutes from Abu Dhabi city center',
        description: 'Taxi to Khalifa Port Abu Dhabi. Professional transfers to the high-tech seaport and maritime hub located in Taweelah.',
        longDescription: 'Khalifa Port is one of the world\'s most technologically advanced seaports, located in the Taweelah area of Abu Dhabi. It is a critical international maritime hub and part of the Khalifa Industrial Zone (KIZAD), serving as a gateway for global trade. Our taxi service provides efficient transportation for employees, business visitors, and industrial professionals to this key site.',
        features: [
            'One of the world\'s fastest-growing and most advanced seaports',
            'Strategically located between Abu Dhabi and Dubai cities',
            'Integrated with the Khalifa Industrial Zone (KIZAD)',
            'Features state-of-the-art automated terminal facilities',
            'Deep-water port capable of handling the world\'s largest vessels',
        ],
        travelTips: [
            'Plan for a longer drive as the port is located outside the main Abu Dhabi city area.',
            'Ensure you have the correct gate and terminal information before starting the journey.',
            'Carry necessary industrial or port entry permits for security clearance.',
            'The E11 highway connecting Abu Dhabi and Dubai provides the main access route.',
            'Pre-book return transfers as on-demand taxis may be limited in the industrial area.',
        ],
        faq: [
            { question: 'How do I get to Khalifa Port?', answer: 'We offer direct transfers from Abu Dhabi city center or Dubai to Khalifa Port.' },
            { question: 'Can I get a taxi from Abu Dhabi Airport to Khalifa Port?', answer: 'Yes. We provide direct transfers from Zayed International Airport to the port.' },
            { question: 'Do you serve both Abu Dhabi and Dubai based visitors?', answer: 'Yes. Due to its location in Taweelah, we provide transfers from both major cities.' },
            { question: 'Are SUVs available for industrial site visits?', answer: 'Yes. We have a range of SUVs and vans suitable for site visits and business teams.' },
            { question: 'How long is the drive from Abu Dhabi city?', answer: 'The journey typically takes 35 to 45 minutes depending on traffic conditions.' },
        ],
        relatedRoutes: [
            { name: 'Abu Dhabi Taxi Service', slug: '/city/abu-dhabi-taxi', type: 'city' },
            { name: 'Abu Dhabi Airport Taxi', slug: '/airport/abu-dhabi-airport-taxi', type: 'airport' },
            { name: 'Dubai to Abu Dhabi Taxi', slug: '/routes/dubai-to-abu-dhabi-taxi', type: 'route' },
        ],
    },
    {
        slug: 'port-sultan-qaboos-muscat',
        portName: 'Port Sultan Qaboos',
        portType: 'Cruise Terminal',
        city: 'Muscat',
        cityCountry: 'Oman',
        locationDetails: 'Muttrah, Muscat',
        approxTravelTime: '20–40 minutes from central Muscat and airport',
        description: 'Taxi to Port Sultan Qaboos in Muttrah. Transfers for cruise passengers and visitors to Oman\'s historic maritime gateway in Muscat.',
        longDescription: 'Port Sultan Qaboos, located in the historic district of Muttrah, is the primary cruise port for Muscat, Oman. It welcomes international cruise ships and is a major tourist gateway due to its proximity to the Muttrah Souq and Corniche. Our taxi service provides easy access for cruise passengers arriving or departing Muscat, ensuring a smooth transition to their Next destination.',
        features: [
            'Historic maritime gateway and primary cruise port of Oman',
            'Located in the heart of the Muttrah cultural district',
            'Scenic harbor area surrounded by dramatic mountain scenery',
            'Walking distance to the famous Muttrah Souq and Corniche',
            'Essential hub for international cruise tourism in the Gulf',
        ],
        travelTips: [
            'Confirm your cruise ship\'s arrival and departure times for timely transfers.',
            'The port is located in Muttrah; allow for city traffic, especially in the late afternoons.',
            'Carry your passport as it will be required for port clearance and boarding.',
            'Inform your driver if you are carrying extra luggage for a long cruise voyage.',
            'Arrange a return pickup to your hotel or the airport after disembarkation.',
        ],
        faq: [
            { question: 'How do I get to Port Sultan Qaboos?', answer: 'We provide direct taxi transfers from any hotel or area in Muscat to the port entrance.' },
            { question: 'Is airport transfer available to the Muscat port?', answer: 'Yes. We offer transfers from Muscat International Airport (MCT) to the port.' },
            { question: 'Can large groups travel together to the cruise ship?', answer: 'Yes. We have vans and minibuses for groups and families traveling with cruise luggage.' },
            { question: 'Is the port near the city attractions?', answer: 'Yes. The port is located right next to the historic Muttrah Souq and Corniche.' },
            { question: 'Can I book a taxi for a city tour from the port?', answer: 'Yes. We can arrange a driver to take you on a city tour after your arrival at the port.' },
        ],
        relatedRoutes: [
            { name: 'Muscat Airport Taxi', slug: '/airport/muscat-airport-taxi', type: 'airport' },
            { name: 'Muscat Taxi Service', slug: '/city/muscat-taxi', type: 'city' },
            { name: 'Taxi to Muscat Old Town', slug: '/taxi-to-landmark/muscat-old-town-muscat', type: 'route' },
        ],
    },
    {
        slug: 'khalifa-bin-salman-port-manama',
        portName: 'Khalifa Bin Salman Port',
        portType: 'Seaport',
        city: 'Manama',
        cityCountry: 'Bahrain',
        locationDetails: 'Hidd, Bahrain',
        approxTravelTime: '20–35 minutes from Manama city center',
        description: 'Taxi to Khalifa Bin Salman Port in Bahrain. Punctual transfers for cruise passengers and maritime visitors to Bahrain\'s international port.',
        longDescription: 'Khalifa Bin Salman Port is the premier maritime gateway to Bahrain, located in the Hidd area. It serves as both a major commercial seaport and an international cruise terminal, welcoming thousands of visitors to the Kingdom annually. Our taxi service provides reliable transportation for cruise passengers and business visitors between the port and Manama city center, hotels, and the airport.',
        features: [
            'Bahrain\'s major international seaport and cruise terminal hub',
            'State-of-the-art maritime facilities for cargo and passengers',
            'Strategically located to serve the northern and central Gulf region',
            'Hosts international cruise ships during the seasonal Gulf circuits',
            'Key gateway for the Kingdom\'s international maritime trade',
        ],
        travelTips: [
            'Confirm which specific terminal your cruise ship or meeting is located in.',
            'Allow time for security gate processing upon entry to the port facility.',
            'Carry your valid ID or passport for presentation at the security checkpoints.',
            'Port traffic can increase during major ship embarkation and disembarkation days.',
            'Pre-book your return transfer to ensure a driver is waiting when you arrive.',
        ],
        faq: [
            { question: 'How do I get to Khalifa Bin Salman Port?', answer: 'We offer direct transfers from any hotel or location in Manama to-Hidd for the port.' },
            { question: 'Is airport transfer available from Bahrain Airport?', answer: 'Yes. We provide direct transfers from Bahrain International Airport (BAH) to the port.' },
            { question: 'Are there vehicles for large tourist families?', answer: 'Yes. We have SUVs and vans suitable for families and groups with luggage.' },
            { question: 'How far is the port from Manama city center?', answer: 'The port is approximately a 20 to 30 minute drive from central Manama.' },
            { question: 'Can I book a return taxi from the port?', answer: 'Yes. Return transfers can be scheduled to match your cruise arrival time.' },
        ],
        relatedRoutes: [
            { name: 'Bahrain Airport Taxi', slug: '/airport/bahrain-airport-taxi', type: 'airport' },
            { name: 'Manama to Al Khobar Taxi', slug: '/routes/manama-to-al-khobar-taxi', type: 'route' },
            { name: 'Dammam to Manama Taxi', slug: '/routes/dammam-to-manama-taxi', type: 'route' },
        ],
    },
];
