export interface TransferPage {
    slug: string;
    airportName: string;
    areaName: string;
    city: string;
    country: string;
    distance: string;
    travelTime: string;
    description: string;
    longDescription: string;
    pickupProcess: string[];
    travelTips: string[];
    faq: { question: string; answer: string }[];
    relatedRoutes: { name: string; slug: string; type: 'city' | 'airport' | 'route' }[];
}

export const transferPages: TransferPage[] = [
    {
        slug: 'dubai-airport-to-dubai-marina',
        airportName: 'Dubai International Airport (DXB)',
        areaName: 'Dubai Marina',
        city: 'Dubai',
        country: 'United Arab Emirates',
        distance: '33 km',
        travelTime: '30–45 minutes',
        description: 'Taxi from Dubai Airport to Dubai Marina. Reliable airport pickup and transfer to the waterfront district of Dubai.',
        longDescription: 'Our airport transfer service from Dubai International Airport (DXB) to Dubai Marina provides a seamless and comfortable journey to one of Dubai\'s most vibrant districts. Whether you are staying at a marina-side hotel or a residential apartment, our professional drivers ensure a timely arrival at your exact drop-off point, navigating the E11 highway with ease.',
        pickupProcess: [
            'Driver meets passengers in the arrivals hall after customs.',
            'Personalized name board for easy identification.',
            'Direct pickup from Terminal 1, 2, or 3.',
            'Assistance with luggage from the terminal to the vehicle.',
        ],
        travelTips: [
            'Confirm your arrival terminal (T1, T2, or T3) during booking.',
            'Share your flight details for real-time delay monitoring.',
            'Confirm the exact building or hotel name in Dubai Marina for the drop-off.',
            'Allow extra time for travel during the evening rush hour on Sheikh Zayed Road.',
        ],
        faq: [
            { question: 'How long does the transfer from Dubai Airport to Dubai Marina take?', answer: 'The journey typically takes 30 to 45 minutes depending on traffic conditions.' },
            { question: 'Can the taxi pick up from the arrivals terminal?', answer: 'Yes, our meet and greet service takes place directly in the arrivals hall.' },
            { question: 'Can groups travel together to the Marina?', answer: 'Yes, we have SUVs and vans like the GMC and Hiace for larger groups.' },
            { question: 'Is flight tracking included?', answer: 'Yes, we monitor your flight and adjust the pickup time for any delays.' },
            { question: 'How do I identify my driver?', answer: 'Your driver will be holding a sign with your name in the designated arrivals area.' },
        ],
        relatedRoutes: [
            { name: 'Dubai Taxi Service', slug: '/city/dubai-taxi', type: 'city' },
            { name: 'Dubai Airport Taxi', slug: '/airport/dubai-airport-taxi', type: 'airport' },
            { name: 'Taxi to Dubai Mall', slug: '/taxi-to-mall/dubai-mall-dubai', type: 'route' },
        ],
    },
    {
        slug: 'dubai-airport-to-palm-jumeirah',
        airportName: 'Dubai International Airport (DXB)',
        areaName: 'Palm Jumeirah',
        city: 'Dubai',
        country: 'United Arab Emirates',
        distance: '35 km',
        travelTime: '35–50 minutes',
        description: 'Taxi from Dubai Airport to Palm Jumeirah. Direct airport transfers to all hotels and residences on the Palm.',
        longDescription: 'Travel from Dubai International Airport (DXB) to the iconic Palm Jumeirah with our dedicated taxi service. We provide door-to-door transportation to all hotels on the Crescent, including Atlantis The Palm, and to residential villas. Our drivers are experienced in navigating the Palm\'s unique road network for a smooth arrival.',
        pickupProcess: [
            'Professional driver meets you at the airport arrivals gate.',
            'Support with luggage and direction to the vehicle.',
            'Pickup available 24/7 from any Dubai International terminal.',
            'Driver assists with loading suitcases and equipment.',
        ],
        travelTips: [
            'Confirm your hotel name or villa Frond number correctly.',
            'The Crescent of the Palm can take longer to reach than the Trunk.',
            'Flight numbers are required for accurate meet and greet coordination.',
            'Request a child seat in advance if traveling with young children.',
        ],
        faq: [
            { question: 'How long is the drive to Palm Jumeirah?', answer: 'The drive usually takes 35 to 50 minutes, depending on the hotel location on the Palm.' },
            { question: 'Are taxis available for 5 or more passengers?', answer: 'Yes, we provide large SUVs and passenger vans for families and groups.' },
            { question: 'Can I book a transfer to a private villa?', answer: 'Yes, we provide door-to-door service to any residential address on the Palm.' },
            { question: 'What happens if my luggage is extra-large?', answer: 'We recommend booking a GMC or Hiace van for extra-large luggage or sport equipment.' },
            { question: 'Can I schedule a return pickup from the Palm?', answer: 'Yes, scheduled return transfers to the airport can be arranged.' },
        ],
        relatedRoutes: [
            { name: 'Dubai Taxi Service', slug: '/city/dubai-taxi', type: 'city' },
            { name: 'Dubai Airport Taxi', slug: '/airport/dubai-airport-taxi', type: 'airport' },
            { name: 'Taxi to Atlantis The Palm', slug: '/taxi-to-landmark/atlantis-the-palm-dubai', type: 'route' },
        ],
    },
    {
        slug: 'riyadh-airport-to-olaya-district',
        airportName: 'King Khalid International Airport (RUH)',
        areaName: 'Olaya District',
        city: 'Riyadh',
        country: 'Saudi Arabia',
        distance: '38 km',
        travelTime: '30–45 minutes',
        description: 'Taxi from Riyadh Airport to Olaya District. Professional transfers to the central business and retail hub of Riyadh.',
        longDescription: 'Our taxi service from King Khalid International Airport (RUH) to the Olaya District offers reliable transportation to the heart of the Saudi capital. We serve all corporate offices, major hotels, and residential buildings in Olaya, ensuring business and leisure travelers reach their destination efficiently.',
        pickupProcess: [
            'Driver meets passengers at the designated airport arrivals area.',
            'Punctual pickup from Terminal 1, 2, 3, 4, or 5.',
            'Assistance with luggage and guidance to the vehicle.',
            'Help with baggage loading and passenger boarding.',
        ],
        travelTips: [
            'Olaya is the central business hub; allow extra time during evening rush hours.',
            'Specify whether you are heading to Olaya North or South.',
            'Provide your flight number for real-time arrival monitoring.',
            'Confirm the office or hotel name for a direct drop-off at the entrance.',
        ],
        faq: [
            { question: 'How long is the journey to Olaya District?', answer: 'The journey typically takes 30 to 45 minutes depending on traffic conditions on Airport Road.' },
            { question: 'Can the driver pick me up from Terminal 5?', answer: 'Yes, we provide pickups from all KKIA terminals including Terminal 5.' },
            { question: 'Are executive sedans available for business trips?', answer: 'Yes, Mercedes S-Class and BMW models are available for business travel.' },
            { question: 'Can I book a return transfer from Olaya?', answer: 'Yes, you can pre-book a return trip to the airport from any location in Olaya.' },
            { question: 'Is the service available at night?', answer: 'Yes, we provide 24/7 airport transfers to and from the Olaya district.' },
        ],
        relatedRoutes: [
            { name: 'Riyadh Taxi Service', slug: '/city/riyadh-taxi', type: 'city' },
            { name: 'Riyadh Airport Taxi', slug: '/airport/riyadh-airport-taxi', type: 'airport' },
            { name: 'Taxi to Kingdom Centre', slug: '/taxi-to-landmark/kingdom-centre-tower-riyadh', type: 'route' },
        ],
    },
    {
        slug: 'doha-airport-to-west-bay',
        airportName: 'Hamad International Airport (DOH)',
        areaName: 'West Bay',
        city: 'Doha',
        country: 'Qatar',
        distance: '20 km',
        travelTime: '15–25 minutes',
        description: 'Taxi from Doha Airport to West Bay. Professional airport transfers to the skyline and business district of Doha.',
        longDescription: 'Travel from Hamad International Airport (DOH) to the West Bay district with our professional airport transfer service. We provide door-to-door transportation to the skyscrapers, high-standard hotels, and corporate offices of Doha\'s primary business area. Our drivers ensure a smooth and punctual arrival for every passenger.',
        pickupProcess: [
            'Meet and greet service in the Hamad Airport arrivals hall.',
            'Assistance with carrying and loading your luggage.',
            'Driver waits at the arrival exit with a personalized sign.',
            'Safe and direct transfer to your West Bay destination.',
        ],
        travelTips: [
            'West Bay is the financial hub; expect traffic during morning business hours.',
            'Confirm the specific tower or hotel name for an accurate drop-off.',
            'Flight details assist us in tracking your arrival and adjusting pickup times.',
            'Pre-book for a guaranteed meet and greet service at the airport.',
        ],
        faq: [
            { question: 'How long is the transfer from Doha Airport to West Bay?', answer: 'The journey usually takes 15 to 25 minutes depending on current traffic.' },
            { question: 'Can the driver assist with several bags?', answer: 'Yes, our drivers provide full assistance with luggage loading and unloading.' },
            { question: 'Are larger vehicles available for group transfers?', answer: 'Yes, we offer SUVs and passenger vans for groups traveling to West Bay.' },
            { question: 'Is flight monitoring included in the service?', answer: 'Yes, we monitor your flight status to ensure the driver is there when you land.' },
            { question: 'Can I book a return taxi to the airport?', answer: 'Yes, return transfers from West Bay to the airport can be scheduled in advance.' },
        ],
        relatedRoutes: [
            { name: 'Doha Taxi Service', slug: '/city/doha-taxi', type: 'city' },
            { name: 'Doha Airport Taxi', slug: '/airport/doha-airport-taxi', type: 'airport' },
            { name: 'Taxi to Souq Waqif', slug: '/taxi-to-landmark/souq-waqif-doha', type: 'route' },
        ],
    },
    {
        slug: 'kuwait-airport-to-salmiya',
        airportName: 'Kuwait International Airport (KWI)',
        areaName: 'Salmiya',
        city: 'Kuwait City',
        country: 'Kuwait',
        distance: '22 km',
        travelTime: '20–30 minutes',
        description: 'Taxi from Kuwait Airport to Salmiya. Reliable airport pickups to the popular retail and residential district of Kuwait.',
        longDescription: 'Our airport transfer service from Kuwait International Airport (KWI) to Salmiya provides convenient and reliable transportation to one of Kuwait\'s most lively districts. We serve all areas of Salmiya, including the beachfront, shopping malls, and residential complexes, ensuring a comfortable start to your visit.',
        pickupProcess: [
            'Meet and greet service at the Kuwait Airport arrivals hall.',
            'Assistance with luggage from the terminal building.',
            'Driver monitors your arrival terminal (T1, T4, or T5).',
            'Direct transportation to your Salmiya residential or hotel address.',
        ],
        travelTips: [
            'Confirm if your flight arrives at Terminal 1, Terminal 4 (Kuwait Airways), or Terminal 5 (Jazeera).',
            'Allow extra time for travel during the afternoon weekend rush in Salmiya.',
            'Share your exact hotel or building location for a direct drop-off.',
            'Pre-booking ensures your vehicle is ready upon arrival at the airport.',
        ],
        faq: [
            { question: 'How long is the ride to Salmiya?', answer: 'The journey typically takes 20 to 30 minutes depending on traffic conditions.' },
            { question: 'Can I get a pickup from Terminal 4?', answer: 'Yes, we serve all terminals at Kuwait International Airport including Terminal 4.' },
            { question: 'Are SUVs available for families with large suitcases?', answer: 'Yes, SUVs and high-capacity vans are available for family luggage.' },
            { question: 'Can I book a return transfer from Salmiya?', answer: 'Yes, we provide scheduled return transfers to the airport from Salmiya.' },
            { question: 'What is the best time to travel to avoid traffic?', answer: 'Mid-morning and late evening are usually the best times to avoid Salmiya traffic.' },
        ],
        relatedRoutes: [
            { name: 'Kuwait City Taxi Service', slug: '/city/kuwait-city-taxi', type: 'city' },
            { name: 'Kuwait Airport Taxi', slug: '/airport/kuwait-airport-taxi', type: 'airport' },
            { name: 'Taxi to The Avenues', slug: '/taxi-to-mall/the-avenues-mall-kuwait-city', type: 'route' },
        ],
    },
    {
        slug: 'muscat-airport-to-qurum',
        airportName: 'Muscat International Airport (MCT)',
        areaName: 'Qurum',
        city: 'Muscat',
        country: 'Oman',
        distance: '25 km',
        travelTime: '20–30 minutes',
        description: 'Taxi from Muscat Airport to Qurum. Professional transfers to the beautiful coastal and residential area of Muscat.',
        longDescription: 'Transfer from Muscat International Airport (MCT) to the Qurum district with our professional chauffeur service. We provide reliable transportation to Qurum Beach, residential areas, and commercial centers. Our drivers ensure a high standard of service for every passenger arriving in the Omani capital.',
        pickupProcess: [
            'Driver meets passengers at the Muscat Airport arrival hall.',
            'Assistance with luggage and help with loading.',
            'Personalized sign for easy driver recognition.',
            'Professional and direct transfer to your Qurum address.',
        ],
        travelTips: [
            'The Muscat airport is modern and efficient; following signs to arrivals is easy.',
            'Qurum is a central hub; check your building name for the most accurate drop-off.',
            'Flight tracking is included to ensure your driver is waiting when you land.',
            'Booking in advance is recommended for late-night international arrivals.',
        ],
        faq: [
            { question: 'How long is the transfer to Qurum?', answer: 'The journey typically takes 20 to 30 minutes from Muscat Airport.' },
            { question: 'Can the driver assist with multiple bags?', answer: 'Yes, our drivers provide full assistance with your luggage.' },
            { question: 'Are SUVs available for group travel?', answer: 'Yes, we offer comfortable SUVs and vans for groups and families.' },
            { question: 'Is the service available for early morning flights?', answer: 'Yes, our airport transfer service in Muscat operates 24/7.' },
            { question: 'Can I schedule a return pickup to the airport?', answer: 'Yes, return transfers from Qurum can be pre-booked at any time.' },
        ],
        relatedRoutes: [
            { name: 'Muscat Taxi Service', slug: '/city/muscat-taxi', type: 'city' },
            { name: 'Muscat Airport Taxi', slug: '/airport/muscat-airport-taxi', type: 'airport' },
            { name: 'Taxi to Muscat Old Town', slug: '/taxi-to-landmark/muscat-old-town-muscat', type: 'route' },
        ],
    },
    {
        slug: 'bahrain-airport-to-juffair',
        airportName: 'Bahrain International Airport (BAH)',
        areaName: 'Juffair',
        city: 'Manama',
        country: 'Bahrain',
        distance: '12 km',
        travelTime: '15–20 minutes',
        description: 'Taxi from Bahrain Airport to Juffair. Quick and reliable airport transfers to the popular district of Manama.',
        longDescription: 'Our airport transfer service from Bahrain International Airport (BAH) to Juffair provides a fast and efficient way to reach your hotel or residence. Juffair is a major hub for international visitors, and our professional drivers are dedicated to providing punctual and comfortable transportation from the airport arrivals to your door.',
        pickupProcess: [
            'Meet and greet service at the Bahrain Airport arrivals area.',
            'Assistance with carrying and loading your suitcases.',
            'Driver monitors your flight for a timely pickup.',
            'Direct transfer to any tower or street in Juffair.',
        ],
        travelTips: [
            'Bahrain Airport is centrally located; the drive to Juffair is relatively short.',
            'Confirm the name of your residential tower or hotel for the driver.',
            'Peak traffic in Manama can occur during morning and late afternoon.',
            'Pre-book your vehicle to ensure a dedicated driver awaits your flight.',
        ],
        faq: [
            { question: 'How long does the transfer to Juffair take?', answer: 'The journey usually takes 15 to 20 minutes depending on traffic.' },
            { question: 'Is pickup at arrivals terminal included?', answer: 'Yes, our driver will meet you at the arrivals hall with a name board.' },
            { question: 'Are there vehicles for large luggage?', answer: 'Yes, we have SUVs and larger vans suitable for multiple pieces of luggage.' },
            { question: 'Can I book a return transfer from Juffair?', answer: 'Yes, scheduled return transfers to the airport are available 24/7.' },
            { question: 'Can groups travel together?', answer: 'Yes, we have high-capacity vans like the Hyundai Staria for groups.' },
        ],
        relatedRoutes: [
            { name: 'Bahrain Airport Taxi', slug: '/airport/bahrain-airport-taxi', type: 'airport' },
            { name: 'Manama Taxi Service', slug: '/city/manama-taxi', type: 'city' },
            { name: 'Taxi to Bahrain Mall', slug: '/taxi-to-mall/city-centre-bahrain-manama', type: 'route' },
        ],
    },
    {
        slug: 'abu-dhabi-airport-to-saadiyat-island',
        airportName: 'Zayed International Airport (AUH)',
        areaName: 'Saadiyat Island',
        city: 'Abu Dhabi',
        country: 'United Arab Emirates',
        distance: '30 km',
        travelTime: '25–35 minutes',
        description: 'Taxi from Abu Dhabi Airport to Saadiyat Island. Direct transfers to the cultural and resort district of Abu Dhabi.',
        longDescription: 'Travel from Zayed International Airport (AUH) to Saadiyat Island with our professional airport transfer service. We provide door-to-door transportation to all Saadiyat resorts, the Louvre Abu Dhabi, and residential villas. Our drivers ensure a high-end experience from the moment you land in the UAE capital.',
        pickupProcess: [
            'Driver meets you in the Zayed International Airport arrivals hall.',
            'Personalized sign for quick and easy meet and greet.',
            'Full assistance with your luggage and guidance to the vehicle.',
            'Professional transfer directly to your Saadiyat Island destination.',
        ],
        travelTips: [
            'Confirm the specific resort or residential frond for your drop-off.',
            'Provide flight details for real-time tracking of your arrival.',
            'Allow extra time if your flight arrives during peak morning hours.',
            'Request a child seat if traveling to the resorts with young children.',
        ],
        faq: [
            { question: 'How long is the transfer to Saadiyat Island?', answer: 'The journey typically takes 25 to 35 minutes depending on traffic.' },
            { question: 'Are vehicles available for families with large suitcases?', answer: 'Yes, we have large SUVs and vans like the GMC and Vito available.' },
            { question: 'Can I book a transfer from Sharjah to Saadiyat?', answer: 'Yes, we offer inter-emirate transfers directly from Sharjah to Saadiyat.' },
            { question: 'Is meeting at arrivals hall standard?', answer: 'Yes, all our airport pickups include meet and greet in the arrivals area.' },
            { question: 'Can I schedule a return pickup from Saadiyat?', answer: 'Yes, you can pre-book a return transfer to the airport.' },
        ],
        relatedRoutes: [
            { name: 'Abu Dhabi Taxi Service', slug: '/city/abu-dhabi-taxi', type: 'city' },
            { name: 'Abu Dhabi Airport Taxi', slug: '/airport/abu-dhabi-airport-taxi', type: 'airport' },
            { name: 'Taxi to Louvre Abu Dhabi', slug: '/taxi-to-landmark/louvre-abu-dhabi-abu-dhabi', type: 'route' },
        ],
    },
    {
        slug: 'jeddah-airport-to-jeddah-corniche',
        airportName: 'King Abdulaziz International Airport (JED)',
        areaName: 'Jeddah Corniche',
        city: 'Jeddah',
        country: 'Saudi Arabia',
        distance: '25 km',
        travelTime: '20–35 minutes',
        description: 'Taxi from Jeddah Airport to Jeddah Corniche. Reliable airport transfers to the waterfront and coastal district of Jeddah.',
        longDescription: 'Our airport transfer service from King Abdulaziz International Airport (JED) to the Jeddah Corniche provides seamless transportation for travelers. Whether you are visiting for leisure at the waterfront or staying at a coastal hotel, our professional drivers ensure a punctual and comfortable journey from the airport arrivals directly to your destination.',
        pickupProcess: [
            'Driver meets passengers at the JED airport arrival area.',
            'Support with luggage handling and vehicle loading.',
            'Clear communication for easy meet and greet coordination.',
            'Direct transfer from the terminal to the Corniche area.',
        ],
        travelTips: [
            'Specify your hotel or landmark on the Corniche for an accurate drop-off.',
            'Jeddah traffic can be heavy during the evening and religious seasons.',
            'Share group size details to ensure the most suitable vehicle choice.',
            'Punctual flight tracking is included in all airport pickup bookings.',
        ],
        faq: [
            { question: 'How long is the drive to Jeddah Corniche?', answer: 'The journey typically takes 20 to 35 minutes depending on traffic.' },
            { question: 'Can the driver pick up from any JED terminal?', answer: 'Yes, we provide pickups from all airport terminals including the new Terminal 1.' },
            { question: 'Are SUVs available for travelers with many bags?', answer: 'Yes, we have GMC and Cadillac Escalade models for heavy luggage.' },
            { question: 'Can I book a return transfer from the Corniche?', answer: 'Yes, scheduled return transfers to the airport are available.' },
            { question: 'Is 24/7 service available?', answer: 'Yes, our airport transfer service in Jeddah operates 24 hours a day.' },
        ],
        relatedRoutes: [
            { name: 'Jeddah Taxi Service', slug: '/city/jeddah-taxi', type: 'city' },
            { name: 'Jeddah Airport Taxi', slug: '/airport/jeddah-airport-taxi', type: 'airport' },
            { name: 'Jeddah to Makkah Taxi', slug: '/routes/jeddah-to-makkah-taxi', type: 'route' },
        ],
    },
];
