export interface UniversityPage {
    slug: string;
    universityName: string;
    universityType: 'Research University' | 'Major Education Institution' | 'Student Campus' | 'International Branch Campus';
    city: string;
    cityCountry: string;
    locationDetails: string;
    approxTravelTime: string;
    description: string;
    longDescription: string;
    features: string[];
    travelTips: string[];
    faq: { question: string; answer: string }[];
    relatedRoutes: { name: string; slug: string; type: 'city' | 'airport' | 'route' }[];
}

export const universityPages: UniversityPage[] = [
    {
        slug: 'king-saud-university-riyadh',
        universityName: 'King Saud University (KSU)',
        universityType: 'Research University',
        city: 'Riyadh',
        cityCountry: 'Saudi Arabia',
        locationDetails: 'Diriyah Road, Northwest Riyadh',
        approxTravelTime: '20–40 minutes from central Riyadh',
        description: 'Taxi to King Saud University Riyadh. Reliable transportation for students, faculty, and campus visitors in Northwest Riyadh.',
        longDescription: 'King Saud University (KSU) is the leading public research university in Saudi Arabia, located in the capital city of Riyadh. It features a vast campus with numerous colleges, research centers, and a university hospital. Our taxi service provides convenient door-to-door transfers for students, visiting parents, and academic staff from any part of Riyadh or the airport.',
        features: [
            'Largest and oldest university in Saudi Arabia',
            'Extensive academic departments and research centers',
            'Home to the King Khalid University Hospital',
            'Multiple campus gates and specialized colleges',
            'Host to international academic conferences and events',
        ],
        travelTips: [
            'The KSU campus is very large; confirm which college or hall you are visiting.',
            'Identify the specific campus gate (e.g., Gate 1 or Gate 2) for your drop-off.',
            'Allow extra travel time during morning lecture hours and graduation periods.',
            'Check visitor access requirements if attending a specific academic department.',
            'Note that separate campus areas may exist for male and female students.',
        ],
        faq: [
            { question: 'How do I get to the King Saud University campus?', answer: 'We offer direct taxi transfers from any location in Riyadh. You can specify your campus gate for a precise drop-off.' },
            { question: 'Can taxis pick up from hotels or Riyadh Airport?', answer: 'Yes. We provide direct transfers from King Khalid International Airport and all hotels to the university.' },
            { question: 'Are vehicles available for groups of students?', answer: 'Yes. We have vans and minibuses like the Mercedes Sprinter and Toyota Hiace for student groups.' },
            { question: 'Do you operate during evening hours for late classes?', answer: 'Yes. Our taxi service is available 24/7 to accommodate all academic schedules.' },
            { question: 'Can I arrange a return pickup from the campus?', answer: 'Yes. We recommend scheduling your return pickup at a specific campus landmark or gate.' },
        ],
        relatedRoutes: [
            { name: 'Riyadh Taxi Service', slug: '/city/riyadh-taxi', type: 'city' },
            { name: 'Riyadh Airport Taxi', slug: '/airport/riyadh-airport-taxi', type: 'airport' },
            { name: 'Taxi to Diriyah', slug: '/taxi-to-destination/diriyah-riyadh', type: 'route' },
        ],
    },
    {
        slug: 'qatar-university-doha',
        universityName: 'Qatar University',
        universityType: 'Research University',
        city: 'Doha',
        cityCountry: 'Qatar',
        locationDetails: 'Al Tarfa, North Doha',
        approxTravelTime: '15–30 minutes from central Doha',
        description: 'Taxi to Qatar University Doha. Punctual transfers for students, visitors, and conference attendees in Al Tarfa.',
        longDescription: 'Qatar University is the main public research university in Qatar, situated in the Al Tarfa district of Doha. The campus is known for its distinct architecture and diverse academic programs. Our taxi service provides reliable transportation for the university community, including direct transfers from Hamad International Airport and major Doha neighborhoods.',
        features: [
            'Principal public institution of higher education in Qatar',
            'Hub for research and innovation in Doha',
            'Distinctively designed campus buildings and facilities',
            'Regular venue for national and international seminars',
            'Conveniently located near the Lusail development area',
        ],
        travelTips: [
            'Confirm the specific college or department name for accurate drop-off.',
            'The campus has several designated pickup and drop-off points; use the closest one.',
            'Morning arrivals are busiest; leave early to avoid gate congestion.',
            'Check for any event-specific parking or access rules if visiting for a conference.',
            'Keep your student or staff ID ready if required at certain campus areas.',
        ],
        faq: [
            { question: 'How do I reach the Qatar University campus?', answer: 'We provide direct transfers from anywhere in Doha. You can book online for a scheduled arrival.' },
            { question: 'Are airport pickups available for visiting academics?', answer: 'Yes. We offer direct airport transfers from Hamad International (DOH) to the university.' },
            { question: 'Can groups of visitors travel together?', answer: 'Yes. We have SUVs and vans available for visiting delegations or student groups.' },
            { question: 'Is it possible to book a taxi from a hotel?', answer: 'Yes. We pick up from all hotels in West Bay, The Pearl, and other Doha districts.' },
            { question: 'Can I arrange a round-trip to the university?', answer: 'Yes. You can book both your arrival and return transfers in one request.' },
        ],
        relatedRoutes: [
            { name: 'Doha Taxi Service', slug: '/city/doha-taxi', type: 'city' },
            { name: 'Doha Airport Taxi', slug: '/airport/doha-airport-taxi', type: 'airport' },
            { name: 'Taxi to Lusail Marina', slug: '/taxi-to-destination/lusail-marina-doha', type: 'route' },
        ],
    },
    {
        slug: 'american-university-in-dubai-dubai',
        universityName: 'American University in Dubai (AUD)',
        universityType: 'International Branch Campus',
        city: 'Dubai',
        cityCountry: 'United Arab Emirates',
        locationDetails: 'Sheikh Zayed Road, near Dubai Media City',
        approxTravelTime: '15–30 minutes from most Dubai areas',
        description: 'Taxi to American University in Dubai. Professional transportation for students and staff near Dubai Media City.',
        longDescription: 'The American University in Dubai (AUD) is a private, non-sectarian institution of higher learning in Dubai. Located on Sheikh Zayed Road near Dubai Media City and Dubai Marina, it is a key educational landmark in the city. Our taxi service provides efficient transfers for students and staff from across Dubai and the airport.',
        features: [
            'Leading American-accredited university in the UAE',
            'Central location near Dubai Media City and Knowledge Village',
            'Hub for international students and academic events',
            'Modern campus facilities in the heart of Dubai',
            'Close proximity to Dubai Marina and Internet City',
        ],
        travelTips: [
            'The AUD campus is located on Sheikh Zayed Road; allow for rush hour traffic.',
            'Specify the main entrance for the most direct drop-off by your driver.',
            'Arrival is recommended at least 15 minutes before your class or meeting.',
            'Use designated taxi areas for a smoother pickup after your visit.',
            'Check for any security registration required for external visitors.',
        ],
        faq: [
            { question: 'How do I get to the AUD campus by taxi?', answer: 'We offer door-to-door transfers from anywhere in Dubai directly to the AUD entrance.' },
            { question: 'Can I get a taxi from DXB or DWC airport?', answer: 'Yes. We provide direct transfers from all Dubai airports to the university.' },
            { question: 'Is pickup available from Dubai Marina hotels?', answer: 'Yes. We serve all hotels and residences in JBR, Marina, and surrounding areas.' },
            { question: 'Can multiple students share a van to campus?', answer: 'Yes. We have vans available for group commutes to the university.' },
            { question: 'Are vehicles available for evening activities?', answer: 'Yes. Our service operates 24/7, covering all evening classes and events.' },
        ],
        relatedRoutes: [
            { name: 'Dubai Taxi Service', slug: '/city/dubai-taxi', type: 'city' },
            { name: 'Dubai Airport Taxi', slug: '/airport/dubai-airport-taxi', type: 'airport' },
            { name: 'Taxi to DIFC', slug: '/taxi-to-business/difc-dubai', type: 'route' },
        ],
    },
    {
        slug: 'kuwait-university-kuwait-city',
        universityName: 'Kuwait University',
        universityType: 'Major Education Institution',
        city: 'Kuwait City',
        cityCountry: 'Kuwait',
        locationDetails: 'Multiple Campuses (Shuwaikh, Khaldiya, Adailiya)',
        approxTravelTime: '15–30 minutes from central districts',
        description: 'Taxi to Kuwait University. Reliable transfers for students and faculty across Shuwaikh and other campus locations in Kuwait.',
        longDescription: 'Kuwait University is the leading public university in Kuwait, with several campuses located across the capital city, including Shuwaikh and Khaldiya. It is the hub for higher education and research in the country. Our taxi service provides organized transfers to all Kuwait University locations from any part of the city or the airport.',
        features: [
            'State-funded public university with multiple city campuses',
            'Major center for academic and research excellence in Kuwait',
            'Regular host to national educational forums and exhibitions',
            'Diverse colleges located in Shuwaikh and other districts',
            'Central to Kuwait\'s social and academic development',
        ],
        travelTips: [
            'Confirm which specific campus (e.g., Shuwaikh or Khaldiya) you are visiting.',
            'Identify the college name for the most direct drop-off point.',
            'Traffic around Shuwaikh and central district campuses can be heavy in the morning.',
            'Coordinate with your department or host for visitor access information.',
            'Note the separate designated areas for pickup at major campus gates.',
        ],
        faq: [
            { question: 'How do I reach Kuwait University by taxi?', answer: 'We offer direct transfers from all Kuwait City districts. Specify your campus when booking.' },
            { question: 'Are airport pickups available for international students?', answer: 'Yes. We provide direct transfers from Kuwait International Airport to all campuses.' },
            { question: 'Can I book a van for our research team?', answer: 'Yes. Large SUVs and vans are available for academic groups and delegations.' },
            { question: 'Is the service available for evening graduation events?', answer: 'Yes. We provide 24/7 service including during evening ceremonies and events.' },
            { question: 'Can I schedule a daily pickup for classes?', answer: 'Yes. Recurring or scheduled pickups can be arranged for regular campus commutes.' },
        ],
        relatedRoutes: [
            { name: 'Kuwait City Taxi Service', slug: '/city/kuwait-city-taxi', type: 'city' },
            { name: 'Kuwait Airport Taxi', slug: '/airport/kuwait-airport-taxi', type: 'airport' },
            { name: 'Taxi to Kuwait Towers', slug: '/taxi-to-destination/kuwait-towers-kuwait-city', type: 'route' },
        ],
    },
    {
        slug: 'university-of-bahrain-sakhir',
        universityName: 'University of Bahrain',
        universityType: 'Student Campus',
        city: 'Sakhir (Zallaq)',
        cityCountry: 'Bahrain',
        locationDetails: 'Sakhir area, near Bahrain International Circuit',
        approxTravelTime: '25–40 minutes from central Manama',
        description: 'Taxi to University of Bahrain in Sakhir. Direct transportation for students and visitors to the main campus in Zallaq.',
        longDescription: 'The University of Bahrain is the largest public university in the Kingdom of Bahrain. Its main campus is located in the Sakhir area near Zallaq, south of the capital city. The campus is a major center for academic life, featuring various colleges and sports facilities. Our taxi service provides reliable trips to Sakhir for students and visitors.',
        features: [
            'Largest public university in the Kingdom of Bahrain',
            'Spacious main campus located in the scenic Sakhir area',
            'Campus home to diverse scientific and social colleges',
            'Center for national academic and student activities',
            'Proximity to major landmarks like Al Areen and the F1 Circuit',
        ],
        travelTips: [
            'The Sakhir campus is a 30-minute drive from Manama; plan your journey in advance.',
            'Specify the gate or college name to ensure the most convenient drop-off.',
            'Peak student hours in the morning can cause delays near the main entrance.',
            'Visitor parking can be limited; a taxi drop-off is often more efficient.',
            'Wear comfortable footwear as the campus involves significant outdoor areas.',
        ],
        faq: [
            { question: 'How do I get to the University of Bahrain campus?', answer: 'We provide door-to-door transfers from Manama, Riffa, and all other areas of Bahrain.' },
            { question: 'Can airport transfers be arranged to Sakhir?', answer: 'Yes. We offer direct transfers from Bahrain International Airport (BAH) to the university.' },
            { question: 'Are larger vehicles available for student groups?', answer: 'Yes. We have vans and buses available for groups traveling to campus together.' },
            { question: 'Do you pick up from hotels in Manama?', answer: 'Yes. We serve all hotels and residences across the city.' },
            { question: 'Is service available for the Sakhir campus in the evenings?', answer: 'Yes. Our taxi service is available 24/7 for all academic and event needs.' },
        ],
        relatedRoutes: [
            { name: 'Bahrain Taxi Service', slug: '/city/bahrain-taxi', type: 'city' },
            { name: 'Bahrain Airport Taxi', slug: '/airport/bahrain-airport-taxi', type: 'airport' },
            { name: 'Taxi to City Centre Bahrain', slug: '/taxi-to-mall/city-centre-bahrain-manama', type: 'route' },
        ],
    },
    {
        slug: 'sultan-qaboos-university-muscat',
        universityName: 'Sultan Qaboos University (SQU)',
        universityType: 'Research University',
        city: 'Muscat',
        cityCountry: 'Oman',
        locationDetails: 'Al Khoudh, Muscat',
        approxTravelTime: '20–35 minutes from Muscat city center',
        description: 'Taxi to Sultan Qaboos University in Al Khoudh. Punctual transfers for students, staff, and visitors in Muscat.',
        longDescription: 'Sultan Qaboos University (SQU) is the first and leading public university in the Sultanate of Oman. Located in Al Khoudh, Muscat, the campus is an architectural and academic landmark. It includes a university hospital and numerous research facilities. Our taxi service provides regular transportation for the SQU community and visitors.',
        features: [
            'Principal national university of the Sultanate of Oman',
            'Academically rich campus in the Al Khoudh district',
            'Home to Sultan Qaboos University Hospital',
            'Significant center for research and Omani heritage studies',
            'Regularly hosts national conferences and graduations',
        ],
        travelTips: [
            'The SQU campus is extensive; confirm whether you need the hospital or a specific college.',
            'Morning periods around the university gates can be busy; allow extra time.',
            'Dress modestly when visiting the campus as per local cultural norms.',
            'Identify the correct gate for your college to minimize walking time.',
            'Arrange for a return pickup from a clear, recognizable campus landmark.',
        ],
        faq: [
            { question: 'How do I reach the SQU campus by taxi?', answer: 'We offer direct transfers from any location in Muscat to the Al Khoudh university campus.' },
            { question: 'Is airport pickup available for visiting researchers?', answer: 'Yes. Direct transfers from Muscat International Airport (MCT) are available.' },
            { question: 'Can group vehicles be booked for university teams?', answer: 'Yes. We have SUVs and vans for departments and student groups.' },
            { question: 'Do you serve the university hospital specifically?', answer: 'Yes. We provide direct transfers to Sultan Qaboos University Hospital.' },
            { question: 'Can I book a taxi from my hotel in Muscat?', answer: 'Yes. We pick up from all hotels in areas like Ruwi, Qurum, and Al Khuwair.' },
        ],
        relatedRoutes: [
            { name: 'Muscat Airport Taxi', slug: '/airport/muscat-airport-taxi', type: 'airport' },
            { name: 'Muscat to Dubai Taxi', slug: '/routes/muscat-to-dubai-taxi', type: 'route' },
            { name: 'Taxi to Mall of Muscat', slug: '/taxi-to-mall/mall-of-muscat-muscat', type: 'route' },
        ],
    },
    {
        slug: 'new-york-university-abu-dhabi-abu-dhabi',
        universityName: 'New York University Abu Dhabi (NYUAD)',
        universityType: 'International Branch Campus',
        city: 'Abu Dhabi',
        cityCountry: 'United Arab Emirates',
        locationDetails: 'Saadiyat Island, Abu Dhabi',
        approxTravelTime: '15–25 minutes from central Abu Dhabi',
        description: 'Taxi to NYUAD Saadiyat Island. Reliable transportation for the international academic community in Abu Dhabi.',
        longDescription: 'New York University Abu Dhabi (NYUAD) is a leading liberal arts and research university located on Saadiyat Island. Part of NYU\'s global network, the campus attracts students and faculty from around the world. Our taxi service provides direct and professional transfers from central Abu Dhabi and Zayed International Airport.',
        features: [
            'Prestigious international campus on Saadiyat Island',
            'Global hub for arts, sciences, and research',
            'Modern award-winning campus infrastructure',
            'Regular host to global summits and cultural arts events',
            'Located in the heart of Abu Dhabi\'s cultural district',
        ],
        travelTips: [
            'NYUAD is located on Saadiyat Island; follow signage for the Campus Centre.',
            'Specify the Gate or Campus Center for the most direct drop-off.',
            'Allow for extra time if visiting during a major campus-wide event or concert.',
            'External visitors may require registration at the campus security gates.',
            'Use the designated taxi and chauffeur drop-off zones on the island.',
        ],
        faq: [
            { question: 'How do I reach NYUAD by taxi?', answer: 'We provide direct transfers from anywhere in Abu Dhabi or Dubai to the Saadiyat Island campus.' },
            { question: 'Are airport pickups available for NYUAD students?', answer: 'Yes. We offer direct transfers from Zayed International Airport to the campus.' },
            { question: 'Can taxis pick up from hotels on Saadiyat Island?', answer: 'Yes. We serve all hotels and residences on the island and in the city center.' },
            { question: 'Are vehicles available for a group of 4 people?', answer: 'Yes. Large SUVs like the GMC are available for shared group travel.' },
            { question: 'Is the service available for evening events at NYUAD?', answer: 'Yes. Our 24/7 service covers all late-night talks and academic events.' },
        ],
        relatedRoutes: [
            { name: 'Abu Dhabi Taxi Service', slug: '/city/abu-dhabi-taxi', type: 'city' },
            { name: 'Abu Dhabi Airport Taxi', slug: '/airport/abu-dhabi-airport-taxi', type: 'airport' },
            { name: 'Taxi to Yas Island', slug: '/taxi-to-destination/yas-island-abu-dhabi', type: 'route' },
        ],
    },
    {
        slug: 'king-abdulaziz-university-jeddah',
        universityName: 'King Abdulaziz University (KAU)',
        universityType: 'Research University',
        city: 'Jeddah',
        cityCountry: 'Saudi Arabia',
        locationDetails: 'Abdullah Sulayman Street, South Jeddah',
        approxTravelTime: '15–30 minutes from central Jeddah',
        description: 'Taxi to King Abdulaziz University Jeddah. Reliable transfers for students, staff, and visitors in South Jeddah.',
        longDescription: 'King Abdulaziz University (KAU) is one of the leading public research universities in Saudi Arabia, located in South Jeddah. The campus is home to numerous colleges, research institutes, and the KAU Hospital. Our taxi service provides organized transfers from any Jeddah district or the airport directly to the university.',
        features: [
            'Consistently ranked as a major research university in the Arab world',
            'Large-scale campus with modern educational and medical facilities',
            'Hub for innovation and intellectual activity in Jeddah',
            'Center for major national and international academic forums',
            'Significant institution for Saudi Arabia\'s medical and scientific research',
        ],
        travelTips: [
            'Identify the specific gate or college (male or female) before your drop-off.',
            'Provide the building name or number to your driver for a more precise arrival.',
            'Morning and afternoon rush hours on the main Jeddah roads can cause delays.',
            'Check for visitor access requirements at the main administrative buildings.',
            'Note that the university hospital area has a separate entrance and drop-off.',
        ],
        faq: [
            { question: 'How do I reach the KAU campus by taxi?', answer: 'We offer direct door-to-door transfers from all Jeddah neighborhoods. Simply book online.' },
            { question: 'Is airport pickup available to the university?', answer: 'Yes. We provide transfers from King Abdulaziz International Airport (JED) to the campus.' },
            { question: 'Can students share a van for group transport?', answer: 'Yes. We have vans like the Toyota Hiace available for group travel to campus.' },
            { question: 'Is service available during the graduation season?', answer: 'Yes. We scale our services to provide reliable transport during peak event times.' },
            { question: 'Can I book a return taxi for later in the day?', answer: 'Yes. You can schedule a pickup at a specific gate for your return journey.' },
        ],
        relatedRoutes: [
            { name: 'Jeddah Taxi Service', slug: '/city/jeddah-taxi', type: 'city' },
            { name: 'Jeddah Airport Taxi', slug: '/airport/jeddah-airport-taxi', type: 'airport' },
            { name: 'Taxi to Red Sea Mall', slug: '/taxi-to-mall/red-sea-mall-jeddah', type: 'route' },
        ],
    },
];
